### ISSUE TITLE
Go back to location after goto def

### ISSUE THREAD

**Issue by bgvianyc** [proofit404/anaconda-mode#100]
M-, does not seem to work.

**Comment by proofit404** [comment]
Because it is `M-*` :smile:

**Comment by bgvianyc** [comment]
Sorry, did not see in the docs, is it in there?

**Comment by proofit404** [comment]
[Second line in this section](https://github.com/proofit404/anaconda-mode#interactive-commands). I've make this `M-*` because this is convenient with `tags` package. `M-,` is popular because of `slime` package.
