### ISSUE TITLE
Going to definition of a symbol in a library

### ISSUE THREAD

**Issue by vskr** [proofit404/anaconda-mode#102]
I  am using anaconda in my emacs editor for code navigation. However, I am not able to figure out a easy way to go to definition of a symbol in a third-party python library installed on my system.

I am attaching a screenshot of what happens in my terminal when I hit (M-. , which is a shortcut for going to a definition in anaconda-mode).

Any help in figuring out to go to a definition of a library would be very helpful.

However, autocomplete works just fine requests.g results in requests.get when I do (C-M-i)

<img width="1275" alt="screen shot 2015-09-05 at 7 28 46 pm" src="https://cloud.githubusercontent.com/assets/1729153/9702151/a5e33ca4-5405-11e5-9e1c-aa3103d67653.png">

**Comment by proofit404** [comment]
Could you provide `python-shell-virtualenv-path` variable value? What is the exactly way you install `requests` library into you system?
