### ISSUE TITLE
Error on anaconda-mode-find-definitions

### ISSUE THREAD

**Issue by maxsiegel** [proofit404/anaconda-mode#105]
Putting the cursor over the final x in the following program, and pressing M-. gives an error: 
```
error in process filter: find-file-noselect: Wrong type argument: stringp, nil
error in process filter: Wrong type argument: stringp, nil
```
This is occurs even when the only installed package is anaconda-mode. However, finding the function definition works. This is on OS X 10.10.

```
def f(x):
    return 1

x = f(3)

x
```

**Comment by proofit404** [comment]
Looks like a problem with `builtin` module. Thanks for the report!

**Comment by proofit404** [comment]
Done.
