### ISSUE TITLE
Can't open file 'anaconda_mode.py'

### ISSUE THREAD

**Issue by dsdshcym** [proofit404/anaconda-mode#106]
After I upgraded anaconda-mode today, I ran into this error:
```
error in process sentinel: anaconda-mode-bootstrap-sentinel: Can't start `anaconda-mode' server
error in process sentinel: Can't start `anaconda-mode' server
```

Here is the contents of the ```*anaconda_mode*``` buffer
```
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: 
can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
```

I'm using a brew version of Python 2.7 by the way.

**Comment by proofit404** [comment]
Do you use spacemacs? What is the value of `python-shell-interpreter` variable?

**Comment by dsdshcym** [comment]
@proofit404  Yes, I'm using spacemacs. 

The value is "python".

**Comment by jonathanchu** [comment]
I'm having this same exact issue, but I'm not using spacemacs.  Previously, I saw `anaconda_mode.py` existed in the `anaconda-mode` package directory (from MELPA).  Now, it's definitely not being written to this directory.

Did something change with how `anaconda_mode.py` is packaged?

**Comment by offbyone** [comment]
I'm using Prelude, and seeing this as well:

    /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory

**Comment by offbyone** [comment]
Since it was a question above:

    python-shell-interpreter is a variable defined in `python.el'.
    Its value is "python"

    Documentation:
    Default Python interpreter for shell.

    You can customize this variable.

**Comment by offbyone** [comment]
I've temporarily worked around this (using Homebrew python) by:

    (setq anaconda-mode-server-script "/usr/local/lib/python2.7/site-packages/anaconda_mode.py")

**Comment by jonathanchu** [comment]
@offbyone cheers! This solved it for me, albeit temporarily.

**Comment by proofit404** [comment]
@jonathanchu Yes. `anaconda-mode` emacs package will install `anaconda_mode` python package into `~/.emacs.d/anaconda-mode` directory.

**Comment by proofit404** [comment]
@jonathanchu @offbyone  Looks like you are installed `anaconda_mode` python package globally in the homebrew python?

**Comment by jonathanchu** [comment]
@proofit404 @offbyone yes, I did.  I was getting the `distutils.cfg` error as documented [here](https://github.com/proofit404/anaconda-mode#distutilsoptionerror), so I installed the `anaconda-mode` package globally.  Was this wrong to do?

**Comment by proofit404** [comment]
Actually I don't know what is the best solution here. Maybe we need to make global installation official, so `anaconda-mode-server-directory` must be a function of some customizable, server version and script name. This is require more strict checks so this is future work I guess.

**Comment by offbyone** [comment]
@proofit404 I didn't do it by choice; I installed it when the pip install failed: 

    Traceback (most recent call last):
      File "<string>", line 8, in <module>
      File "<string>", line 5, in check_deps
      File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 512, in get_distribution
      File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 392, in get_provider
      File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 918, in require
      File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 805, in resolve
    pkg_resources.DistributionNotFound: anaconda-mode
    Collecting anaconda-mode==0.1.1
      Using cached anaconda_mode-0.1.1.tar.gz
    Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
      Using cached jedi-0.9.0-py2.py3-none-any.whl
    Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
      Using cached service_factory-0.1.2.tar.gz
    Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
      Using cached six-1.9.0-py2.py3-none-any.whl
    Installing collected packages: jedi, six, service-factory, anaconda-mode
    [31mException:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
        root=options.root_path,
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
        **kwargs
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
        self.move_wheel_files(self.source_dir, root=root)
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
        isolated=self.isolated,
      File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 242, in move_wheel_files
        name, user=user, home=home, root=root, isolated=isolated
      File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 192, in distutils_scheme
        i.finalize_options()
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/install.py", line 38, in finalize_options
        orig.install.finalize_options(self)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
        "must supply either home or prefix/exec-prefix -- not both"
    DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both[0m

**Comment by proofit404** [comment]
@offbyone I understand that users doesn't change any infrastructure until it doesn't works. On the other hand I can try to workaround distutils bug during installation (ignoring homebrew settings).

**Comment by offbyone** [comment]
I'd be thrilled with that. I've seen this a few times with anaconda-mode in the past. I'm not totally sure what the right way to do this is, though.

**Comment by proofit404** [comment]
Close due to #113
