### ISSUE TITLE
Running anaconda_mode.py in vagrant

### ISSUE THREAD

**Issue by synic** [proofit404/anaconda-mode#107]
Is it possible to run anaconda_mode.py in a vagrant instance, and have emacs connect to it on port 9000?  I've tried setting `anaconda-mode-server-script` to an ssh command, but that doesn't seem to work.

**Comment by proofit404** [comment]
Hello. I spent last few months rewriting significant parts of `anaconda-mode` to make this possible in the near future. Last blockers are:
* get host ip from tramp ssh name
* make `anaconda-mode-host` behave correctly
* set up test environment to reproduce remote access

Hope I can do this soon.

**Comment by synic** [comment]
Awesome.  Carry on :)

**Comment by proofit404** [comment]
:sparkles:  Done! :sparkles:
