### ISSUE TITLE
error in process sentinel: json-read: JSON readtable error

### ISSUE THREAD

**Issue by ruajhonatan** [proofit404/anaconda-mode#109]
### Good day,
when trying to load the anaconda-mode jumps me the error

```
error in process sentinel: json-read: JSON readtable error
error in process sentinel: JSON readtable error
```
anyone knows what can happen?

Thank you.

**Comment by proofit404** [comment]
Do you use http proxy?

**Comment by ruajhonatan** [comment]
do not use http proxy

**Comment by ruajhonatan** [comment]
When I install anaconda-mode from Melpa I get error:

```Warning (emacs): Unable to activate package `f'.
Required package `s-1.7.0' is unavailable```

**Comment by proofit404** [comment]
Melpa stable?

**Comment by ruajhonatan** [comment]
not

**Comment by proofit404** [comment]
Update to the master and post `*Anaconda-Response*` buffer here.
