### ISSUE TITLE
anaconda-mode-eldoc-format-definition: Wrong type argument

### ISSUE THREAD

**Issue by gabor** [proofit404/anaconda-mode#110]
i use spacemacs, which seems to come with anaconda-mode. sometimes i get the above-mentioned error-message. how to reproduce:

save this snippet as a python file,and open it with anaconda-mode:
```
data = set([
    1,
    2,
])
```
just those 4 lines.

when i open it in emacs, in anaconda-mode, and slowly move down, from line to line (let's say i wait on every line 2 seconds), when reaching the line with "2", i get this error (and a big slowdown in emacs):

```
error in process filter: anaconda-mode-eldoc-format-definition: Wrong type argument: number-or-marker-p, nil                                                                                                
error in process filter: Wrong type argument: number-or-marker-p, nil   
```

**Comment by gabor** [comment]
also, not sure if it's related, but i am on osx+homebrew+spacemacs, so to make anaconda start up at all, i had to do this:

- go to ~/.emacs.d/anaconda-mode/0.1.1
- create a ~/.pydistutils with the empty-prefix-thing
- pip install -t . anaconda_mode
- delete the ~/.pydistutils file

i'm practically cargo-culting these things, so it's possible i did something stupid here :)

**Comment by proofit404** [comment]
Thanks for report. Will try to fix this in the evening.

**Comment by gabor** [comment]
thanks for the quick response. in the meantime, how can i just disable anaconda completely (currently it's quite painful to work with the slowdown), until the problem is fixed?

**Comment by proofit404** [comment]
Remove `anaconda-mode` from `python-mode-hook` or disable `eldoc-mode` same way if only it cause your problem.

**Comment by proofit404** [comment]
Done.
