### ISSUE TITLE
Workaround distutils bug

### ISSUE THREAD

**Issue by proofit404** [proofit404/anaconda-mode#113]
Ignore distutils prefix config parameter during package installations.

**Comment by istinspring** [comment]
``` 
 File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 38, in finalize_options             |requirements.txt
    orig.install.finalize_options(self)                                                                                 |runtests.py
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install\|settings.py
.py", line 264, in finalize_options                                                                                     |tasks.py
    "must supply either home or prefix/exec-prefix -- not both"                                                         |
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both^[[0m/usr/local/Cellar/python/2.7.9/Fram\|
eworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py':
```

Do you mean this one? I just updated packages and can't use emacs because of it.

**Comment by proofit404** [comment]
Yes, I mean exactly this problem.

**Comment by proofit404** [comment]
You can find temporary workaround in #114

**Comment by istinspring** [comment]
Already fixed, thank you.

**Comment by offbyone** [comment]
@proofit404 is there any chance you've made progress on this? I appreciate that this is OSS, so no demands, but if you happen to have the time I'd love to see a fix trickle out. 

Thank you.

**Comment by proofit404** [comment]
There are a lot of work to do on this project to make it pleasant for every one. Unfortunately I doesn't have enough time to work on each issue. Currently make `anaconda-mode` work over `tramp` have biggest priority for me. Maybe I can comeback to this issue after finishing `tramp` branch.

Thanks for your patience.
Regards, Artem.

**Comment by introom** [comment]
I encountered the same problem with the latest debian sid.

The pip version is 8.1.1. There is no shipped distutils.cfg.

I ended up removing  debian's python-pip package and uses the get-pip script to get an upstream version of pip. That one also is of version 8.1.1.

**Comment by proofit404** [comment]
System wide pip installation doesn't work and pip installed with get-pip script works without any different change in the system?

**Comment by introom** [comment]
System wide pip installation doesn't work 
yes

pip installed with get-pip script works without any different change in the system?
no change required.

**Comment by proofit404** [comment]
What Linux distribution (with full version) do you use? I will try to reproduce this in virtual machine.

**Comment by introom** [comment]
debian sid 64bit.

**Comment by proofit404** [comment]
What installation method did you use? netinstall/desktop with ui installer

**Comment by introom** [comment]
I think it doesn't matter here, though.

I installed the latest Debian sid with virtualbox. The installation is done in expert-mode, and no X software is installed. So all happens within tui.

If you open up a Debian 64bit testing instance on google cloud platform, you will suffer the same issue.
I've also tested that on Linode with the same setup. Again, it will fail if you choose to install the debian packaged python-pip.

**Comment by proofit404** [comment]
Maybe we can get rid of this bug finally. I need help from person with OS X.

Given: python (2.7 for example) installed with homebrew. Code below must fail with weird distutils error. 

```bash
mkdir $HOME/.emacs.d/anaconda-mode/test/
pip install -t $HOME/.emacs.d/anaconda-mode/test/ anaconda-mode
```

At the same time some thing like this may works:

```bash
PYTHONPATH=$HOME/.emacs.d/anaconda-mode/test/ easy_install -d $HOME/.emacs.d/anaconda-mode/test/ -a anaconda_mode
```

Any volunteer to help?

**Comment by ttylec** [comment]
I confirm (OS X 10.10) that the first results in error and the latter installs without any problems. With python from homebrew.

**Comment by proofit404** [comment]
@ttylec Thanks for your help!

**Comment by sickHamm** [comment]
@proofit404  Just want you know. maybe helpful.

Debian Test has same bug；
and  `pip3  install  --system --target=~/.emacs.d/anaconda-mode/0.1.2/  anaconda_mode` work well；
I think the reason is `pip --target`     imply `--prefix`； and  '--user' and '--prefix'  could not work togther， and  on Debian systems the --user is default.

> 
--user                      Install to the Python user install directory for your platform. Typically ~/.local/,
                             On Debian systems, this is the default when running outside of a virtual environment 
-------
and not as root.
  --system                    Install using the system scheme (overrides --user on Debian systems)


ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations
---------



> pip3  install --user --prefix anaconda_mode
ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations

**Comment by sickHamm** [comment]
And why not create a virtualenv for anaconda server just like jedi.el ;

**Comment by proofit404** [comment]
@sickHamm Thanks for information you provide.

The reason to install anaconda_mode python package into directory and not in virtual environment is pretty straightforward. Last time I saw jedi.el the way it works with your own virtual environments was ugly. I don't know if it changes. If I recall correctly you need add side packages from your own virtual environment as a buffer local variable to run separate jedirpcserver for each buffer. There is a special package to simplify this. I don't like this approach at all.

Anaconda mode make it difference. All that you need is activate your project virtual environment as you usually does with python.el (set global variable ones). Anaconda mode takes care of the rest of process including installation and server monitoring. The simplest way to implement this just have a directory where anaconda_mode.py and its dependencies lives.

Hope this clarify taken design decisions a little.

Regards, Artem.

**Comment by sickHamm** [comment]
thanks for  your explanation.

and  my  explanation  maybe not very clear;
in short,
 when  install  anaconda_mode maybe should use `--system` overrides `--user `, at least on debians


> Debian Test has same bug；
but pip install --system --target=~/.emacs.d/anaconda-mode/0.1.2/ anaconda_mode work well；
I think the reason is pip --target imply --prefix； and '--user' and '--prefix' could not work togther， and on Debian systems the --user is default. the Mac OS X 's pip may default --user too.

**Comment by proofit404** [comment]
At this point we decide to move from pip to easy_install. It achieve same goal without flags conflict. You can follow related discussion in #186
