### ISSUE TITLE
can't start 'anaconda-mode' server

### ISSUE THREAD

**Issue by geekplux** [proofit404/anaconda-mode#114]
I use the master branch of spacemacs and install the python layer.

and there was a error when I open a python file first time... ( python is new to me )
Is this because of my python version?
or anaconda-mode causing it..

![70c62910-a49e-407d-801c-6e79005a6c3a](https://cloud.githubusercontent.com/assets/3816105/9831171/6578a798-597e-11e5-8547-7f55f03a73a3.png)

**Comment by proofit404** [comment]
I guess you install python from homebrew. There is `distutils.cfg` with `prefix` option in it created by homebrew. Comment this option, start emacs and open python file. `anaconda-mode` will install tiny python program for autocomplete. Then you can revert `prefix` option back.

I'll try to workaround this distutils bug as mentioned in #113 

Regards, Artem.

**Comment by geekplux** [comment]
@proofit404 Thank you

**Comment by proofit404** [comment]
@geekplux can you provide `distutils.cfg` content here so I can reproduce this in tests?

**Comment by geekplux** [comment]
@proofit404 sorry, can you tell me the path of `distutils.cfg` file? I can't find it....

**Comment by proofit404** [comment]
As far as I understand it stored at `lib/python2.7/distutils/distutils.cfg` relative to your python path installation.

**Comment by geekplux** [comment]
@proofit404 thanks, but there is no this file in my OS X, nor the folder. I have searched it by `ag`.
I used `brew` to install the python and python3.

**Comment by proofit404** [comment]
Search for something like `Frameworks/Python.framework/Versions/2.7/lib/python2.7` in your installation. I newer use mac nor homebrew so I can't answer directly.

**Comment by geekplux** [comment]
@proofit404 wow, I find it with your help.

```
[install]
prefix=/usr/local

[build_ext]
include_dirs=/usr/local/include:/usr/local/opt/openssl/include:/usr/local/opt/sqlite/include
library_dirs=/usr/local/lib:/usr/local/opt/openssl/lib:/usr/local/opt/sqlite/lib
```

You are so patient. Thank you very much.

**Comment by proofit404** [comment]
You're welcome. Thanks for info!!

**Comment by zhexuany** [comment]
@geekplux  It will be nice if you tell others what is the path then.

**Comment by log0ymxm** [comment]
@zhexuany In my case it was located at, `/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/distutils.cfg`

Notice that the error shown in the `*anaconda-mode*` buffer has the path to the distutils package which is causing the problem. That's the where the config file should be.

**Comment by proofit404** [comment]
@zhexuany It is installation dependent. For example in my case it stored deeply inside `~/.pyenv` directory.

**Comment by felix-d** [comment]
The fix worked on one of my machine but not the other one.
I still get the issue.
```
error in process sentinel: anaconda-mode-install-sentinel: Can't install `anaconda-mode' server
error in process sentinel: Can't install `anaconda-mode' server
```

**Comment by proofit404** [comment]
I need `*anaconda-mode*` buffer content.

**Comment by felix-d** [comment]
```
Traceback (most recent call last):
  File "<string>", line 6, in <module>
AttributeError: 'module' object has no attribute 'main'
```
I tried installing anaconda-mode manually using
```
python -c "
import sys
import pip
pip.main(['install', '-t', 'foobar', 'anaconda_mode==' + '0.1.1'])
"
```
and it seems to be replicating the same error. I'll try to reinstall pip and see how it goes

**Comment by felix-d** [comment]
Ok so this was an error with pip itself. Reinstalling did the trick! Thanks a lot! Sorry for the disturbance!

**Comment by proofit404** [comment]
Do you install same version of pip?

**Comment by felix-d** [comment]
@proofit404 yes, I don't know what happened there seriously, but I'm happy it works now.

**Comment by Plancalkuele** [comment]
I need help to find the distutils.cfg file. Can't find it and it drives me crazy.
I checked the following paths:
/usr/lib/pythonver/distutils/distutils.cfg

The 2.7 version folder of python has a distutils folder but the distutils.cfg file doesn't exist.

**Comment by proofit404** [comment]
```bash
find / -name distutils.cfg 2>/dev/null
```

**Comment by Plancalkuele** [comment]
No output unfortunately when using the find command. Am I missing any packages maybe?

**Comment by proofit404** [comment]
This mean the problem is not in the distutils. Any anaconda-mode related messages or buffers appears during installation process?

**Comment by Plancalkuele** [comment]
That's where I get the ''error: can't combine user with prefix, exec_prefix/home, or install_(plat)base" message
```
Downloading/unpacking six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: anaconda-mode, jedi, service-factory, six
  Running setup.py install for anaconda-mode
    error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-cvBegv/anaconda-mode/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gsYPbm-record/install-record.txt --single-version-externally-managed --compile --user --home=/tmp/tmpuiNqqx:
    running install

error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

**Comment by proofit404** [comment]
What are you operation system, python version and the way you are install both python and emacs.

**Comment by Plancalkuele** [comment]
Ubuntu Studio 15.10 Wily Werewol 64 bit Version
I always try to install everything via sudo apt-get install. So I installed emacs via apt-get install. spacemacs via ''' git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d '''
''' python -V ''' gives me Python 2.7.10

**Comment by proofit404** [comment]
Try following bash script:
```bash
mkdir -p ~/.emacs.d/.cache/anaconda-mode/0.1.1
pip install -t ~/.emacs.d/.cache/anaconda-mode/0.1.1 anaconda_mode
```

**Comment by Plancalkuele** [comment]
This is what I get when following your bash script...same as before:
```
Downloading/unpacking anaconda-mode
  Downloading anaconda_mode-0.1.1.tar.gz
  Running setup.py (path:/tmp/pip-build-0h_G2q/anaconda-mode/setup.py) egg_info for package anaconda-mode
    
    no previously-included directories found matching 'test'
Downloading/unpacking jedi>=0.9.0 (from anaconda-mode)
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB): 157kB downloaded
Downloading/unpacking service-factory>=0.1.2 (from anaconda-mode)
  Downloading service_factory-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip-build-0h_G2q/service-factory/setup.py) egg_info for package service-factory
    
Downloading/unpacking six (from service-factory>=0.1.2->anaconda-mode)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: anaconda-mode, jedi, service-factory, six
  Running setup.py install for anaconda-mode
    error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-0h_G2q/anaconda-mode/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ubVjGc-record/install-record.txt --single-version-externally-managed --compile --user --home=/tmp/tmptAMc4B:
    running install

error: can't combine user with prefix, exec_prefix/home, or install_(plat)base

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-0h_G2q/anaconda-mode/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ubVjGc-record/install-record.txt --single-version-externally-managed --compile --user --home=/tmp/tmptAMc4B failed with error code 1 in /tmp/pip-build-0h_G2q/anaconda-mode
Storing debug log for failure in /home/haydnmoans/.pip/pip.log
```

**Comment by proofit404** [comment]
Hmm. Actually I don't know what to do. I'll try to fix this by monkey-patching distutils during server installation. Will do this ASAP. Please wait for updated version.

**Comment by Plancalkuele** [comment]
Thank you for your effort! Looking forward doing python programming with Spacemacs.

**Comment by proofit404** [comment]
@Plancalkuele I've setup ubuntu studio in my virualbox, run `apt-get update`, `apt-get upgrade`, `apt-get install python-pip emacs`. So far test environment have following:

* Emacs version 24.3.1
* Python version 2.7.6
* LSB release 14.04

`anaconda-mode` install process was successful at first try. Maybe you can provide more info?

**Comment by Plancalkuele** [comment]
When I check the packages installed with sudo apt-cache policy I get the following:
emacs -> 46.1 -> https://launchpad.net/ubuntu/wily/arm64/emacs/46.1
python -> 2.7.9-1 -> https://launchpad.net/ubuntu/wily/amd64/python/2.7.9-1
lsb-release -> 4.1+Debian11ubuntu8 -> https://answers.launchpad.net/ubuntu/wily/amd64/lsb-release/4.1+Debian11ubuntu8

Strangely, now I'm in anaconda-mode when I open a python file and I don't get the 
_error: can't combine user with prefix, exec_prefix/home, or install_(plat)base_ anymore. Maybe a restart of my computer and your pip install suggestion solved this.

But now I get the message:
eldoc error: (error 127.0.0.1&3anil/80 name or service not known)

Guess I have also to tell spacemacs to load the elddoc package, tried that with:
dotspacemacs-additional-packages '(eldoc)

But I still do get the same message. Not that familiar yet with spacemacs...was that the right way to load the eldoc package?

**Comment by proofit404** [comment]
If I understand correctly spacemacs [enable](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/packages.el#L65-L66) eldoc for you. I guess port detection doesn't work correctly if `python-shell-interpreter` was set to `ipython`. Try to add following to your config:
```lisp
(setq python-shell-interpreter "python")
```
And report if it help or not.

**Comment by Plancalkuele** [comment]
But you can also find the following lines in [packages.el](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/packages.el#L65-L66):
`(defun python-setup-shell ()
        (if (executable-find "ipython")
            (progn
              (setq python-shell-interpreter "ipython")
              (when (version< emacs-version "24.4")
                ;; these settings are unnecessary and even counter-productive on emacs 24.4 and newer
                (setq python-shell-prompt-regexp "In \\[[0-9]+\\]: "
                      python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
                      python-shell-completion-setup-code "from IPython.core.completerlib import module_completion"
                      python-shell-completion-module-string-code "';'.join(module_completion('''%s'''))\n"
                      python-shell-completion-string-code "';'.join(get_ipython().Completer.all_completions('''%s'''))\n")))
          (setq python-shell-interpreter "python")))`

So actually python-shell-interpreter gets set to python if not ipython is found as executable.
I don't want to fix it to python since I'm also using ipython with orgmode for evaluating python code in blocks. But maybe I don't understand the above lines correctly.

**Comment by proofit404** [comment]
I don't ask you to change this variable permanently, just try it and see if it solve your problem or not. AFAIK `ob-ipython` package doesn't use this variable.

**Comment by Plancalkuele** [comment]
Adding
`(setq python-shell-interpreter "python")`
after
`(defun dotspacemacs/user-config ())`
in .spacemac did not solve the problem. Still get the same error:
`eldoc error: (error 127.0.0.1&3anil/80 name or service not known)`

**Comment by proofit404** [comment]
No idea what we can to try else.

**Comment by euccastro** [comment]
I'm on Ubuntu 15.10 too.  On a whim, I tried the following workaround:

    mkdir -p ~/.emacs.d/.cache/anaconda-mode/0.1.1
    sudo pip install -t ~/.emacs.d/.cache/anaconda-mode/0.1.1 anaconda_mode
    sudo chown -R es:es ~/.emacs.d/.cache/anaconda-mode/0.1.1

All seems to work fine (maybe the sudo removes the `--user` flag, or something?).  I only get code completion if I have a Python shell running (`,si` in spacemacs), but maybe that's how it should be?

**Comment by proofit404** [comment]
I only get code completion if I have a Python shell running

This mean you don't use anaconda-mode at all. Only inferior python process. Do you see any errors in `*anaconda-mode*`, `*anaconda-response*` or `*Messages*` buffers?

**Comment by euccastro** [comment]
Hm, you're right, I get the following error in `*anaconda-mode*`

```
127.0.0.1 - - [19/Feb/2016 06:17:07] ================================================================================
Traceback (most recent call last):
  File "/home/es/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/es/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/es/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/es/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/es/.emacs.d/.cache/anaconda-mode/0.1.1/six.py", line 718, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'most_recent\',)"}}')
```

This failure is much less crippling that the one I was getting before (same traceback as @Plancalkuele's).  That one would freeze my spacemacs, making it plain unusable in Python mode.

**Comment by proofit404** [comment]
That one would freeze my spacemacs, making it plain unusable in Python mode.

Does anaconda-mode cause performance issue for you? What package version do you have?

**Comment by Plancalkuele** [comment]
The message in spacemacs:
`eldoc error: (error 127.0.0.1&3anil/80 name or service not known)`
has changed to
`eldoc error: (error Eldoc needs an inferior Python process running)`

**Comment by proofit404** [comment]
Do you enable `anaconda-eldoc-mode`?

**Comment by Plancalkuele** [comment]
Actually I was missing the following line in my configuration:
`(add-hook 'python-mode-hook 'anaconda-mode)`

but had this line put in my configuration some while ago:
`(add-hook 'python-mode-hook 'eldoc-mode)`

Now I edited my config to the following:
```
(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)
```

But I still receive the following message:
`eldoc error: (error Eldoc needs an inferior Python process running)`

**Comment by proofit404** [comment]
What is the value of `eldoc-documentation-function` variable?

**Comment by Plancalkuele** [comment]
```
;;; Eldoc.

(defun anaconda-mode-eldoc-function ()
  "Show eldoc for context at point."
  (anaconda-mode-call "eldoc" anaconda-mode-eldoc-callback))

(defun anaconda-mode-eldoc-callback (result)
  "Display eldoc from server RESULT."
  (eldoc-message (anaconda-mode-eldoc-format result)))

(defun anaconda-mode-eldoc-format (result)
  "Format eldoc string from RESULT."
  (when result
    (let* ((name (cdr (assoc 'name result)))
           (index (or (cdr (assoc 'index result)) 0))
           (params (cdr (assoc 'params result)))
           (doc (anaconda-mode-eldoc-format-definition name index params)))
      (if anaconda-mode-eldoc-as-single-line
          (substring doc 0 (min (frame-width) (length doc)))
        doc))))

(defun anaconda-mode-eldoc-format-definition (name index params)
  "Format function definition from NAME, INDEX and PARAMS."
  (concat
   (propertize name 'face 'font-lock-function-name-face)
   "("
   (anaconda-mode-eldoc-format-params params index)
   ")"))

(defun anaconda-mode-eldoc-format-params (args index)
  "Build colorized ARGS string with current arg pointed to INDEX."
  (->>
   args
   (--map-indexed
    (if (= index it-index)
        (propertize it 'face 'eldoc-highlight-function-argument)
      it))
   (-interpose ", ")
   (apply 'concat)))
```

**Comment by proofit404** [comment]
Actually I have no idea what to try else.

**Comment by Plancalkuele** [comment]
By turning anaconda-mode on and off and restarting spacemacs I suddenly came across the following message:
`File mode specification error: (void-function anaconda-eldoc-mode)`

**Comment by proofit404** [comment]
There is [no](https://github.com/proofit404/anaconda-mode/search?utf8=%E2%9C%93&q=anaconda-mode-eldoc) such declaration as `anaconda-mode-eldoc`

**Comment by Plancalkuele** [comment]
I meant the anaconda-mode-eldoc-function.
[Search for anaconda-eldoc-mode](https://github.com/proofit404/anaconda-mode/search?utf8=%E2%9C%93&q=anaconda-eldoc-mode&type=Code)

 _test/anaconda-mode-test.el
Showing the top two matches. Last indexed 16 days ago._
```
(ert-deftest test-anaconda-eldoc-mode-enable ()
  "Enable `anaconda-eldoc-mode'."
  (with-temp-buffer
    (anaconda-eldoc-mode 1)
    (should (eq eldoc-documentation-function 'anaconda-mode-eldoc-function))
```

But it's alright....I just thought there could have been somewhere a mistake with defining anaconda-mode-eldoc-function as anaconda-eldoc-mode-function. But then also other people would habe serious problems. ^^

But does the message: _File mode specification error: (void-function anaconda-eldoc-mode)_ help you for finding my problem? ;)

**Comment by Plancalkuele** [comment]
Ok. I fixed the problem by commenting the python layer in .spacemacs, restarting spacemacs, uncommenting it again and restarting spacemacs again so that the packages get removed and installed again. No error message when opening a python file in anaconda-mode.

**Comment by proofit404** [comment]
I'm glad you solve it.
