### ISSUE TITLE
anaconda-mode doesn't work in `master` branch of spacemacs

### ISSUE THREAD

**Issue by signalpillar** [proofit404/anaconda-mode#115]
Dear community, 

I installed Spacemacs and enabled python layer. In attempt to go to the definition or check documentation I see the following messages

```
command-execute: Symbol's function definition is void: anaconda-mode-goto
command-execute: Symbol's function definition is void: anaconda-mode-view-doc
```

Then I tried to switch to `develop` branch of Spacemacs and found that `anaconda-mode` works there. 

This could be potentially my problem with environment but if somebody can reproduce it in the `master` of Spacemacs that means we have those things broken.

**Comment by proofit404** [comment]
Looks like related to your problem https://github.com/syl20bnr/spacemacs/pull/2918

**Comment by signalpillar** [comment]
@proofit404 thanks for resolving, will stay with develop then.
