### ISSUE TITLE
Allow customizing the installation directory

### ISSUE THREAD

**Issue by PythonNut** [proofit404/anaconda-mode#116]
It would be really cool if I could tell `anaconda-mode` to install the server somewhere other than my config root directory.

**Comment by proofit404** [comment]
I can make customizable base directory i.e. `~/.emacs.d/anaconda-mode` but python package version will be added any way.

**Comment by PythonNut** [comment]
@proofit404 that's totally fine!

**Comment by proofit404** [comment]
Done.
