### ISSUE TITLE
completion in a library not being displayed

### ISSUE THREAD

**Issue by silgon** [proofit404/anaconda-mode#117]
Hello,
I have a weird problem with a particular library which lies inside a project in `$PYTHONPATH`. First a simple working example with numpy.
```python
import numpy as np
np.
```
This code autocompletes with no problem. Then I try a library inside `$PYTHONPATH` as follows:
```python
import tf
tf.
```
This code is not working. But what it's weird is that I have some other libraries inside `$PYTHONPATH` that autocomplete with no problem. The next is the message sent by `company-anaconda`:
```
Company: Back-end company-anaconda error "JSON-RPC error condition: :data, "AttributeError(\"'NoneType' object has no attribute 'names_dict'\",)", :code, -32000, :message, "Server error"" with args (candidates )
```
I went a little bit further and tried the next code:
```python
# first I set my  $PYTHONPATH in terminal
import jedi
source = '''
import tf
tf.'''
script = jedi.Script(source, 3, len('tf.'), 'example.py')
print script.completions()
# answer of print function
# [<Completion: broadcaster>, <Completion: ConnectivityException>, <Completion: Exception>, <Completion: ExtrapolationException>, <Completion: listener>, <Completion: LookupException>, <Completion: msg>, <Completion: srv>, <Completion: tfwtf>, <Completion: transformations>, <Completion: TransformBroadcaster>, <Completion: Transformer>, <Completion: TransformerROS>, <Completion: TransformListener>, <Completion: _tf>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>]
```
So, I actually have the autocompletion with this little program but not inside `anaconda`. As a side-note, i'm setting `$PYTHONPATH` in emacs with `M-x setenv` ->`PYTHONPATH` -> `mypath`.

I'd appreciate your help. =)

**Comment by proofit404** [comment]
Hello.

Looks like dumping completion list to JSON caused this error. Will try to fix this.

Thanks for report. This is the best bug report I've got for long time :smiley_cat:

**Comment by silgon** [comment]
I'm glad that it makes you happy to know about a bug =P. Let me know if you are able to solve it, so I can update, thanks ;)

**Comment by proofit404** [comment]
Where I can get `tr` library for testing against it?

**Comment by silgon** [comment]
The reference to the libraries are in the following link. 
http://wiki.ros.org/tf
But I doubt there's a direct installation for only libraries. Usually these libraries are installed in `opt/ros/indigo/lib/python2.7/dist-packages` and I have to add the PYTHONPATH environmental variable to emacs

**Comment by proofit404** [comment]
Looks like a `jedi` bug to me. Can you elaborate more on this? Add `$HOME/.emacs.d/anaconda-mode/0.0.1` to you `PYTHONPATH` and try following code in the interactive python console:
```python
import anaconda_mode
source = '''
import tf
tf.'''
script = anaconda_mode.complete(source, 3, 3, 'example.py')
```

**Comment by proofit404** [comment]
Close due to inactivity. Feel free to reopen if you steel have this error and provide complete result.
