### ISSUE TITLE
Unterminated string

### ISSUE THREAD

**Issue by tollerm** [proofit404/anaconda-mode#120]
When editing config.py file which is used for configuring qtile window manager I got multiple identical exceptions that made the editor unresponsive. It seems for me that somewhere (in socket reading?) is limit for number of bytes, the string is truncated and json decoder fails to read.  Here is the output in the anaconda buffer:   
 
127.0.0.1 - - [20/Sep/2015 12:08:58] ================================================================================
Traceback (most recent call last):
  File "/home/anatoli/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 62, in load_args
    args = loads(arg)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 10245 (char 10244)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anatoli/.emacs.d/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/anatoli/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 46, in __call__
    args = self.load_args(arg)
  File "/home/anatoli/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 64, in load_args
    parse_error()
  File "/home/anatoli/.emacs.d/anaconda-mode/0.1.1/service_factory/errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "jsonrpc": "2.0", "id": null}')

**Comment by proofit404** [comment]
To reproduce this I need config.py content and point value.

**Comment by tollerm** [comment]
When I use this default_config.py file from https://github.com/qtile/qtile/blob/develop/libqtile/resources/default_config.py
I get immediately after starting scrolling from the first line "Unterminated string"  exception. I presume that qtile package should be installed as well to reproduce this problem. BTW this problem appeared after updating anaconda. Before updating there were no such problems.

Thank you.

**Comment by proofit404** [comment]
What cursor position (line with column) cause this error. What anaconda-mode command do you call?

**Comment by tollerm** [comment]
When I start to move a cursor from  (0, 0) position with C-n  I get this error. Also I've forgotten to mention that I am using use-package. I am afraid that use-package is responsible for this weird behavior. It looks that anaconda-mode is activated only when I start to move cursor.  And if I move cursor quickly the input buffer is clogged. Clearly, I should look more carefully at my setup.

**Comment by tollerm** [comment]
After some small investigation I found the reason for this weird problem. It turned out that this config file contains a fancy unicode fontified symbol. Clearly jedi has been chocked by bytes from this symbol. Replacing this symbol by normal expression "\U0001f847" solved the problem. Thank you very much for your help and sorry for creating noise with this issue.

**Comment by proofit404** [comment]
Hmm. Not sure if this is jedi bug or emacs json library. I will try it tomorrow.

**Comment by proofit404** [comment]
No progress so far...

**Comment by tollerm** [comment]
Ach, for me the problem is solved because I can leave without these fancy symbols in a code. 
BTW putting a line with 
text="◤ "
immediately chokes Emacs. But once again, IMO it is not worth of your time spending for this obscure bug.

**Comment by proofit404** [comment]
Fixed in the `tramp` branch.
