### ISSUE TITLE
Server connection message in minibuffer

### ISSUE THREAD

**Issue by wizzomafizzo** [proofit404/anaconda-mode#123]
Hi

There is a message that has been showing in the minibuffer when using anaconda-mode and I was wondering if there's a way to suppress it. It only flashes up for less than a second but from what I can make out it says "*http://127.0.0.1:9000*", I assume this is the server it talks to for Python.

It's not the worst thing in the world but it's getting very distracting, it appears every single time I move the cursor, even when it has no information to display.

OS: Mac OS X 10.10.4
Emacs: 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
anaconda-mode: 20150922.537

I'm not sure what version the pip packages are but they're whatever the latest version was as of yesterday.

**Comment by proofit404** [comment]
It is message from `url` package. I don't know how to suppress it. Someday I'll do additional research on this.

**Comment by wizzomafizzo** [comment]
That's annoying, makes sense though. I went all through the url package and I couldn't see how to do it either. I don't mind closing this if you want.

**Comment by avli** [comment]
+1

**Comment by proofit404** [comment]
@avli you can find research `url` package and tell me what part of it have cause this message or better create pull request with fix.

**Comment by avli** [comment]
I hardly can read elisp code, so can't promise anything. But I'll try to glance through ``url`` package code when I got a free minute.

**Comment by proofit404** [comment]
I would appreciate any help on this project.

**Comment by si14** [comment]
I've just updated emacs and now I also see the message. Is it possible to hide it somehow? It makes anaconda mode unusable.

**Comment by proofit404** [comment]
@si14 That isn't my fault. This echo area messages appears from the `url` emacs library. I don't know how to turn it off.  To be honest I doesn't spent any amount of my time to research this problem.  If it possible to hide it somehow I will do this by default inside my package.

**Comment by proofit404** [comment]
Should be fixed by #159.

**Comment by si14** [comment]
@proofit404 thanks a lot! Sorry for sounding too harsh, I didn't mean to. You are doing a fantastic job!

**Comment by proofit404** [comment]
> You are doing a fantastic job!

Thank you for so sweet words. Anaconda mode will be better at least in order of magnitude when I finish `tramp` branch. Search for definitions inside vagrant and docker will improve user experience.
