### ISSUE TITLE
Trim import annotations.

### ISSUE THREAD

**Issue by proofit404** [proofit404/anaconda-mode#125]
![company_import](https://cloud.githubusercontent.com/assets/1862725/10071146/16096346-62c0-11e5-9b33-9d82b678cc3c.png)

**Comment by yejianye** [comment]
Is there a way to turn off all annotations? I feel the popup window would be much cleaner if it doesn't show annotation at all, just show completion candidates.

**Comment by proofit404** [comment]
Looks like there is no way to do this with `company` itself.

**Comment by dsedivec** [comment]
Oops, sorry, I didn't see this issue before I submitted [a pull request to potentially address this issue of long annotations](https://github.com/proofit404/company-anaconda/pull/10) over on company-anaconda.  Thusly linked here, for the benefit of others.

**Comment by proofit404** [comment]
Recent jedi release doesn't have this problem.
