### ISSUE TITLE
`truncate-lines` gets turned off when completion starts

### ISSUE THREAD

**Issue by yejianye** [proofit404/anaconda-mode#126]
I'm using `company-mode` for auto-completion in spacemacs. When completion starts, `truncate-lines` settings for local buffer seems get set to `nil` automatically. And once completion ends, `truncate-lines` will get set to `t` automatically. The whole line will get shifted during completion which is very annoying. 

Here is a screencast of the issue
![truncate lines issue](http://g.recordit.co/yrMMvKkrdg.gif)

**Comment by proofit404** [comment]
Can't reproduce this. `truncate-lines` doesn't change during completion process.
Maybe @dgutov can comment this behavior correctly.

P.S. Upgrade your packages.

**Comment by dgutov** [comment]
> ;; ... fci-mode sets truncate-lines to t in buffers
;; in which it is enabled and restores it to its previous value when
;; disabled.

Do you need any further explanation?

**Comment by proofit404** [comment]
Thanks!! But I can't find `fci-mode`.

**Comment by dgutov** [comment]
https://github.com/company-mode/company-mode/issues/180

The reporter is apparently using the workaround.

**Comment by yejianye** [comment]
Thanks @dgutov for the workaround. Apparently it's related to `fci-mode`
