### ISSUE TITLE
python install failure even after manual install

### ISSUE THREAD

**Issue by sam-s** [proofit404/anaconda-mode#130]
I did 
```
$ pip install anaconda-mode
```
manually and I still get 
```
Downloading/unpacking anaconda-mode==0.1.1
...
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```
in emacs.

PS. ubuntu 15.04, python 2.7

**Comment by proofit404** [comment]
You need to install `anaconda-mode` package exactly into `~/.emacs.d/anaconda-mode/0.1.1` directory.

**Comment by sam-s** [comment]
that's not where 
```
M-x package-install RET anaconda-mode RET
```
installs `anaconda-mode`.
the destination is `.emacs.d/elpa/anaconda-mode-20150922.537`.

**Comment by proofit404** [comment]
I was talking about python package installed with `pip`. Actually `anaconda-mode` consists from two packages Emacs lisp side and Python side. Emacs lisp one install Python part at first run but it fails to do so because of broken distutils config.

**Comment by sam-s** [comment]
I did
```
pip install anaconda-mode
```
this seems to install to `~/.local/lib/python2.7/site-packages/`.
why can't emacs use that?

On Tue, Oct 13, 2015 at 5:40 PM, Malyshev Artem <notifications@github.com>
wrote:

> I was talking about python package installed with pip. Actually
> anaconda-mode consists from two packages Emacs lisp side and Python side.
> Emacs lisp one install Python part at first run but it fails to do so
> because of broken distutils config.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proofit404/anaconda-mode/issues/130#issuecomment-147862129>
> .
>



-- 
Sam Steingold <http://sds.podval.org> <http://www.childpsy.net/>

**Comment by proofit404** [comment]
Anaconda mode *require* python package installed in specified directory. I make this design decision to share this tiny python server across all python version and virtual environments. This is how I avoid reinstalling it again and again. For example I have six python versions and 15 virtual environments on my machine at work.

That's the case.

**Comment by sam-s** [comment]
*solution*: `pip install -U pip` then kill `*anaconda-mode*` buffer.

**Comment by proofit404** [comment]
Do you upgrade system pip that way?

**Comment by sam-s** [comment]
no. this installs a personal pip7 for me; then it is loaded by your python
code in `anaconda-mode.el`

On Wed, Oct 28, 2015 at 4:47 PM, Malyshev Artem <notifications@github.com>
wrote:

> Do you upgrade system pip that way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proofit404/anaconda-mode/issues/130#issuecomment-151985691>
> .
>



-- 
Sam Steingold <http://sds.podval.org> <http://www.childpsy.net/>
