### ISSUE TITLE
`go-back` function puts me in a loop

### ISSUE THREAD

**Issue by proteusvacuum** [proofit404/anaconda-mode#132]
Hey,
I've been using anaconda mode for a few months. When I first started, the `M-*` keybinding would call `anaconda-pop-mark`. This recently changed to `anaconda-go-back` (17bbf0d0bbf8e52e7697fd8ba455e32b67e4804b). Pop mark would go backwards in a list, so if I was following a long chain of definitions with `M-,` or `M-.` I could always get back to the place I had started with multiple `M-*` presses. Now, `M-*` only puts me back one level prior, and pushing it again will toggle between the definition and where it was called. 
Is there a way to have the `pop-mark` functionality again? I found it really useful when navigating through code.

Thanks!

**Comment by proofit404** [comment]
It is a bug, not a feature :smile: I will fix it some day

**Comment by peterhadlaw** [comment]
:+1

**Comment by peterhadlaw** [comment]
Any way to build out a temporary fix I could apply locally? If not, thanks for your wonderful package regardless :)

**Comment by proofit404** [comment]
@peterhadlaw Currently I prepare my talk for Moscow Python Meetup. So I doesn't have time for open source. I doesn't think there is a workaround that will be simpler that final fix.
