### ISSUE TITLE
It don't work at emacs 25.0.50.1

### ISSUE THREAD

**Issue by jiahut** [proofit404/anaconda-mode#133]
when I upgrade to emacs25.0.50.1

emacs --vesion

    GNU Emacs 25.0.50.1
    Copyright (C) 2015 Free Software Foundation, Inc.

It don't work well 

    Debugger entered--Lisp error: (wrong-type-argument commandp anaconda-mode-goto)                                                                               
    2  #<subr call-interactively>(anaconda-mode-goto nil nil)                                                                                                      
    3  ad-Advice-call-interactively(#<subr call-interactively> anaconda-mode-goto nil nil)                                                                         
    4  apply(ad-Advice-call-interactively #<subr call-interactively> (anaconda-mode-goto nil nil))                                                                 
    5  call-interactively(anaconda-mode-goto nil nil)                                                                                                              
    6  command-execute(anaconda-mode-goto)

**Comment by proofit404** [comment]
You call wrong command. Use one of `anaconda-mode-find-*` command group defined by `anaconda-mode-map`.
