### ISSUE TITLE
Low echo-idle-delay clutters echo area

### ISSUE THREAD

**Issue by fjlv** [proofit404/anaconda-mode#141]
I have `(setq eldoc-idle-delay 0.000001)` in my init.el and this causes noise to appear in the echo area with eldoc-mode turned on. If I set `eldoc-idle-delay` to a higher value the problem disappears.

Here is a [video](https://vid.me/FBL3)

**Comment by proofit404** [comment]
When I try to open your gif url I got this message:
```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
    <Code>
        MissingKey
    </Code>
    <Message>
        Missing Key-Pair-Id query parameter or cookie value
    </Message>
</Error>
```

**Comment by fjlv** [comment]
Uploaded it as a video.

**Comment by proofit404** [comment]
Looks like expected behavior with low eldoc delay.  See related #123 issue.
