### ISSUE TITLE
Very slow on large projects

### ISSUE THREAD

**Issue by cpaulik** [proofit404/anaconda-mode#142]
This might be a `jedi` issue but I though I'll first report it here.

I was working on the `pandas` source code and was not able to get any completion candidates. The Python process works on full CPU load but then emacs tells me `Skip anaconda-mode complete response`
One example is insert a new line below:
https://github.com/pydata/pandas/blob/master/pandas/tests/test_frame.py#L2268

and start typing:

```python
self.mix
```

Do you think that there is any way of making it faster on such projects?

**Comment by cpaulik** [comment]
Ok, I've played with jedi directly and it seems the problem is that it takes a long time to parse the 16000 line source code file. I guess that there can be no cache for the file we are currently editing so this problem seems rather hard to solve.

**Comment by proofit404** [comment]
Looks like expected behavior.
