### ISSUE TITLE
Quitting anaconda-mode-show-doc?

### ISSUE THREAD

**Issue by jluttine** [proofit404/anaconda-mode#144]
When I run anaconda-mode-show-doc, the doc opens in a neighbouring window. This is great. But how can I easily quit/close this doc such that the original buffer is recovered in the neighbouring window and focus gets back to the original window? Is there a key binding for this? Couldn't find..

**Comment by proofit404** [comment]
Typing `q` doesn't work for you?

**Comment by jluttine** [comment]
Nope. What is the command that should execute? I could bind some key to it myself. I'm using Spacemacs without any custom configuration if that makes any difference to this.

**Comment by proofit404** [comment]
Looks like `q` [should](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/packages.el#L52-L53) works. I think this is spacemacs related issue.

**Comment by jluttine** [comment]
Ok, thanks! I'll report this issue to Spacemacs.

**Comment by jluttine** [comment]
Running `quit-window` works, so it's only a key binding issue.

**Comment by proofit404** [comment]
Anaconda mode [use](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L631) it already.
