### ISSUE TITLE
 'Lambda' object has no attribute 'get_subscope_by_name'

### ISSUE THREAD

**Issue by eoranged** [proofit404/anaconda-mode#145]
I see a lot of errors like this in anaconda-mode buffer. It's kind of annoying.  
It is [fixed in dev branch of jedi](https://github.com/davidhalter/jedi/issues/628). Maybe It's worth to switch to it?  
I've already replaced anaconda's built-in version of jedi and for now it works just fine.

**Comment by proofit404** [comment]
I don't like to depend on development branch of any library. But customizable installation is possible to implement. We can discus this mechanism behavior from the user point of view. Fill free to create properly named issue for this discussion and describe your suggestions.

Have a good day.
