### ISSUE TITLE
ImportError: No module named cx_Freeze

### ISSUE THREAD

**Issue by nocLyt** [proofit404/anaconda-mode#146]
When I use emacs to open a .py file, I get the following error:

======================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 400, in <module>
    import UserDict
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 83, in <module>
    import _abcoll
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 11, in <module>
    from abc import ABCMeta, abstractmethod
  File "abc.py", line 1, in <module>
    from cx_Freeze import setup, Executable
ImportError: No module named cx_Freeze

![20391ea7-762f-4454-8cb3-3625ff7b1d35](https://cloud.githubusercontent.com/assets/3166027/11587554/46ba5d10-9ab5-11e5-9a97-c9ee00ec605f.jpg)
==================

I use pip to uninstall and install cx_Freeze again and again. The error is still there.

=================

my python version:
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

**Comment by proofit404** [comment]
Looks like something went wrong with your python installation. Check your `abc.py` module content. It doesn't contain `cx_Freeze` import on my machine.
![abc_module_bug](https://cloud.githubusercontent.com/assets/1862725/11588298/564b7d38-9a90-11e5-89f5-92dbf3d3e830.png)

**Comment by nocLyt** [comment]
No. That is what make me confused. 
![image](https://cloud.githubusercontent.com/assets/3166027/11588402/236d8d7c-9abb-11e5-9bc0-d675d887614b.png)

Even, I can  use python run /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py. there is no error. 
![image](https://cloud.githubusercontent.com/assets/3166027/11588435/91985e30-9abb-11e5-8902-f25d227bddfa.png)

**Comment by proofit404** [comment]
Lets try to be stupid :D 
```shell
cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
grep cx_Freeze -R --include='*.py'
```
and
```shell
find / -name abc.py 2>/dev/null
```

**Comment by nocLyt** [comment]
I think the first code you give me lacks something in the end.
I run:
```
cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
grep cx_Freeze -R --include='*.py' .
```
Then, run : 
```
find / -name abc.py 2>/dev/null
```

![image](https://cloud.githubusercontent.com/assets/3166027/11589438/8b796410-9ac3-11e5-96e9-ed66092ad580.png)



But, when I use Emacs open a .py file, the error is still there. T_T

**Comment by proofit404** [comment]
No. First code snippet doesn't need the final dot.  Actually `/Users/yiyi/abc.py` file confuses me. Why is it here?

**Comment by nocLyt** [comment]
Thank for you help!
The problem is `/Users/yiyi/abc.py`. I remove the file. The problem is solved. 
The file is a configuration file about cx_Freeze. I used it one year ago, and I forgot it.
I don't know why the file cause the problem. Maybe because of $PATH?

**Comment by proofit404** [comment]
Python add current directory into `sys.path`. If anaconda-mode server starts from file with `default-directory` at your home then this `abc.py` module get precedence over system one. Glad we solve it.

**Comment by peweet** [comment]
I have this exact issues the last few days. What exactly is causing the error I don't quite follow. (On a Windows Machine btw)

**Comment by proofit404** [comment]
Can you provide full traceback?

**Comment by peweet** [comment]
Hey @proofit404. Thanks for the offer to help!I actually fixed the issue. I had several versions of Python installed on my machine. One of the Paths got mixed up and Cx_Freeze was installed in a version of Python that my system was not using. And more than that but the Paths in my enviroment variable where corrupted. I got another machine that was clean.
And not only that but I installed Python 3.6 64 bit. Cx_Freeze won't work with that version, it won't recognize the install in the wizard. 
So if you have this issue
1. Uninstall delete versions of python on the system that you don't need. (You need to figure this out)
2. Install Python 3.6 32 bit. Very important. Cx_Freeze at the moment wont work with 64 bit.
3. Make sure to read Cx_Freeze docs and how to configure the setup.py file
4. Install Cx_Freeze 5.01 (a new version was the released this month) 
5. built the executable to the command line.  "
6. Put your python files in a folder. Hold shift and right click the folder. 
7. Click on open in command view. 
8. Type in (san's quotation marks) "python setup.py build" 
9. You should see a file with the executable inside it.

**Comment by proofit404** [comment]
Thanks for sharing your solution :+1:

**Comment by peweet** [comment]
Thanks hahaha I just hope no one has to go through the torture I went through yesterday in the office searching for which damn enviroment variable was wrong!!
