### ISSUE TITLE
Using cached version of anaconda-mode

### ISSUE THREAD

**Issue by skrech** [proofit404/anaconda-mode#150]
Hello,

Since there is no discussion board for anaconda-mode I'll ask here.

Today I've tried Spacemacs and installed pyenv. Before installing pyenv, I was getting some strange error about some prefix, and I see that it's common error. Anyway, after pyenv-mode-set anaconda-mode succeeds with installing but I see that it's installed in .emacs.d/.cache/anaconda-mode/VERSION. So my question is:
Will anaconda-mode highlight the appropriate syntax if I initially installed it from python3 but I'm currently working on python2 project?

**Comment by proofit404** [comment]
Hello.
I prefer to use this bug tracker as project discussion platform. This allows to keep all things at one place.
`anaconda-made` actually consist of two packages one written in Emacs Lisp and another written in Python. Python package currently support 2.6 and newer up to 3.4 interpreter versions.
The actual goal of this package is code auto-completion and reference search. Code high lightning is done by `python-mode` it self and works properly both for python 2 and python 3.

**Comment by skrech** [comment]
Thanks for answering,

I meant will anaconda-mode code-complete correctly if I have installed it when using python3 and then switch to python2? And... does pyenv current mode affect the behaviour of anaconda-mode?

**Comment by proofit404** [comment]
Yes. Anaconda mode server support both python 2 and 3. You doesn't need to do anything like reinstall it. The only side effect of using pyenv-mode together with anaconda-mode is automatic search of completion candidates in the side-packages of current virtualenv.
