### ISSUE TITLE
Show object docstrings in eldoc

### ISSUE THREAD

**Issue by PythonNut** [proofit404/anaconda-mode#152]
I'm not sure how difficult this is.

It would be awesome if `anaconda-mode` could show the docstrings of the objects under the point, when `eldoc-mode` is enabled. You could probably replace newlines with spaces and squeeze multiple contiguous whitespace. In most of the cases I've seen, the general use of the function can be derived from the first line or so.

**Comment by proofit404** [comment]
This functionality isn't provided. And never will be during `Jedi.call_signatures` behaviour. I'm hacking a bit and ends up with following solution:

```lisp

(defun docstring-eldoc-function ()
  (anaconda-mode-call "goto_definitions" 'docstring-eldoc-callback))

(defun docstring-eldoc-callback (result)
  (eldoc-message (s-join " " (--map (s-collapse-whitespace (cdr (assoc 'docstring it))) result))))

(defun docstring-eldoc-init ()
  (make-local-variable 'eldoc-documentation-function)
  (setq-local eldoc-documentation-function 'docstring-eldoc-function))

(add-hook 'python-mode-hook 'docstring-eldoc-init)
```
Last line must be evaluated *before* you adding anaconda-mode into python-mode-hook.
Hope this is sophisticated solution for you.
Have a nice day.

**Comment by PythonNut** [comment]
@proofit404 thanks, I have a [slight derivative of your code](https://github.com/PythonNut/emacs-config/commit/72bb6548ef83f9683e660f918e4b173082b513b4#diff-61963b6a9a75ea36b535f4d11a06e062R252) that preserves the original messages if possible as well. I'm very happy with it.

**Comment by proofit404** [comment]
You're welcome.
