### ISSUE TITLE
context based autocompletion issue

### ISSUE THREAD

**Issue by shelper** [proofit404/anaconda-mode#157]
so does the autocompletion work for the following case:
```python
s = 'abc'
s.
```
what i am expecting is the functions for string will pop up, but it doesn't

the autocompletion works only after i run the `s='abc'` in python-shell
am i missing anything to setup the autocompletion?

**Comment by proofit404** [comment]
Hello. If you give me a link to you Emacs setting repository I'll look if you setup `anaconda-mode` properly.

Have a good day.

**Comment by shelper** [comment]
i use emacs-prelude and all my personalized configurations of prelude is here https://github.com/shelper/prelude/blob/master/personal/settings.org

**Comment by shelper** [comment]
i think i solved the problem by adding following lines

```lisp
(eval-after-load "company"
 '(progn
   (add-to-list 'company-backends 'company-anaconda)))
```

**Comment by proofit404** [comment]
This mean you enable company mode backend for anaconda-mode. This is a necessary step to got autocompletion with company-mode. It is described in the `company-anaconda` documentation.
