### ISSUE TITLE
p

### ISSUE THREAD

**Issue by stormpat** [proofit404/anaconda-mode#158]

**Comment by stormpat** [comment]
Sorry!

**Comment by stormpat** [comment]
The dangers of github keyboard shortcuts...

**Comment by proofit404** [comment]
No problem :) Do you have any problems with `anaconda-mode` package?

**Comment by stormpat** [comment]
Actually i had some issues with my python + emacs setup, but i got it working after reading about setting it up with the temp fix for the distutils bug. Thanks for anaconda-mode! +1

**Comment by proofit404** [comment]
Currently I'm working on the `tramp` branch which will also introduce brand new test suite for `anaconda-mode`. This will allows us to emulate this `distutils` bug and hopefully fix it.
