### ISSUE TITLE
Annoying process exist confirmation when quitting Emacs

### ISSUE THREAD

**Issue by Sarcasm** [proofit404/anaconda-mode#160]
Hello,

First thanks for anaconda-mode/company-anaconda, seems to work nice :+1: 

When I use anaconda Emacs prompts me with this message:

    Active processes exist; kill them and exit anyway? (yes or no) 

I think it does not happen 100% of the time but still it happens qui frequently.
Is it expected?

I think using something like `(set-process-query-on-exit-flag process nil)` should resolve the issue.

**Comment by proofit404** [comment]
Hello.

Anaconda-mode already set `query-on-exit-flag` to `nil` on it server process. Here is a [prove](https://github.com/proofit404/anaconda-mode/blob/679936239013aeb15e9209371a5e09303850661f/anaconda-mode.el#L266). However it might be a process of stalled JSONRPC request. Maybe it is possible to set this flag for network process created by `url` library. Will research this topic.  

Thanks for the `irony-mode` by the way. It saves me countless times during C extension development for our python packages.

**Comment by Sarcasm** [comment]
Oh okay, make sense.
