### ISSUE TITLE
anaconda-mode didn't work in spacemacs

### ISSUE THREAD

**Issue by EasonMax007** [proofit404/anaconda-mode#162]
Hi,

I enable python option in spacemacs,but anaconda-mode didn't work.

error message:
completion needs an inferior Python process running

configuration:
    auto-completion
     better-defaults
     emacs-lisp
     markdown
     osx
     org
     python
  (spell-checking :variables
                     spell-checking-enable-auto-dictionary t)
     spell-checking

**Comment by proofit404** [comment]
What actually you are trying to do? Are there any anaconda-mode related buffers (`*anaconda-mode*`, `*anaconda-response*` or `*Anaconda*`)?

**Comment by ntcong** [comment]
I noticed it as well. Have to run "run-python" everytime spacemacs restart.

**Comment by proofit404** [comment]
Update company-anaconda package.
