### ISSUE TITLE
How to use Tramp in anaconda-mode in windows.

### ISSUE THREAD

**Issue by nannanmath** [proofit404/anaconda-mode#163]
Hi, proofit404:
    Thank you for your anaconda-mode. But I have some questions about it.
     I am a new one in emacs for python, my local is a windows and remote host is Linux. An emacs 24.5 is installed in my windows and anaconda2 is installed in remote host. I want to use tramp and anaconda-mode to connect to remote host. Could you give me a detail configuration about how to config my emacs in local and remote host? Thank you very much!
    BTW, I have set that in my init.ed file:
(setq python-shell-interpreter "/plink:username@XXX.XXX.XXX.XXX:/home/username/anaconda2/bin/python"
      python-shell-interpreter-args "-i")
but when I run 'M-x run-python' the output is: shell-quote-argument: Wrong type argument: arrayp, nil

**Comment by proofit404** [comment]
Hello.

Try to do following:

```lisp
(setq python-shell-virtualenv-path "/plink:username@10.120.0.4:/home/username/anaconda2/")
```

This shouldn't affect `run-python` command.

**Comment by nannanmath** [comment]
Hi, I also have a problem when I run `M-x python`, likes:

    Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  6 2015, 18:08:32) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    Anaconda is brought to you by Continuum Analytics.
    Please check out: http://continuum.io/thanks and https://anaconda.org
    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/usr/tmp/py-shell-completion-setup-code.py'
    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/usr/tmp/py-ffap-setup-code.py'
    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/usr/tmp/py-eldoc-setup-code.py'
    >>> 

my config file about python is:

    (provide 'setup-python)
    (require 'python-mode)
    
    (setq python-shell-virtualenv-path "/ssh:username@xxx.xxx.xxx.xxx:/home/username/anaconda2/")
    (add-hook 'python-mode-hook 'anaconda-mode)

and if I run `M-x ipython`, if respones like:

    Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  6 2015, 18:08:32) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 4.0.1 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
     : cannot connect to X server

I don't know how to solve them.

**Comment by proofit404** [comment]
You can use `C-u M-x python` and set python interpreter.
