### ISSUE TITLE
low version of glibc problem

### ISSUE THREAD

**Issue by dzhwinter** [proofit404/anaconda-mode#165]
when I create the vitrual env to use anaconda-mode, which complain me with message, 
"/env/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found"
I found that the glib6 version is too old. But unfortunatly, I didn.t have the right permission because its serve many develop all the day and night. can you figure me out how to fix it?
thank you a lot

**Comment by proofit404** [comment]
Do you create special virtual environment for your project or for anaconda-mode specially? Does any python script successfully running in this environment?

**Comment by dzhwinter** [comment]
I just copy this virtual env from my local machine. I have fix it by recompile python2.7 and anaconda-mode . This problem is produced by environment side, has nothing to do with anaconda-mode.  
Anyway, Thanks a lot .

**Comment by proofit404** [comment]
I'm glad you're solve it.
