### ISSUE TITLE
Can Anaconda send to Ipython subprocess as Elpy?

### ISSUE THREAD

**Issue by MortalCatalyst** [proofit404/anaconda-mode#167]
Hi

I find anaconda a better mode especially for completion and speed. One feature I really like from elpy though is sending to ipython so sending a selection or file to the IPython subprocess as 
[http://elpy.readthedocs.org/en/latest/ide.html#command-elpy-shell-send-region-or-buffer](url)

`C-c C-c (elpy-shell-send-region-or-buffer)`

Searching this [repo for ipython](https://github.com/proofit404/anaconda-mode/search?utf8=%E2%9C%93&q=ipython) I cannot see an answer and hoping if there is an alternate way to acheive this with anaconda that would be great.

**Comment by proofit404** [comment]
Anaconda-mode has nothing to do with inferior python process. You have a few options to solve this issue. 
* You can use elpy for python shell interactions. Do not enable elpy mode, bind elpy-shell-* commands directly to the python-mode-map.
* You can try python-x package.
* You can try ob-ipython package.
* You can try ein package.
* You can use vanilla python shell integration provided by python.el
  * Press C-c C-c to send whole buffer
  * Press C-c C-r to send a region

**Comment by novakboskov** [comment]
You can also simply start python with your preferred interpreter and then Anaconda will work with it.
So, start do:
`(when (executable-find "ipython")
  (setq python-shell-interpreter "ipython")`
Then `run-python` and see if it is what you want.

**Comment by MortalCatalyst** [comment]
Awesome thanks so much.
