### ISSUE TITLE
Not clear how to remap anaconda-mode-map 

### ISSUE THREAD

**Issue by vxe** [proofit404/anaconda-mode#168]
The only way I found to remap this is like this:

(setq anaconda-mode-map nil)

(add-hook 'anaconda-mode-hook
	    (lambda ()
	      (local-set-key (kbd "M-,") #'anaconda-mode-go-back)
	      (local-set-key (kbd "M-*") #'anaconda-mode-find-assignments)))

why is the map created with defvar as this (I think) requires setting anaconda-mode-map to nil?

**Comment by proofit404** [comment]
Use following snippet

```lisp
(eval-after-load 'anaconda-mode
  '(progn
     (define-key anaconda-mode-map (kbd "M-,") 'anaconda-mode-go-back)
     (define-key anaconda-mode-map (kbd "M-*") 'anaconda-mode-find-assignments)))
```
