### ISSUE TITLE
I can't access the libraries that's in pythonpath from company autocomplete

### ISSUE THREAD

**Issue by korayal** [proofit404/anaconda-mode#171]
So, I'm using spacemacs and I've set the parameters as below:
```
  (setq python-shell-interpreter "ipython3")
  (setq python-shell-extra-pythonpaths (list "/home/korayal/other-python-project")) 
```

Then I open a python file and try to import classes using relative paths acording to the path I set above. And the only autocomplete I see is the ones that are installed, not the ones in that pythonpath.

To see if I set the pythonpath correctly, I open a repl using `python-start-or-switch-repl` and `ipython3 -i`
And in the REPL:

```
In[4] :os.environ['PYTHONPATH']
Out[8]: '/home/korayal/other-python-project:'
```

It seems the PYTHONPATH is set correctly. So I don't know what's wrong here.

**Comment by proofit404** [comment]
I can't reproduce this issue. Setting `python-shell-extra-pythonpaths` to the list of absolute directory paths provide expected behavior for me.

**Comment by korayal** [comment]
Do you have any suggestions for me to check out what may the problem on my case? I'm not using any type of virtual environment for python.

any when opening a `.py` file, the I get these two lines on Messages buffer:

```
Making python-shell-interpreter local to  *Python Internal [08219dff5a7c38a72f5bf42175142394]* while let-bound!
Making python-shell-interpreter-args local to  *Python Internal [08219dff5a7c38a72f5bf42175142394]* while let-bound!
```

and the only thing I see in `anaconda-mode` buffer is the line below:

```
anaconda_mode port 9000
```

when I check that process from `ps`, I see this line:

`/usr/bin/python /usr/bin/ipython anaconda_mode.py`
Which would mean it's running with python2.7 would that affect my project if I'm working on python3?

**Comment by proofit404** [comment]
Try to `print(sys.path)` in the `script_method.wrapper` and checkout `*anaconda-mode*` buffer.

**Comment by korayal** [comment]
so I made an update to the file at `~/.emacs.d/anaconda-mode/0.1.1/anaconda_mode.py` but it didn't change anything. It looks like I had to change the file in `~/.emacs.d/.cache/anaconda-mode/0.1.1/anaconda_mode.py`

After opening it with `emacsclient` I got:
```
['/home/korayal/.emacs.d/.cache/anaconda-mode/0.1.1', '', '/usr/bin', '/home/korayal/other-python-project', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/korayal/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/IPython/extensions', '/home/korayal/.ipython']
```
as a result.

But if I open the same `.py` file (that would trigger the `python-mode`) directly with emacs24 (which also have a `pyenv` for Python 3.4.4 ) I get:

```
['/home/korayal/.emacs.d/.cache/anaconda-mode/0.1.1', '/home/korayal/other-python-project', '/home/korayal/.pyenv/versions/3.4.4/lib/python34.zip', '/home/korayal/.pyenv/versions/3.4.4/lib/python3.4', '/home/korayal/.pyenv/versions/3.4.4/lib/python3.4/plat-linux', '/home/korayal/.pyenv/versions/3.4.4/lib/python3.4/lib-dynload', '/home/korayal/.pyenv/versions/3.4.4/lib/python3.4/site-packages']
```

In both configuration, I can't seem to access py files in `other-python-project` via company-anaconda

**Comment by korayal** [comment]
OK, this is my fault. I figured that I had to add `__init__.py` files to directories that I need to import. (which was not a requirement for IDEs like PyCharm etc.)

**Comment by proofit404** [comment]
`jedi` library doesn't support namespace packages yet, so you need to use `__init__.py` files to turn your modules into classic package.
