### ISSUE TITLE
Keep getting "Skip anaconda-mode complete response"

### ISSUE THREAD

**Issue by introom** [proofit404/anaconda-mode#175]
When editting a python file, I kept getting the "skip anaconda-mode blabla stuff".

Found the relevant code here: https://github.com/proofit404/anaconda-mode/blob/6a8c20683dc818cf0e9faba3f511131e37708c3e/anaconda-mode.el#L369

But dunno what's supposed to modify.

the _anaconda mode_ buffer content is:

anaconda_mode port 9000

**Comment by proofit404** [comment]
Do you have this problem with company-anaconda?

**Comment by introom** [comment]
I am using anaconda with company-anaconda.

So, yes.

**Comment by proofit404** [comment]
I think we need to keep this messages for commands triggered by user like `M-.` or company-complete called with hot key and skip it for regular `company-complete` and `eldoc`.

I will try to fix it on Sunday.

**Comment by xarthurx** [comment]
Hi, did you fix this?
@proofit404

**Comment by xarthurx** [comment]
I came from this bug:
# status: (:error (error connection-failed failed with code 22
 :host 127.0.0.1 :service 62580))
# point: 1

sometime the code and service number is different.

and did the "no_proxy" trick, then it shows the message reported in this page.

**Comment by dwcoates** [comment]
this seems to be a problem with large data that has many features. If I read in a 150,000 line json document, the pure json object has no issues with completion. When I read this json object into a Pandas DataFrame, suddenly it stutters, throws this error mostly, sometimes says "no completion available", and sometimes completes properly (after a considerable delay).
