### ISSUE TITLE
wrong python version picked (doesn't work with pyenv)

### ISSUE THREAD

**Issue by introom** [proofit404/anaconda-mode#176]
Hi,

In my project directory, I have a `.python-version' file with version 3.4.4

I opened terminal emacs inside that directory to edit a python file.

Turns out anaconda completes with python 2.7.

Some more details:

The command `run-python' gives a python 3.4.4 shell.

The `python-shell-interepter' variable is 'python'.

The `default-directory' for *Anaconda* is my project directory.

Since pyenv alters the PATH env variable and adds shim python executable. I think it's reasonable for anaconda to pick up the pyenv provided python.

**Comment by proofit404** [comment]
It doesn't work this way. You need to setup `python-shell-interpreter` or `python-shell-virtualenv-path` variables according to `python.el` documentation. Or use my package `pyenv-mode` for that.

**Comment by introom** [comment]
I took a loot at your pyenv-mode, 
So the line: https://github.com/proofit404/pyenv-mode/blob/master/pyenv-mode.el#L68 basically calls pythonic-activate which in turn revolves around the python-shell-virtualenv-path.

I don't think this issue relates to the virtualenv problem.

It's about anaconda cannot find the right python executable binary. No *virtualenv* stuff plays here.

The python.el works ok, for example the `run-python'.  It picks python3.4 because indeed the `python' executable as in "/usr/local/var/pyenv/shims/python" `exec's a python3.4 process image.

On the other hand, anaconda doesn't work (completion and jumping). It stuborrnly chooses the python2.7. I don't know why it chooses the python2.7. If it searches a python image w.r.t the `python-shell-interpreter' whose values is "python", then it ought to find the `../pyenv/shims/python' executable, and finally the python3.4.

**Comment by proofit404** [comment]
`anaconda-mode` doesn't look for `default-directory` when search for python. Set `python-shell-interpreter` to `/home/introom/.pyenv/3.4.4/bin/python`. This is how it works.
