### ISSUE TITLE
find-definition doesn't find obvious place

### ISSUE THREAD

**Issue by introom** [proofit404/anaconda-mode#177]
for example
from types import SimpleNamespace

put the cursor on SimpleNamespace and do a find-definition, the result is no-definition

**Comment by proofit404** [comment]
This case is actually the tricky one. First of all try to do assignment search. It will open `types` module at right place. `SimpleNamespace = type(sys.implementation)`. If you try to open the definition or assignment of `sys` module it will fail. Since go to definitions tries to search for the deepest definition it fails on `sys` module too.

**Comment by introom** [comment]
Thanks for your quick help.

Looks like the definition under anaconda is a transitive search.

aka
a = b = c = somedef
so def(a) == def(b) == def(c) == somedef

Looks like I should write a wrap of (find-defintion, if fail, then find assignment)

**Comment by proofit404** [comment]
This should be something like this:

```lisp
(defun my-goto ()
  (interactive)
  (anaconda-mode-call "goto_definitions"
    (lambda (result)
      (if result
          (anaconda-mode-definitions-view result)
        (anaconda-mode-call "goto_assignments" anaconda-mode-find-assignments-callback)))))
```

**Comment by introom** [comment]
Well, still I'd consider the always folloiwng `=' to find the deepest class/object is a bug.

For example, 
in a.py:
import enum
Event = enum.IntEnum("Event", "time owner callback")

in b.py
import a
event = a.Event("foo", "bar", "baz")

When I put the cursor on a.Event in b.py, then find the definition, it will go to the enum.py shipped with Python.

But indeed, people will only care about how a.Event is defined, and jumping to the right line inside a.py is the only choice.

**Comment by proofit404** [comment]
This is assignment search. Use `M-,` to go to the `Event = enum...` in the `a` module.
