### ISSUE TITLE
Spacemacs anaconda_mode issue

### ISSUE THREAD

**Issue by Nolski** [proofit404/anaconda-mode#178]
Hi,

I recently enabled the python layer in spacemacs and I am encountering issues with anaconda mode. If you expect this is more of an issue with spacemacs let me know and I can close this and refile on their repository. After installing the layer, whenever opening a python file, a new window opens with the following message.
 
```
Collecting anaconda-mode==0.1.1
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: jedi, six, service-factory, anaconda-mode
[31mException:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both[0m
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
```

Here is the location of `python`
```
$ which python
/usr/local/bin/python
```

Here is my python version.
```
$ python --version
Python 2.7.11
```

The shell I'm launching emacs from is fish shell.

I saw this issue referenced in #106 but I couldn't find any definitive solution or workaround to this problem.

**Comment by proofit404** [comment]
Hello. This is definitely `anaconda-mode` problem. What is the return value for `M-x eval-expression RET (pythonic-executable) RET`? Do you use system wide python or you install it with homebrew?

**Comment by Nolski** [comment]
This is a bit embarrassing but the output seems to kill evil mode and I can't get a copy of the text. However I took a screenshot of it here:
<img width="700" alt="screen shot 2016-05-04 at 4 07 31 pm" src="https://cloud.githubusercontent.com/assets/2600677/15027560/6cdcda16-1212-11e6-9ed1-5f44dfa9e9b3.png">

**Comment by proofit404** [comment]
```lisp
(progn
  (require 'pythonic)
  (pythonic-executable))
```

**Comment by Nolski** [comment]
That outputs `"python"`.

**Comment by proc** [comment]
Encountering this issue as well

**Comment by proofit404** [comment]
![d29f0b942bfce41bde5d8becc52543c7](https://cloud.githubusercontent.com/assets/1862725/15242434/3301f104-1907-11e6-96e4-556adaf4b77d.gif)

**Comment by proofit404** [comment]
Same issue discussed in #181
