### ISSUE TITLE
vagrant - connection-failed failed with code 22

### ISSUE THREAD

**Issue by bedwards** [proofit404/anaconda-mode#179]
Using vagrant getting

```
# status: (:error (error connection-failed failed with code 22
 :host localhost :service 9000))
# point: 
```

vagrant port shows 9000 (guest) => 9000 (host)

on the host

```
sudo lsof -i -P | grep 9000
VBoxHeadl 63046       bedwards   23u  IPv4 0x6ee07b28c3b8d475      0t0  TCP *:9000 (LISTEN)
```

on the guest

```
$ sudo lsof -i -P | grep 9000
python    22460    bbuser    3u  IPv4  79517      0t0  TCP *:9000 (LISTEN)

$ ps -ef | grep 22460
bbuser   22460 22121  0 04:59 pts/3    00:00:00 /home/bbuser/.virtualenvs/bb/bin/python anaconda_mode.py 0.0.0.0
```

**Comment by proofit404** [comment]
Hello.

Lets try to debug this issue. 

* Disable port forwarding in the vagrant configuration
* Boot vm
* Open python file over tramp
* Activate remote virtual environment
* Call some anaconda-mode interactive command
* See connection failure
* Close this window
* From the host OS run `ssh -nNT vagrant@localhost -p 2222 -L 9000:localhost:9000`
* Call anaconda-mode interactive command
* See what happens :)
