### ISSUE TITLE
In the org-mode, how to load a  piece of python code before Eldoc?

### ISSUE THREAD

**Issue by cnglen** [proofit404/anaconda-mode#180]
I use org-mode to write documents while evaluating some python code.

In the org file, 

#+BEGIN_SRC ipython :session :exports both
  %matplotlib inline
  import pandas as pd
  import numpy as np
  import matplotlib as mpl
  import matplotlib.pyplot as plt
#+END_SRC

#+BEGIN_SRC ipython :session :exports both
  import pandas as pd
  pd.DataFrame   <-  **M-? works**
#+END_SRC

#+BEGIN_SRC ipython :session :exports both
  pd.DataFrame    <-  **M-? Not working**
#+END_SRC

C-c i, to open a python buffer.  In the last block, anaconda-mode doesn't find 'pd'.

Is there any to init with "import pandas as pd" then run Eldoc?

**Comment by proofit404** [comment]
Hello.

Anaconda-mode process whole buffer to search completion candidates and eldoc. In the second example there is no reference for `pd` so anaconda-mode can't find `DataFrame` documentation. You can hack it in some way to concat all related src sections before send. [Here](https://github.com/proofit404/anaconda-mode/blob/0261b3828543a9f6175fb55914a5504f2c639044/anaconda-mode.el#L336) you can see how it works. Advice `anaconda-mode-jsonrpc-request-data` function to change source field in the desired way.

Have a good day.

**Comment by cnglen** [comment]
done, thanks.
`               ;; (source . ,(buffer-substring-no-properties (point-min) (point-max)))
               ;; (line . ,(line-number-at-pos (point)))
               (source . ,(concat "import pandas as pd;import numpy as np;import matplotlib as mpl;import matplotlib.pyplot as plt;import seaborn as sns;from scipy import stats\n"
                                  (buffer-substring-no-properties (point-min) (point-max))))
               (line . ,(+ 1 (line-number-at-pos (point))))`

**Comment by proofit404** [comment]
You're welcome :)
