### ISSUE TITLE
*anaconda-response* buffer frequently pops up showing "status: nil" when company-idle-delay=0

### ISSUE THREAD

**Issue by liweitianux** [proofit404/anaconda-mode#183]
Hello,

When I'm editing a Python file, after several completions (quite random), the `*anaconda-response*` buffer pops up and steals the cursor but only shows following two lines:

```
# status: nil
# point: 1
```

This happens quite frequently and is very annoying, usually after only several completions/words.  I could just close the `*anaconda-response*` buffer and continue my editing, but it would happen quickly.

I checked the `*Message*` buffer, and noticed that there was always an message related to the `*anaconda-mode*` popup:

```
Can not read anaconda-mode server response
```

I also checked the `*anaconda-mode*` buffer, but there was nothing.

When this issue happens, I immediately evaluate `(anaconda-mode-running-p)` and the result was `(run open listen connect stop)`.  In addition, there were many repeated messages `Skip anaconda-mode complete response`.

Other information about my environment:
- `python-shell-interpreter`: `python`
- `python-shell-virtualenv-path`: `nil`
- no `pyenv`
- I'm using the `spacemacs` bundle

I have no idea why this happens, and don't how to further investigate into it (I'm still rather new to Emacs).

Cheers,
Aly

**Comment by proofit404** [comment]
This means emacs was unable to perform api call on its server. If I recall correctly this may be caused by http proxy settings in your system.

**Comment by liweitianux** [comment]
Hi @proofit404 , I think I found the reason, and this issue does **not** relate to the proxy settings.

I have the setting ``(setq company-idle-delay 0)`` for my Emacs (w/ ``spacemacs``), which make completion start just when I type.  And I'm currently sure this is the reason causes the frequent emergence of ``*anaconda-mode*`` buffer window.  After I changed this ``company-idle-delay`` to a value **greater than zero** (say 0.1), this issue never happened again.

On the other hand, I also tried with the environment variable ``no_proxy="localhost,127.0.0.1"``, but it didn't help with this problem.

I have no idea about the internal details why this issue happens with ``company-idle-delay`` set to 0.  Maybe there is a bug in the ``company-anaconda``?

Cheers,
Aly

**Comment by proofit404** [comment]
Maybe it try to start anaconda-mode server to frequently. I can't guarantee that I correctly handle restart of server in the early state.

**Comment by nverno** [comment]
Another option is removing the hook that shows the failed response buffer in your python setup,

```
(remove-hook 'anaconda-mode-response-read-fail-hook
             'anaconda-mode-show-unreadable-response)

```

**Comment by proofit404** [comment]
In this case better option is turn off anaconda-mode at all since it doesn't work. Silent failure is still failure.

**Comment by nverno** [comment]
It works fine, the company backend and everything else works great, just temporary issues with the server, which would be fine to report in another buffer, except the response buffer steals the cursor

**Comment by proofit404** [comment]
@nverno Does this issue happens with turned off company-mode?

**Comment by nverno** [comment]
@proofit404 no, not as far as I can tell.

**Comment by proofit404** [comment]
What is the `company-idle-delay` value?

**Comment by nverno** [comment]
I use 0.5 for `company-idle-delay`

**Comment by proofit404** [comment]
Does this error happens when you call goto definition/assignment command? Or it is auto complete related only?

**Comment by nverno** [comment]
I have only encountered it with auto-complete when using the company-backend.  Jumping to definitions works well.  I haven't looked into very much since the above fix works fine for me, but it appears that a new connection is established after on of those errors if that makes sense?  Does it fail and restart a new process?

**Comment by wqhhust** [comment]
I added the following to dotspacemacs/user-config, but still have the problem. I am using 0.105.21 spacemacs. What should I do?
```
  (setq company-idle-delay 0.5)
  (remove-hook 'anaconda-mode-response-read-fail-hook
               'anaconda-mode-show-unreadable-response)
```

**Comment by proofit404** [comment]
Try to add `(require 'anaconda-mode)` *before* `remove-hook` statement in your config.

**Comment by mbertheau** [comment]
FWIW, I believe the spacemacs equivalent would be the following in `user-config`:

```elisp
(with-eval-after-load 'anaconda-mode
    (remove-hook 'anaconda-mode-response-read-fail-hook
                 'anaconda-mode-show-unreadable-response)))
```

Spacemacs loads correctly with this but the error happens too sporadically for me to verify that this solves the nuisance problem.

**Comment by ruefo** [comment]
@mbertheau Please remove last `)`, just in case someone wants to copy-paste ;)

**Comment by doctorvik** [comment]
I am also getting this in spacemacs. My config just has python layer and autocomplete layers active. I can reproduce the error with the following code.

    i="hello
    i.

then where the autocomplete would normally popup, if I cancel it, then go back to the `i.` and do `M-<Tab>` it fails to autocomplete and autocompletion breaks and after a few minutes my minibuffer reports the status:
`# status: (:error (error connection-failed failed with code 22
 :host 127.0.0.1 :service 51516))
# point: 1`

**Comment by NathanLovato** [comment]
Following on @mbertheau, the fix works, but it only worked after updating the package to the latest version. In spacemacs, in user-config:
```lisp
(defun dotspacemacs/user-config ()
...
  (remove-hook 'anaconda-mode-response-read-fail-hook
               'anaconda-mode-show-unreadable-response)
...
)
```

It still opens quite a few processes/fires quite a few connections but with this it works really well!
Big thanks to you @proofit404, and all the contributors :)

**Comment by proofit404** [comment]
Errors do not propagate to windows anymore.
