### ISSUE TITLE
anaconda-mode stuck compiling

### ISSUE THREAD

**Issue by jreeseue** [proofit404/anaconda-mode#184]
Using GNU Emacs 24.5.1 on a MacBook Pro with El Capitan 10.11.5 and trying to install anaconda-mode. After running `M-x package-install RET anaconda-mode RET` I am faces with the following error: `Compiling /*/*/.emacs.d/elpa/anaconda-mode-0.1.2/anaconda-mode.el...` and this seems to hang indefinitely.

**Comment by proofit404** [comment]
Do you have same issue calling `byte-compile-file` on `anaconda-mode.el`?

**Comment by jreeseue** [comment]
Yes. If I cancel the compilation when trying to install via `M-x package-install RET anaconda-mode RET` and try `byte-compile-file` on `anaconda-mode.el` this also hangs when trying to compile.

josh

**Comment by proofit404** [comment]
Does `*anaconda-mode*` buffer present? If it does please paste it content.

**Comment by jreeseue** [comment]
There is no `*anaconda-mode*` in the buffer:

```
CRM Buffer                 Size Mode             File                           
.   *scratch*                 0 Lisp Interaction
 %* *Messages*      109 Messages
    dataflow.py        1752 Python               ~/...
```

**Comment by jreeseue** [comment]
Note: using the same installation on an Ubuntu 14.04.4 LTS machine works fine. Same installation meaning I share `.emacs.d/ ` directories via a git repo between machines.

**Comment by proofit404** [comment]
Try to disable `eldoc-mode`.

**Comment by jreeseue** [comment]
Well, I am not terribly sure what happened but it does appear to be working now on all three machines that I am running.

josh

**Comment by proofit404** [comment]
I have no idea too. Feel free to reopen this issue.
