### ISSUE TITLE
jedi staticmethod first param complate error

### ISSUE THREAD

**Issue by JinMaiAymazon** [proofit404/anaconda-mode#185]
I'm sorry, my English is poor.

def A:
----@staticmethod
----def a(param):
--------""":type param: str"""
--------param. # this pop a(param == cls) and not str.xxx
--------assert isinstance(param, str)
--------param. # this pop str.xxx

Another problem is how to use the single-line comments for type completion?
x = y['xxx'] # :type: str
is not complate, i test is not work, and:
x = y['xxx'] # type: str | # @type: str
: (

**Comment by proofit404** [comment]
Looks like `jedi` can't process docstring type hints for static methods. I don't know if it should process type hints at the end of the string. You can ask this questions in its bugtracker. `anaconda-mode` is a simple wrapper for it without any logic related to code analysis.

**Comment by JinMaiAymazon** [comment]
:), thank you.
