### ISSUE TITLE
error in process sentinel: url-http-create-request: Multibyte text in HTTP request

### ISSUE THREAD

**Issue by stakemori** [proofit404/anaconda-mode#189]
I use Emacs 25.0 (658daf93e295dd00048d15001335f58f91e679f6) built from the source. Recently, I got an error from url-http-create-request when I visited a source file which contains a unicode character. Here is a part of the error message:

```
    error in process sentinel: url-http-create-request: Multibyte text in HTTP request: POST / HTTP/1.1
    MIME-Version: 1.0
    Connection: keep-alive
    Extension: Security/Digest Security/SSL
    Host: 127.0.0.1:9000
    Accept-encoding: gzip
    Accept: */*
    User-Agent: URL/Emacs
    Content-length: 19854

    {"jsonrpc":"2.0","id":1,"method":"eldoc","params":{"source":"# -*- coding: utf-8 -*-\nimport
```

I guess the commit a98aa02a5dbf079f7b4f3be5487a2f2b741d103d in the Emacs source repository causes this.

**Comment by demon386** [comment]
+1. I got this when I visit a file with GBK encoded characters.

**Comment by proofit404** [comment]
Does this issue relates to other packages uses url library?

**Comment by stakemori** [comment]
@proofit404, yes, I guess packages which use `json.el` and `url-http.el` have the same bug.
Actually, I got the same error when I edited a js file which contains a multibyte character with `tern-mode` on. So I guess this is a bug of `url-http.el`.

I guess the promblem is that the function `string-bytes` is not "additive",
that is, `(+ (string-bytes string1) (string-bytes string2))` may not be equal to `(string-bytes (concat string1 string2))` for multibyte strings.

In `url-http-create-request`, it seems that they assume the additivity. I mean `(= (string-bytes request) (length request))` may be `nil`, even if `(= (string-bytes url-http-data) (length url-http-data))` is `t`.

**Comment by demonlife** [comment]
+1。 I also meet this problem. python version is 2.7.12 emacs version is 25.1.1, and file-coding is utf-8

**Comment by proofit404** [comment]
@stakemori Maybe its better to file this bug to the emacs mailing list? Anaconda-mode isn't proper place to fix this.

**Comment by stakemori** [comment]
@proofit404, I have reported this bug to bug-gnu-emacs@gnu.org. But please keep this issue open until they confirm the bug.

**Comment by proofit404** [comment]
No problem, thanks!

**Comment by dgutov** [comment]
> (+ (string-bytes string1) (string-bytes string2)) may not be equal to (string-bytes (concat string1 string2)) for multibyte strings

So? The code is checking that the string is unibyte.

**Comment by stakemori** [comment]
Which string should be checked? `url-http-data` or `request`? If it's `request`,  how do we avoid this issue?

**Comment by dgutov** [comment]
> If it's request, how do we avoid this issue?

You convert to unibyte all values that you bind the `url-` variables to.

**Comment by stakemori** [comment]
Thanks. But it seems that `anaconda-mode` bind only two global variables that start with `url-`. `url-request-method` and `url-request-data`. `url-request-method` is bound to an ASCII string and `url-request-data` is bound to a return value of `encode-coding-string`, which is already unibyte string. Sorry if I misunderstand something.

**Comment by dgutov** [comment]
OK, I see the problem, thanks.

**Comment by dgutov** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24117#17

**Comment by stakemori** [comment]
@dgutov, thanks for analyzing. It seems that the bug is confirmed. So I close this issue.
