### ISSUE TITLE
Ignores no_proxy

### ISSUE THREAD

**Issue by quicknir** [proofit404/anaconda-mode#190]
I've found that anaconda-mode typically ignores the no_proxy variable, at least the way I have it set. With this in my .emacs file, anaconda-mode did not work for me:

```
  (setenv "no_proxy" "127.0.0.1,localhost")
  (setenv "NO_PROXY" "127.0.0.1,localhost")
```

If I add this, then I don't have problems: 

```
  (setenv "http_proxy" "")
  (setenv "https_proxy" "")
```

Though of course, now I can't update packages etc. Is there something particular to what anaconda mode is doing that might cause it to ignore no_proxy? Did I do something wrong? The anaconda-mode buffer only says that it is running on port 9000 and nothing else, the anaconda server response buffer clearly shows that it is getting redirected to the proxy (and failing) even with no_proxy set.

If it matters at all, I'm using anaconda-mode via spacemacs.

**Comment by proofit404** [comment]
Does this setenv think happens before url library loaded? What is the value of url-proxy-services variable?

**Comment by quicknir** [comment]
It was happening after (most likely, with lazy loading sometimes its hard to tell). I moved it to another section of spacemacs where it is run before anaconda-mode and things seem to be working. Thanks! If I have further issues I'll reopen.

**Comment by proofit404** [comment]
You're welcome.

**Comment by quicknir** [comment]
@proofit404 I'm again having issues. I look at the value of url-proxy-services, and indeed it is not set correctly (it doesn't mention the no_proxy settings, which it did before). Do you have any other advice or insight on whether it should run before, or after? I'm not sure when and how url-proxy-services populates itself.

**Comment by proofit404** [comment]
Maybe easiest thing to do is to setup url-proxy-services manually according to its documentation. This aproach avoids dependency on module load order which is nice thing to do.

**Comment by proofit404** [comment]
Do you solve it?

**Comment by quicknir** [comment]
Well, it's working again now, I suspect it won't last. I should try setq'ing my url proxy services, the last time I did it though it didn't work and I'm not sure why, maybe I needed to escape something. Thanks for your help.
