### ISSUE TITLE
Change linter from flake8 to PyLint or others

### ISSUE THREAD

**Issue by liuxianming** [proofit404/anaconda-mode#191]
Hi, 

I'm a big fun of anaconda-mode, and have been using it in the past year. However, due to the change of server environment, I can not use flake8 as linter anymore (non-zero error code), and I'm considering to change it to PyLint. Can I do it in anaconda-mode? Any help would be appreciated.

Thanks

**Comment by proofit404** [comment]
Anaconda-mode is an autocomple engine. It does not support linters at this point.  Any way I want to help you to resolve your issue. Can you describe infrastructure change? What is the expected behavior of Emacs in this situation? In other words how you would like to use it?

**Comment by liuxianming** [comment]
@proofit404 Sorry for late reply. The problem is because the flake8 in the system does not have options '--format', which makes linter failed. I just installed anaconda in home folder and install py-flake8, which does not affect the system linter but also can use the "local" flake8. Thanks for your reply.

**Comment by proofit404** [comment]
If you use flycheck or flymake plugins then it is possible to make to use theme local flake8.
