### ISSUE TITLE
C-M-i not working out of box?

### ISSUE THREAD

**Issue by shwsun** [proofit404/anaconda-mode#192]
Hi, I have been struggled with this issue for a while. Weird thing is that I can't use ``C-M-i`` to complete out of box. ``*Messeges*`` buffer will complain ``python-completion-complete-at-point completion needs an inferior python process``. However, if I try to use ``M-x anaconda-mode-complete``, the code completion works fine. 

``$ uname -r`` 
``4.6.4-1-ARCH``

I believe this pops out just recently cause I try to reinstall Emacs. I tested it on Spacemacs and a personal fork of emacs config settting. Thx a lot.

**Comment by proofit404** [comment]
Do you enable anaconda-mode in this python buffer?

**Comment by shwsun** [comment]
I do. That's why ``M-x anaconda-mode-complete`` works, right?

Below is my python config
```
(require-package 'pip-requirements)
(require-package 'anaconda-mode)
(require-package 'company-anaconda)
(require-package 'flymake-python-pyflakes)
(require-package 'py-autopep8)
(require-package 'py-yapf)

;;; Code:
(setq auto-mode-alist
      (append '(("SConstruct\\'" . python-mode)
                ("SConscript\\'" . python-mode))
              auto-mode-alist))

;; flycheck
(require 'flymake-python-pyflakes)
(add-hook 'python-mode-hook 'flymake-python-pyflakes-load)
(setq flymake-python-pyflakes-executable "flake8")

(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)
(eval-after-load "company"
 '(add-to-list 'company-backends 'company-anaconda))
(add-to-list 'completion-at-point-functions 'anaconda-mode-complete)

;; autopep8
(require 'py-autopep8)
(add-hook 'python-mode-hook 'py-autopep8-enable-on-save)
(setq py-autopep8-options '("--max-line-length=80"))

;; yapf
(require 'py-yapf)
(add-hook 'python-mode-hook 'py-yapf-enable-on-save)

(setq python-shell-completion-native-enable nil)
(provide 'init-python-mode)
;;; init-python-mode ends here```

**Comment by proofit404** [comment]
anaconda-mode-complete work regardless of turning on anaconda-mode. What C-h k C-M-i says?

**Comment by shwsun** [comment]
Says "python-completion-complete-at-point: Completion needs an inferior python process".

**Comment by proofit404** [comment]
It should show `*Help*` buffer describing C-M-i binding.

**Comment by shwsun** [comment]
It is very weird that when I try to only use anaconda-mode. e.g only have anaconda-mode configed in ``.emacs``. I can't see the `*Help*` buffer.

I am using Arch Linux. Do you thing it is somehow related? Should I try to get the Emacs from GNU and compile it my self?

**Comment by proofit404** [comment]
Try `M-x describe-function RET anaconda-mode-complete` from python-mode buffer with anaconda-mode enabled in it.

You should see this

```
anaconda-mode-complete is an interactive compiled Lisp function in ‘anaconda-mode.el’.

It is bound to C-M-i.

(anaconda-mode-complete)

Request completion candidates.
```

**Comment by shwsun** [comment]
Yes, it is what the buffer pops up says.

**Comment by proofit404** [comment]
And C-M-i doesn't trigger completion in **this** python buffer?

**Comment by shwsun** [comment]
No.

**Comment by proofit404** [comment]
C-h m and see if another minor mode hide C-M-i binding.

**Comment by shwsun** [comment]
There is a ``complete-at-point``, but it says shadowed in current buffer.

**Comment by proofit404** [comment]
Look for command which binding not shadowed.

**Comment by shwsun** [comment]
Then it is just anaconda-mode-complete

**Comment by proofit404** [comment]
Then C-M-i must trigger this command.

**Comment by shwsun** [comment]
Thx, I just try my configuration on Mac. It works fine, so it has to be sth wrong with my arch linux

**Comment by proofit404** [comment]
Ok.
