### ISSUE TITLE
With python 3.5 + asyncio

### ISSUE THREAD

**Issue by dpineiden** [proofit404/anaconda-mode#195]
Hello.
I'm working recently with emacs and anaconda mode. My project uses python 3.5 and asyncio and anaconda give this error:

`Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 78, in <module>
    import os
  File "/usr/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "/usr/lib/python3.5/_collections_abc.py", line 56
    async def _coro(): pass
            ^
SyntaxError: invalid syntax
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 78, in <module>
    import os
  File "/usr/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "/usr/lib/python3.5/_collections_abc.py", line 56
    async def _coro(): pass
            ^
SyntaxError: invalid syntax
anaconda_mode port 9000`

**Comment by proofit404** [comment]
This is expected error since `jedi` doesn't support python 3.5 syntax yet.

**Comment by loggerhead** [comment]
@proofit404 Can you reopen this issue? So people who care about the support of python 3.5 can subscribe this issue and track it easily.

**Comment by proofit404** [comment]
Hi @loggerhead 

First of all we should check `master` and `dev` branches of `jedi` library. If this issue will persist and there is no milestone yet for python 3.5 support, then it is necessary to start discussion in the `jedi` issue tracker.

Unfortunately I'm short on time and can't do all necessary preparations for this kind of report. If you can please do and feel free to link this issue to the created one.

Regards, Artem.
