### ISSUE TITLE
A warning in emacs25

### ISSUE THREAD

**Issue by lipanXJ** [proofit404/anaconda-mode#196]
I am using emacs25-rc2 now,and here is the warning,are they need to be fixed?

```
Warning (bytecomp): reference to free variable ‘anaconda-mode-definition-commands’
`Warning (bytecomp): ‘font-lock-fontify-buffer’ is for interactive use only; use ‘font-lock-ensure’ or ‘font-lock-flush’ instead`
```

**Comment by proofit404** [comment]
Sorry, looks like I miss this issue. Does your problem was solved somehow?

**Comment by lipanXJ** [comment]
Surely,it's a issue that can be ignored.(just a compilation warning after install)
