### ISSUE TITLE
Keep getting error messages

### ISSUE THREAD

**Issue by asdyjd** [proofit404/anaconda-mode#197]
I keep getting these messages:
make client process failed: connection refused, :name, 127.0.0.1, :buffer, #<killed buffer>, :host, 127.0.0.1, :service, 9000, :nowait, nil
Skip anaconda-mode complete response
Skip anaconda-mode eldoc response

I'm using win10, spacemacs and python2.7.
What shoud I do?

**Comment by asdyjd** [comment]
*anaconda-mode* buffer's content:
anaconda_mode port 9000

**Comment by proofit404** [comment]
Hi. Sorry for late response. This issue somehow depends on network interaction problems. Do you have any successful anaconda-mode results or all commands ends up with error?

**Comment by asdyjd** [comment]
I can get some successful anaconda-mode results.
Successful results and errors can appear in 1 or 2 secconds.
It seems they are not regular.

**Comment by asdyjd** [comment]
When the errors occur, the emacs stick for about 500ms.It makes me unhappy.
I am a Chinese,I don't know if I am using the right words to describe the problem.I am sorry for that.

**Comment by proofit404** [comment]
What emacs version do you use? I remember similar problems happens a year ago. But they were fixed.

**Comment by asdyjd** [comment]
24.5,Latest version downloaded from ftp://ftp.gnu.org/pub/gnu/emacs/windows/
And When I delete the .emas file,these errors occur too.So I am asure it's not my setting's problem.

**Comment by xarthurx** [comment]
Has this bug been fixed?

**Comment by asdyjd** [comment]
@xarthurx 
Update spacemacs and all packages.Now it occurs occasionally.

**Comment by xarthurx** [comment]
@asdyjd 
I'm using the latest spacemacs and packages. The problem occurs whenever I try to auto-complete for a very short input.

For example, if I input "numpy." and waited for  a second, this problem will occur, but if I quickly "numpy.abs" it will show info about this problem and no errors will occur.

Besides, when the error did occur, there are may buffer called "127.0.0.1" opens... and everytime I close Emacs, these need to be killed.

But I understand your comments in another post that you don't have time.

**Comment by proofit404** [comment]
Yeh, sorry for that.

**Comment by proofit404** [comment]
Discussion moved to https://github.com/proofit404/anaconda-mode/issues/295
