### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by Purring** [proofit404/anaconda-mode#200]
Just wondering if there are any plans for docker support? I checked an old issue saying that docker + vagrant support was supposed to be added when you merged the tramp branch, but I don't know if it it was canceled because I can't find any info about how to set it up.

**Comment by vladimir-vovk** [comment]
I think, you can ssh to your docker container (similar to your vagrant box). But it takes some extra steps...
http://stackoverflow.com/questions/30172605/how-to-ssh-into-a-docker-container
"... 

Lets say, for reasons that are your own, you really do want to use SSH. It takes a few steps, but it can be done. Here are the commands that you would run inside the container to set it up...

apt-get update
apt-get install openssh-server

mkdir /var/run/sshd
chmod 0755 /var/run/sshd
/usr/sbin/sshd

useradd --create-home --shell /bin/bash --groups sudo username ## includes 'sudo'
passwd username ## enter a password

apt-get install x11-apps ## X11 demo apps (optional)
ifconfig | awk '/inet addr/{print substr($2,6)}' ## display IPADDRESS (optional)
Now you can even run graphical applications (if they are installed in the container) using X11 forwarding to the ssh client.

ssh -X username@IPADDRESS
..."

**Comment by proofit404** [comment]
@vladimir-vovk thanks for this explanation! This is indeed how docker container can be accessed for now.

@Purring I have plans to support `/docker:` tramp method. It will help you to avoid ssh installation inside your containers. But for now it is only plans since I'm short on time.

**Comment by mimischi** [comment]
Any news on this or how to help?

**Comment by proofit404** [comment]
Hi @mimischi 

Currently I have no time to do this feature.

If you describe your workflow with docker, maybe I can suggest possible solution to you.

Regards, Artem.

**Comment by mimischi** [comment]
Thanks for getting back! So I've  just started using [spacemacs](https://github.com/syl20bnr/spacemacs) and I'm just transitioning to a new workflow.

Before I've been using PyCharm with a Docker Compose setup provided by the [cookiecutter-django](https://github.com/pydanny/cookiecutter-django/) package. Basically the setup runs both PostgreSQL and Django in their own container.
PyCharm has the option to use the remote python interpreter (the one running inside the Docker).

I'd be wondering if the same thing is possible to achieve using anaconda-mode. Looks like Tramp does support something similar, but I'm not very sure on the setup?

**Comment by proofit404** [comment]
Remote interpreters supported over ssh only at this time.

What is the path of interpreter inside docker container?

**Comment by proofit404** [comment]
Looks like it's using global python interpreter inside the container.

**Comment by mimischi** [comment]
Right. Getting ssh to work with Docker containers is a bit hacky as of now. Not sure how PyCharm is doing it currently, but it somehow works out of the box without any further configuration needed inside the actual Docker setup.

**Comment by proofit404** [comment]
I bet it use `docker exec` to execute command inside running containers. I have same idea for anaconda-mode. But it is a lot of work to implement and test this functionality in the pythonic and anaconda-mode packages.

**Comment by shivamkalra** [comment]
Any update regarding support of docker? I'm using docker-machine to provision some remote docker machines.

**Comment by proofit404** [comment]
Done.
