### ISSUE TITLE
anaconda-mode-show-doc does NOT work while elpy-doc works

### ISSUE THREAD

**Issue by cnglen** [proofit404/anaconda-mode#202]
For some case, M-? not works. While elpy-mode will work.

While reading [tensorflow](https://github.com/tensorflow/tensorflow.git): try to find the doc of `tf.contrib.layers`
- No documents a available (anaconde-mode)
- show docs in elpy-mode

**Comment by proofit404** [comment]
Did you activate virtual environment in emacs?
