### ISSUE TITLE
Anaconda-mode fails if buffer-file-name is nil

### ISSUE THREAD

**Issue by millejoh** [proofit404/anaconda-mode#206]
If `buffer-file-name` is nil in the buffer where anaconda-mode is active, the following error is generated:

```
Server error: TypeError("unhashable type: 'dict'",)
```

Looking at the code in `anaconda-mode-jsonrpc-request-data` one would think that None would be generated if `buffer-file-name` is nil, but somehow the nil is turning into an empty dict. It seems to work okay if the code explicitly returns an empty string in the case that `buffer-file-name` is nil.

**Comment by proofit404** [comment]
Uh, sorry I forgot to answer.

Yes this is known problem.

**Comment by proofit404** [comment]
Fixed in master.
