### ISSUE TITLE
Show argument list

### ISSUE THREAD

**Issue by quicknir** [proofit404/anaconda-mode#208]
I'm using anaconda-mode via the spacemacs python layer. When I try to do completion for a typical candidate in anaconda it looks like this:

```
self.assertEqual<function: case.TestCase.assertEqual>
```

When I switch to ycmd for auto completion it looks like this:

```
assertEqual(self, first, second, msg=None) [function: case.TestCase.assertEqual]
```

I find that information useful. Then I discovered `company-anaconda-annotation-function`. So I tried to customize. When I use the following code as a test case, it works:

```
  (defun anaconda-description (candidate)
    (concat
     (get-text-property 0 'description candidate)
     (get-text-property 0 'description candidate)))
  (setq company-anaconda-annotation-function 'anaconda-description)
```

(and just shows the information twice). Looking at the docs, it seems like the way to get the information I want would be via `'line`. So I change the first description to `'line`. When I do that though, I now get an error. Is what I want possible, and if so, how would I go about it?

**Comment by quicknir** [comment]
Ah, ok. I figured out that line is actually the line number. Is there any simple way to make this happen?

**Comment by proofit404** [comment]
Hello. Thanks for feedback. Can you remove byte code files from your installation, add this setting `(setq debug-on-error t)` and show me full traceback of the error you got.

**Comment by quicknir** [comment]
Hey, sorry my last post wasn't clear. The error was because I was trying to concatenate with a number, which isn't allowed. When I do `(number-to-string (get-text-property 0 'line candidate))` it works fine. But the line number isn't really what I'm after, it's more being about to see the arguments. And, ideally, integrating the arguments into yasnippet.

**Comment by proofit404** [comment]
I've looked at ymcd sources. It does it in interesting way. It's kinda hacky I can say.

Emacs plugin get function signature from the documentation string using [regular expression](https://github.com/abingham/emacs-ycmd/blob/831e09aeecedf0128177b46ecbd0ba511cd3c864/company-ycmd.el#L265-L279). This docstring is a result of inner [api call](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/python/jedi_completer.py#L265-L271) of ycmd which is actually another [wrapper call](https://github.com/vheon/JediHTTP/blob/33082a33504b738f517e404c2e587fbc36e5a35b/jedihttp/handlers.py#L55-L71).

The [same thing](https://github.com/proofit404/anaconda-mode/blob/ed5a7d7ce711a23e86fd188ed5f906f119c56f6e/anaconda_mode.py#L40-L51) happens in the anaconda-mode server. You can add same behaviour with your own annotation function according to the company-anaconda [customization guide](https://github.com/proofit404/company-anaconda#customization).

Hope this helps.

**Comment by quicknir** [comment]
@proofit404 I was looking at this issue again recently, largely because anaconda's perf seems to be much better than ycmd's. One thing that I noticed is that spacemacs' python layer, in the minibuffer, always shows me the signature of whatever function my cursor is in. It's extremely reliable as well. Is this coming from anaconda? I can't seem to see from where, but I don't know where else it could be. If it is coming from anaconda, couldn't this be re-used to provide the arguments?

Also, it's not just a matter of showing the arguments in the completion. This feature is nice, but what is really killer IMHO is that ycmd basically creates a template when you semantically complete. So each argument's name gets pasted in and highlighted, and you fill in each one in turn and tab to the next one. Really jogs your memory nicely have them right on the cursor in front of you.

**Comment by proofit404** [comment]
Hello,

Yes its eldoc, but it works on top of anaconda-mode.  Actually it anaconda-eldoc-mode :)

Yasnippet support for company-anaconda is more than welcome. I'll provide necessary information if you're interesting in it. I can't write it myself because I'm very short on time right now.

**Comment by proofit404** [comment]
Close due to inactivity.
