### ISSUE TITLE
Request adding a mode-icon

### ISSUE THREAD

**Issue by eflanigan00** [proofit404/anaconda-mode#209]
It would be nice to have an icon for this:
https://github.com/ryuslash/mode-icons

**Comment by proofit404** [comment]
LOL Is something necessary from me, or all changes applies to the `mode-icons` repository?

**Comment by eflanigan00** [comment]
Sorry for troubling you with this, I've been requesting them from some of my favorite modes :)
Someone just needs to pick and or create an icon.
And inform the mode-icons maintainer.
Maybe a capital 'A' or an 'A' overlaying a python symbol. Not sure whatever you guys want to do!

I really love the package by the way, thank you for the great work!

**Comment by proofit404** [comment]
Maybe we can use this logo https://github.com/proofit404/anaconda-mode/blob/master/static/logo.png
since it's official anaconda-mode symbol already.

Can you try to make icon from it? I'm very short on time this days.

**Comment by eflanigan00** [comment]
Thank you, yes I can try!

**Comment by proofit404** [comment]
Close due to inactivity.
