### ISSUE TITLE
helm-anaconda.el

### ISSUE THREAD

**Issue by proofit404** [proofit404/anaconda-mode#21]
Select definitions and references similar to [helm-swoop](https://github.com/ShingoFukuyama/helm-swoop/blob/master/helm-swoop.el#L985).

**Comment by CestDiego** [comment]
What would be needed for this to work ? D: where do we get a list of candidates?

**Comment by proofit404** [comment]
Hello. Currently I work on `pypi` branch where candidates / definitions / assignments processes in the server response callback. I can add some hook / customization mechanism there so you can implement `helm` backend. But this is future work. If you implement this backend now - it will be necessary to rework it a lot after `pypi` feature branch finish.

**Comment by CestDiego** [comment]
Ok I'll wait until then, thank you for your excellent work on anaconda :)

**Comment by proofit404** [comment]
@CestDiego `pypi` branch was merged into master. You can use customizable callbacks to write your helm package.
