### ISSUE TITLE
Can't find the release

### ISSUE THREAD

**Issue by eflanigan00** [proofit404/anaconda-mode#210]
I'm using a local MELPA (behind a firewall).
Emacs 25.1.1  and the installed package looks like this:
  anaconda-mode      20161028.29   installed   

Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
IPython 5.1.0 -- An enhanced Interactive Python.

Why is anaconda looking to pypi?

Searching for anaconda_mode==0.1.6
Reading https://pypi.python.org/simple/anaconda_mode/
Download error on https://pypi.python.org/simple/anaconda_mode/: [Errno -2] Name or service not known -- Some packages may not be found!
Reading https://pypi.python.org/simple/anaconda-mode/
Download error on https://pypi.python.org/simple/anaconda-mode/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'anaconda_mode' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for anaconda_mode==0.1.6
An exception has occurred, use %tb to see the full traceback.

[0;31mSystemExit[0m[0;31m:[0m error: Could not find suitable distribution for Requirement.parse('anaconda_mode==0.1.6') (--always-copy skips system and development eggs)

/home/wb602e/sys/src/anaconda3-4.2.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
[0;31m[0m
[0;31mImportError[0mTraceback (most recent call last)
[0;32m<ipython-input-1-7de66df3eaa2>[0m in [0;36m<module>[0;34m()[0m
[1;32m      2[0m [0;32mimport[0m [0msys[0m[0;34m,[0m [0msite[0m[0;34m[0m[0m
[1;32m      3[0m [0msite[0m[0;34m.[0m[0maddsitedir[0m[0;34m([0m[0;34m'.'[0m[0;34m)[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mimport[0m [0manaconda_mode[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0manaconda_mode[0m[0;34m.[0m[0mmain[0m[0;34m([0m[0msys[0m[0;34m.[0m[0margv[0m[0;34m[[0m[0;36m1[0m[0;34m:[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0m

**Comment by proofit404** [comment]
Yes, anaconda_mode is available on PyPI.

    Name or service not known

Looks like you have some network problems which cause this error to happen. It may occurs only within Emacs however.

**Comment by eflanigan00** [comment]
I have it installed, it shouldn't need to go out to pypi. Is it not possible to run without connecting to the internet?

**Comment by proofit404** [comment]
Your installation should pass [this check](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L129-L155)

**Comment by eflanigan00** [comment]
I did pip install of (it was failing but I didn't have them installed).
    
    pip install service_factory-0.1.5.tar.gz
    pip install anaconda_mode-0.1.6.tar.gz

Now I get this:
Searching for anaconda_mode==0.1.6
Skipping development or system egg: anaconda-mode 0.1.6
Reading https://pypi.python.org/simple/anaconda_mode/
Download error on https://pypi.python.org/simple/anaconda_mode/: [Errno -2] Name or service not known -- Some packages may not be found!

error: Could not find suitable distribution for Requirement.parse('anaconda_mode==0.1.6') (--always-copy skips system and development eggs)

How do I disable --always-copy?   
I need to use the system (or local version of anaconda_mode.

What is the calling routine for the code you pointed me to?  What is sys.argv[-1]?

**Comment by proofit404** [comment]
You can't use `anaconda_mode` python package installed somewhere else. Your custom installation should be compatible with `anaconda-mode` internal machinery. Please try to run script written below in your shell.
```shell
python -c "
import os, sys
from setuptools.command import easy_install
directory = os.path.expanduser(sys.argv[-2])
version = sys.argv[-1]
sys.path.append(directory)
easy_install.main(['-d', directory, '-S', directory, '-a', '-Z',
                   'anaconda_mode==' + version])
" "~/.emacs.d/anaconda-mode/0.1.6" "0.1.6"
```

**Comment by eflanigan00** [comment]
That is why I am confused that source code gives me the same error.
Searching for anaconda_mode==0.1.6
Skipping development or system egg: anaconda-mode 0.1.6
Reading https://pypi.python.org/simple/anaconda_mode/
Download error on https://pypi.python.org/simple/anaconda_mode/: [Errno -2] Name or service not known -- Some packages may not be found!

But when I do this, I have it installed. 

    > pip list | grep anaconda-mode
    anaconda-mode (0.1.6)

Maybe I can use easy_install to install it to the proper directories?
What are the sys.argv in your calling routine?

**Comment by eflanigan00** [comment]
The system is on a firewall and I'm not about to access pypi

**Comment by proofit404** [comment]
The easiest way is to copy `~/.emacs.d/anaconda-mode` directory from another computer. Alternatively you can try to download eggs from pypi, copy them to the target computer and play with `easy_install` options.

**Comment by proofit404** [comment]
I think you should check following options
```
  --index-url (-i)           base URL of Python Package Index
  --find-links (-f)          additional URL(s) to search for packages
```

**Comment by eflanigan00** [comment]
Ok thank you, I will try to use easy_install on the egg!
Is directory ~/.emacs.d/anaconda-mode/  with the following line?

    directory = os.path.expanduser(sys.argv[-2])

**Comment by proofit404** [comment]
No, it should include package version like `~/.emacs.d/anaconda-mode/0.1.6`

**Comment by eflanigan00** [comment]
It worked, thank you so much for your help!!
I updated the wiki, feel free to edit or change it if you feel like it.

    import os, sys
    from setuptools.command import easy_install
    version = "0.1.6"
    directory = os.path.join("/home/username/.emacs.d/anaconda-mode/", version)
    sys.path.append(directory)
    local_package_dir = '/home/user/anaconda_mode_pkg/'
    easy_install.main(['-d', directory,            # install package to DIR
                       '-S', directory,            # list of directories where .pth files work
                       '-a',                       # Always copy all needed packages to install dir
                       '-Z',                       # don't install as a zipfile, no matter what
                       '-f', local_package_dir,    # additional URL(s) to search for packages
                       'anaconda_mode==' + version])

**Comment by proofit404** [comment]
Thanks for the wiki entry! :+1:
