### ISSUE TITLE
Add user option for anaconda-mode lighter

### ISSUE THREAD

**Issue by darkfeline** [proofit404/anaconda-mode#211]
Many minor modes, both in Emacs and third party, expose a user option to configure the mode line lighter when a minor mode is active (example, `auto-revert-mode-text` in `autorevert.el`).

It would be nice if `anaconda-mode` had such an option since the default lighter string is so long, and provides easier customization without needing to rely on, e.g. `diminish.el`

**Comment by proofit404** [comment]
Hm, I thought `diminish` library is the standard de facto. I'm using it myself to configure `anaconda-mode` lighter.

**Comment by darkfeline** [comment]
`diminish` is certainly popular, but it is not standard to Emacs (it is a third party package after all).  You can see from the `auto-revert-mode` example that many package that ship with Emacs provide an option to allow easy customization.

`projectile-mode` also does this, for another example.  This also allows users to use an arbitrary Elisp expression as the lighter, for example using different characters under different conditions.

``` emacs-lisp
(define-minor-mode projectile-mode
  "Minor mode to assist project management and navigation.
..."
  :lighter projectile-mode-line
  ...)

(defcustom projectile-mode-line
  '(:eval (if (file-remote-p default-directory)
              " Projectile"
            (format " Projectile[%s]" (projectile-project-name))))
  "Mode line lighter for Projectile.

The value of this variable is a mode line template as in
`mode-line-format'.  See Info Node `(elisp)Mode Line Format' for
details about mode line templates.

Customize this variable to change how Projectile displays its
status in the mode line.  The default value displays the project
name.  Set this variable to nil to disable the mode line
entirely."
  :group 'projectile
  :type 'sexp
  :risky t
  :package-version '(projectile . "0.12.0"))
```

It's a relatively small change that gives users many easy customization options.

**Comment by proofit404** [comment]
Ok, I agree that this change is meaningful. Will you provide PR?

**Comment by darkfeline** [comment]
https://github.com/proofit404/anaconda-mode/pull/212
