### ISSUE TITLE
Keep errors open in a separate window

### ISSUE THREAD

**Issue by mnbf9rca** [proofit404/anaconda-mode#213]
When reviewing code with a lot of errors (someone else's of course :) ) it's annoying when the sublime popup with the error list keeps disappearing. It would be good to have it as a floating window, or docked to the bottom of the editor, like the error list in Visual Studio when working with e.g. c#. Is this possible?

**Comment by proofit404** [comment]
Looks like you have troubles with `anaconda_mode` server connection stability. I can suppose that frequently eldoc queries causes requests when you don't edit code.

You can try to use packages like `popwin.el` if you like to change this error window position.

But I think that you better try to find the reason of connection problems.

**Comment by mnbf9rca** [comment]
oops -  i've submitted my issue to the wrong anaconda project. How embarrasing! sorry!
