### ISSUE TITLE
anaconda-mode server setup fails if setuptools is not installed

### ISSUE THREAD

**Issue by KevOrr** [proofit404/anaconda-mode#215]
__Description__

When using anaconda-mode for the first time, editing will ungraciously fail if setuptools is not installed. Attempting to enter insert mode results in the error message ```Can not install `anaconda-mode' server``` and a traceback `ImportError: No module named setuptools.command`

__How to reproduce__

* Uninstall/never had installed `setuptools`
* Install `anaconda-mode`
* Open a .py file

__System info__
* Emacs: 24.5.1
* Spacemacs: 0.200.5 (664ba6a)
* anaconda-mode: 20161121.1137
* OS: Linux Mint 18 Sarah

**Comment by proofit404** [comment]
Hi,

Thanks for giving a try of my package.

This is expected behavior https://github.com/proofit404/anaconda-mode#installation

If you have better design decision in mind, feel free to reopen this issue.

Regards, Artem.
