### ISSUE TITLE
anaconda-mode keeps getting error 'Server error: KeyError(u'\u4e2d\u82f1\u6587\u6458\u8981',)' while in an org src block

### ISSUE THREAD

**Issue by et2010** [proofit404/anaconda-mode#216]
#### Description :octocat:
When cursor is within a org src block (between 'begin_src' and 'end_src'), I keep getting this error message:
```
Server error: KeyError(u'\u4e2d\u82f1\u6587\u6458\u8981',)
```
Meanwhile I get following backtrace in \*anaconda-mode\*:
```
anaconda_mode port 43341
127.0.0.1 - - [20/Dec/2016 07:56:54] ================================================================================
Traceback (most recent call last):
  File "/home/neoarch/Envs/venv-org/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/neoarch/Envs/venv-org/lib/python2.7/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/neoarch/Envs/venv-org/lib/python2.7/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/neoarch/Envs/venv-org/lib/python2.7/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'\\\\u4e2d\\\\u82f1\\\\u6587\\\\u6458\\\\u8981\',)"}}')
```

#### Reproduction guide :beetle:
- Start Emacs
- Open an org buffer with python src block
- Move the cursor within a python src block to get the error

*Observed behaviour:* :eyes: :broken_heart:
As described above

*Expected behaviour:* :heart: :smile:
No error in \*anaconda-mode\*

#### System info
- emacs 25.1.1
- spacemacs 0.200.5 (on dev.)
- org-mode 9.0
- python 2.7 in a virtual environment
- python packages:
```
backports.shutil-get-terminal-size==1.0.0
cycler==0.10.0
decorator==4.0.10
Django==1.10.4
enum34==1.1.6
image==1.5.5
ipython==5.1.0
ipython-genutils==0.1.0
jedi==0.9.0
matplotlib==1.5.3
matplotlib2tikz==0.5.16
numpy==1.11.3
packaging==16.8
pandas==0.19.1
pandoc-attributes==0.1.7
pandoc-eqnos==0.16
pandoc-xnos==0.9
pandocfilters==1.4.1
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==3.4.2
pip==9.0.1
pip-review==0.5
prompt-toolkit==1.0.9
psutil==5.0.0
ptyprocess==0.5.1
Pygments==2.1.3
pyparsing==2.1.10
python-dateutil==2.6.0
pytz==2016.10
service-factory==0.1.5
setuptools==32.1.2
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.1
wcwidth==0.1.7
wheel==0.29.0
```

All packages are up-to-date.

Note that this issue only affects python src block in an org buffer, editing python code in dedicated buffers is not affected, eg. editing the src block in a dedicated buffer by calling `org-edit-src-code` will be fine.

**Comment by et2010** [comment]
Switching to jedi 0.8.1 solves the issue but it will lead to a more annoying issue that *anaconda-response* buffer pops more frequently. The latter makes anaconda-mode unusable, so I have to choose the lesser of two evils and switch back to jedi 0.9.

**Comment by proofit404** [comment]
Hello. Thanks for such a verbose report.

Unfortunately there is nothing I can do for you. This bug indeed persist in the jedi 0.9 package. You can try to upgrade it from master or dev branch. Hope this'll help.

Regards, Artem.

**Comment by et2010** [comment]
Thanks for the quick reply. I'll definitely try it.
