### ISSUE TITLE
code browsing question.

### ISSUE THREAD

**Issue by Mafeuser** [proofit404/anaconda-mode#217]
Hallo

I'm planning to use spacemacs as my python IDE.
I need to work with some python 2.x framework, namely avocado framework.

Below is just a simple python class (it uses avocado framework).

When I try to visit definition of 'get' function with M-. (anaconda-mode-find-definitions), I end up with message: "no definitions found".

```
#!/usr/bin/env python

from avocado import Test

class MyTest(Test):   # M-. on 'Test' ends up in test class. This is fine.

    def test_mine(self):
        myParam = self.params.get(key='myParm', path='/', default=None)  ## M-. on 'get' fails. PyCharm does the job.

if __name__ == "__main__":
    main()
```

Is there something I can do (by means of confuguration tweak) to have it work?

My spacemacs config regarding python is not touched.

regards

**Comment by proofit404** [comment]
It depends on how `Test` class was defined, but I don't think there is something you can do to fix it.

**Comment by Mafeuser** [comment]
@proofit404, thanks for the answer. You say that it depends on how Test is defined, but jumping to 'Test' definition from "class MyTest(Test)" line, succeeds. Does it mean something or still nothing?

**Comment by proofit404** [comment]
By saying "how Test was defined" I mean:
* where `self.params` was assigned?
* does this class has custom metaclass?
* does it provide type annotations in the docstrings?
