### ISSUE TITLE
Problems using a Python3-based shell-interpreter

### ISSUE THREAD

**Issue by fth86** [proofit404/anaconda-mode#219]
Hi, 

First off - thank you a lot for your work here. I have so far been thoroughly enjoying anaconda-mode. I switched to Python3 recently, however, and that seems to have broken something.

Completion does not work, and anaconda buffers pop up frequently.
This is the output of the *anaconda-mode* buffer:  

> anaconda_mode port 37443
> Process anaconda-mode killed
> anaconda_mode port 34117
> Process anaconda-mode killed 
> (... ad infinitum...)

The output of the *anaconda-response* buffer depends on the exact python executable I use.
The one from the Anaconda distribution leads to an output of
>  status: nil
>  point: 1

The system one (*/usr/bin/python3*) to
>  status: (:error (error connection-failed failed with code 111
> :host 127.0.0.1 :service 43931))
>  point: 1

I am using the newest Emacs Snapshot 26.0.50 with Spacemacs, but I see the same behavior in 
Emacs 25 (with Spacemacs). These are the different flavors of python interpreters I have tried:

> (setq python-shell-interpreter "/usr/bin/ipython")    ;; works   (ipython 2.7, python 2.7.12)
> (setq python-shell-interpreter "/usr/bin/python")     ;; works    (python 2.7.12)
> (setq python-shell-interpreter "/usr/bin/python3")   ;; fails       (python 3.5.2)
> (setq python-shell-int "/home/myname/software/anaconda/bin/python3.5")   ;; fails (python 3.5.2, Anaconda distribution)
> (setq python-shell-int "ipython")  ;; fails (ipython5, python 3.5.2, Anaconda distribution)

Anything I can do to help narrow down the problem?

**Comment by proofit404** [comment]
This is really weird. `*anaconda-mode*` buffer should looks this way only when you change settings related to python interpreter (like python path or virtual environment root). The only thing I can say that for some strange reason `anaconda_mode` server restart very frequently (maybe by Emacs itself). As a result requests made in parallel can't reach this not started yet server and results into error you see in the `*anaconda-response*` buffer.

**Comment by fth86** [comment]
Okay, so you think this has to do with the server getting requests too quickly, i.e., while still initializing, or something? I have indeed always just tried to immediately *use* the server, while busy in the code.

But I just tried to start the server manually via (anaconda-mode-start), wait a while, and only then try to to use it. And the result is the same. So I guess it must be something else?

I just noticed now, that, before the anaconda-mode process is killed and restartet there's a "Skip anaconda-mode complete response" message in the minibuffer. Does that tell us anything?

**Comment by proofit404** [comment]
`anaconda_mode` process stdout and stderr binds to `*anaconda-mode*` buffer. If there is any output you must see it.

Skip messages mean that `anaconda_mode` respond with completions but you already move point so threre is no sense to show completion list in the wrong place.

`anaconda_mode` is fully compatible with python3 from the beginning. Actually python2 support were introduced few month after first public release.

**Comment by fth86** [comment]
ok - setting up a fresh anaconda environment fixed it somehow.  I had some issues with anaconda updates a couple of days ago - maybe this was somehow related...

Thanks for your input!

**Comment by proofit404** [comment]
Glad you fix it. Feel free to reopen if any related problems occurs again.
