### ISSUE TITLE
Python 3.5?

### ISSUE THREAD

**Issue by s0undt3ch** [proofit404/anaconda-mode#220]
Although I haven't stumbled on an issue yet, your docs state that python 3.4 is the highest supported version. Is this true or the readme just needs to be updated?

I'm pretty new to anaconda-mode. I'm using it on spacemacs which I have been trying out whenever I find the time so that eventually I switch from vim to spacemacs. The project that I'm trying it on is a python 3.5 project, but as mentioned, so far, I apparently haven't hit a snag.

**Comment by proofit404** [comment]
I use anaconda-mode without any problems on python3.5 but we run tests up until python3.4 only.

**Comment by s0undt3ch** [comment]
Awesome! I'll be back if I do stumble on any issue.
Thanks!
