### ISSUE TITLE
Auto-import/search imports for symbols

### ISSUE THREAD

**Issue by dan-passaro** [proofit404/anaconda-mode#223]
I am enjoying anaconda-mode, the ability to get documentation and jump around to code definitions with quick keybindings is great.

However, one feature I make heavy use of in PyCharm that I can't quite find an Emacs replacement for is an autocomplete that will use *all* names available across all modules, and add an import for me if the name isn't already available. This makes it a lot easier to locate classes in large libraries like Django where the module layout is more difficult to memorize.

Is there any interest in a feature like this for anaconda-mode?

**Comment by proofit404** [comment]
Hello.

I use GNU Globals with pygments parser for searching names in large code bases. Insertion can be achieved with little Emacs Lisp code. Hope this helps.

There is no plans to add this feature to anaconda-mode as far as jedi library don't support this kind of search.

Regards, Artem.
