### ISSUE TITLE
Incomplete call signature shown by eldoc

### ISSUE THREAD

**Issue by sebhofer** [proofit404/anaconda-mode#226]
I'm getting incomplete call signatures displayed by eldoc-anaconda. For example, placing the cursor between the brackets in this snippet
`np.linspace()`
gives me something like the following in the minibuffer
`linspace(, , , nt=True, [...])`
where [...] denotes some more text I didn't want to type. The curious thing is that the complete argument list is displayed while the completion popup is activated. In other words, I type `np.lin` and wait for the popup to appear. Then after some more time, the complete call signature is displayed in the minibuffer. Another thing I noticed is, that in this case there is no fancy formating (colors, bold fonts, etc.), but when the incomplete list is displayed `linspace` is bold and in color.

Is this a known issue?
TIA Sebastian

**Comment by proofit404** [comment]
Eldoc arguments are displayed correctly
![np_eldoc](https://cloud.githubusercontent.com/assets/1862725/23152211/e307604c-f819-11e6-8b9c-57c6b0f9c2b3.png)
Completion meta information looks the same
![np_complete](https://cloud.githubusercontent.com/assets/1862725/23152227/fd8b4cbc-f819-11e6-8650-e8c9ba189d45.png)
I can guess that you install older jedi library.

**Comment by sebhofer** [comment]
That was indeed the reason! Sorry for the noise and thanks for the prompt response!

**Comment by Vicriss** [comment]
Could you tell me how to fix it?
I'm a newer and I'm using @purcell 's config 
I'll appreciate you for any help!

**Comment by proofit404** [comment]
Can you describe (or show with screenshot) you current problem. What behavior do you expect?

**Comment by Vicriss** [comment]
As same as @sebhofer describe, minibuffer shows that incompletely
![image](https://cloud.githubusercontent.com/assets/9296808/25284517/ca066846-26e9-11e7-8b75-8f6578694dd4.png)
BTW, when I open a python file first time, import numpy as np, completion meta information do not show.
Then I type TAB, minibuffer show that, 

> Completion needs a inferior Python process running

**Comment by proofit404** [comment]
Can you provide full config?

**Comment by Vicriss** [comment]
I'm using @purcell 's [config](https://github.com/purcell/emacs.d)

Addition, I add some my own config to init.el
```
;; default window frame
(setq default-frame-alist
      '((height . 50) (width . 85) (top . 100) (left . 800) (menu-bar-lines . 20) (tool-bar-lines . 0)))

;; For Linux (font)
(set-face-attribute 'default nil :font "Droid Sans Mono-11" )
(set-frame-font "Droid Sans Mono-11" nil t)

;; enable line numbers globally
(global-linum-mode t)

(custom-set-variables
 '(menu-bar-mode nil))

(provide 'init-myconfig)
```
And change theme

**Comment by jrab89** [comment]
I was having the same problem. Upgrading from jedi-0.9.0 to jedi-0.10.2 fixed this for me.
