### ISSUE TITLE
python-shell-extra-pythonpaths vs. PYTHONPATH

### ISSUE THREAD

**Issue by agriffis** [proofit404/anaconda-mode#227]
For looking up definitions, this works for me:

```emacs
(setenv "PYTHONPATH" "/home/aron/src/project/.virtualenv/lib/python3.6/site-packages")
```

However this doesn't seem to work:

```emacs
(add-to-list 'python-shell-extra-pythonpaths "/home/aron/src/project/.virtualenv/lib/python3.6/site-packages")
```

In the former case, I can use `SPC m g g` (Spacemacs key binding) to jump to definitions in the virtualenv. In the latter case, it just says "No definitions found"

In theory, I should just use `pyvenv-activate` but the virtualenv is actually bind-mounted into a docker container, and the python executable isn't compatible with the host system. It actually works fine for jedi to statically parse the files, so long as anaconda-mode uses the host Python binary rather than the one in the virtualenv. So that's why I'm not actually activating the virtualenv, just setting `PYTHONPATH` instead.

Which gets back to the problem. I'd like something that works at the project level, probably using `.dir-locals`, so I'd like to know if I misunderstood `python-shell-extra-pythonpaths`, or if there's something else you'd recommend.

**Comment by agriffis** [comment]
Well, here's what I ended up with:

```emacs
  (defun agriffis/setenv-from-dir-locals ()
    (cond ((boundp 'agriffis/env)
           (make-local-variable 'process-environment)
           (dolist (kv agriffis/env)
             (setenv (car kv) (cdr kv))))
          ((local-variable-p 'process-environment)
           (kill-local-variable 'process-environment))))

  (add-hook 'hack-local-variables-hook 'agriffis/setenv-from-dir-locals)
```

with this in `.dir-locals.el`

```emacs
((python-mode . ((agriffis/env . (("PYTHONPATH" . "/home/aron/src/ss/furls/.virtualenv/lib/python3.6/site-packages"))))))
```

so now I have a generic way to set buffer-local environment variables from `.dir-locals.el`

**Comment by proofit404** [comment]
Actually `python-shell-extra-pythonpaths` variable should work. This is [source code](https://github.com/proofit404/pythonic/blob/master/pythonic.el#L99-L106) which process it. Can you try to reproduce this bug without spacemacs?

**Comment by proofit404** [comment]
Feel free to reopen this issue if problem still persist.
