### ISSUE TITLE
Server error and async timeout 

### ISSUE THREAD

**Issue by wandersoncferreira** [proofit404/anaconda-mode#228]
Hi, I am using anaconda-mode and company-anaconda.

I have seen the Server error: ValueError('not enough values to unpack (expected 1, got 0)',)

Reproducing:
```python
import numpy as np

test = np.[C-M-i]
```

And when hitting the company completion key bindings I got an error message as:

Company: backend (company-anaconda company-dabbrev company-capf) async timeout with args (candidates np.)

**Comment by proofit404** [comment]
Hello. This error comes from jedi library. Did you select virtualenv with numpy in Emacs.

**Comment by wandersoncferreira** [comment]
I have this line in my init.el:

```
  (use-package pyvenv
    :ensure t
    :config
    (pyvenv-activate "/home/bartuka/miniconda3"))
```

**Comment by proofit404** [comment]
Hmm, so error occurs even with numpy available to jedi. Let's hope next jedi release will fix it. You can also try to install jedi from master. You can find instructions in the previous issue.
