### ISSUE TITLE
anaconda-mode-show-doc for auto-generated documentation?

### ISSUE THREAD

**Issue by sebhofer** [proofit404/anaconda-mode#229]
Is there a way to get show the doc string for functions with auto-generated documentation, e.g., matplotlib.pyplot.plot? If I run anaconda-mode-show-doc on them, I only get
`pyplot
plot(*args, **kwargs)`
Is this the expected behaviour or did I misconfigure something? Both the jupyter web interface and EIN manage to give a meaningful documentation.

**Comment by proofit404** [comment]
I don't know if jedi tries to calculate modifications made to `__doc__`. IPython do this through introspection of already executed code. Jedi is static analysis tool. This is big difference in each tool possibilities. Try to file an issue into jedi bug tracker to get more info. There is no settings in anaconda-mode related to docs.

**Comment by sebhofer** [comment]
Makes sense. Thanks for the quick reply!
