### ISSUE TITLE
No completions inside an async function

### ISSUE THREAD

**Issue by r-darwish** [proofit404/anaconda-mode#233]
When writing the following code

```
def something():
    var = ""
    var.st
```

I get autocompletion suggestions as expected. When adding the `async` keyword to the beginning of the function I get no completions at all. I am using the development branch of Jedi. This seems like a Jedi problem at first, but there are no exceptions shown in the `*anaconda-mode*`. In addtion, Jedi is supposed to support `async` functions. I made a little script to invoke Jedi directly on the above code:

```
from jedi.api import Script

x = Script(source_path='test.py', line=3, column=9)
print(repr(x.completions()))
```

The output of the script is the same whether the `async` keyword is present or omitted:

```
[<Completion: split>, <Completion: splitlines>, <Completion: startswith>, <Completion: strip>, <Completion: swapcase>]
```

This leads me to believe that the problem may be in Anaconda. Is it possible that Anaconda does not invoke Jedi at all when dealing with async function?

**Comment by proofit404** [comment]
Can't reproduce your problem. Can you provide any additional information?
![async_complete](https://cloud.githubusercontent.com/assets/1862725/23719433/657d3ec8-044c-11e7-92ee-7e5d298543d3.png)

**Comment by r-darwish** [comment]
Using Spacemacs on both macOS and Linux. Anacoda's version is `20170214.556`. I'll try stripping my config to the bare minimum that causes reproduction.

**Comment by proofit404** [comment]
Feel free to reopen this issue if you came up with reproducible example.
