### ISSUE TITLE
`*anaconda-mode*` buffer agressively takes control

### ISSUE THREAD

**Issue by gergelypolonkai** [proofit404/anaconda-mode#235]
I had an error in my virtualenv the other day; it was missing core stuff like setuptools. While browsing the Python code inside, I got a lot of messages in the `*anaconda-mode*` buffer. It’s all nice, but that buffer automatically gets selected, making the code buffer unusable. I don’t mind error messages (actually, I like them if they are useful), but this renders Emacs unusable. I couldn’t even close the code buffer, because the `*anaconda-mode*` buffer took control before I could hit `C-x k`.

**Comment by proofit404** [comment]
Looks like I won crappy UX award :)

Maybe you can propose better error reporting for anaconda-mode? What behavior you want exactly?

**Comment by gergelypolonkai** [comment]
Don't get me wrong, I'm happy with the UX in general.

What I would do is not giving focus to the `*anaconda-mode*` buffer. Create it, maybe even present it in the other window like now. But the active window should remain active so I can continue working in it, even though messages flood in `*anaconda-mode*`.

**Comment by gergelypolonkai** [comment]
Now that I’m behind my keyboard, I could create a possible solution (using `display-buffer` instead of `pop-to-buffer`).

**Comment by proofit404** [comment]
It was just a joke. Nevermind :)
