### ISSUE TITLE
anaconda-mode sporadically consumes 100% CPU

### ISSUE THREAD

**Issue by DGalt** [proofit404/anaconda-mode#236]
After some indeterminate period of time of editing python files my CPU usage on one of my cores jumps up to 100%. Checking `top` the process causing the spike is `ipython`. If I kill `anaconda-mode` CPU usage on that core drops down to normal and the process disappears. 

There's nothing in the `anaconda-mode` messages buffer that seems to indicate a problem. Under my Processes in emacs, though, it's obvious that the associated `ipython` process is tied to anaconda-mode. See: 
http://imgur.com/a/ETb5x

I haven't been able to figure out what circumstances reliably recreates this though. Some times it happens within a few minutes of opening up a file and editing, and other times it doesn't occur for an hour or more. The CPU core usage stays at 100% indefinitely -  the only solution I have found so far is just restart emacs, but it inevitably happens again at some point. 

I imagine that this is actually an issue with my system, but I'm not sure where I can get more information to troubleshoot what's going on. 

I'm on Arch linux using a pretty stock install of spacemacs (emacs 25.1-4). Using ipython 5.1.0-2, if that's relevant.

**Comment by proofit404** [comment]
I don't know if it related to my code or used `jedi` library. You can search `jedi` issues for similar bug. Also you can try to run `anaconda_mode.py` in the terminal and send different requests to it. Maybe this way you can come up with reproducible example.

**Comment by DGalt** [comment]
Haven't been able to reproduce this yet this morning, which is a bit maddening. 
I've tried working directly with jedi just in a ipyhon repl and haven't come across anything where it gets hung up. 
I'm not quite sure on how to test completions with `anaconda-mode.py` in a terminal though. The server starts, but I don't understand how to send requests to it.

**Comment by proofit404** [comment]
`anaconda_mode.py` is a json rpc server.

You can interact with it over http. Service Factory README contains example with curl https://github.com/proofit404/service-factory

Available rpc methods are complete, goto_definitions, goto_assignments, usages and eldoc. You can see this in the server code https://github.com/proofit404/anaconda-mode/blob/master/anaconda_mode.py#L101

Each method need four arguments (source, line, column, path). You can find detailed explanation in the jedi documentation http://jedi.readthedocs.io/en/latest/

Hope this helps.

**Comment by DGalt** [comment]
Thanks, that helped a lot. 

I've run a lot of different completion requests through `anaconda_mode.py` now without any hiccups. 

What is getting logged in the `*anaconda-mode*` buffer? Any exceptions that come out of Jedi? 

I'm guessing this is really a Jedi issue. Is there any way to get a fuller picture of what's going on behind the scenes here?

**Comment by proofit404** [comment]
The only way you can do it right now is to put `print(arg)` statement [right here](https://github.com/proofit404/service-factory/blob/e7086bdeb7441dabbbd8ca89a61f388e9c75899b/service_factory/service.py#L46).

**Comment by DGalt** [comment]
Perfect. I'll log that and report back if/when I reproduce the issue.

**Comment by rocha** [comment]
I have a similar problem which may be related. In my case the anaconda process slowly ends up using all available memory, forcing the computer to use swap memory. Killing the process frees the memory. There are no related messages in any of the relevant buffers.

**Comment by DGalt** [comment]
I haven't seen this happen again in the last few days and it seems that jedi has also now had a new release. Feel free to close this, and if it happens again I can come back with more information since I know how to generate a log now.

**Comment by proofit404** [comment]
Ok. Let's close it for now.

**Comment by 3rd3** [comment]
Upgrading from `jedi-0.10.0` to `jedi-0.10.2` seems to have solved the problem for me.
