### ISSUE TITLE
M-x package-install fails on installing dash

### ISSUE THREAD

**Issue by sboisen** [proofit404/anaconda-mode#240]
I do 

        M-x package-install RET anaconda-mode RET

Response is 

    http://melpa.org/packages/dash-20160510.1127.el: Not found

If i do

    M-x list-packages

I can install dash from there, and after that installing anaconda-mode succeeds. So there's a workaround, but i don't know how to suggest fixing your install process (if that's even where the fix needs to happen, which i'm not sure of). 

On Emacs 24.5.1 on OS X El Capitan.

**Comment by proofit404** [comment]
I have no idea why this happens. Maybe it is temporary melpa issue.
