### ISSUE TITLE
*anaconda-mode* buffer contains ansi escape codes in stacktraces

### ISSUE THREAD

**Issue by rgrinberg** [proofit404/anaconda-mode#242]
These escape codes just make the errors harder to read

**Comment by proofit404** [comment]
Hi. Do you use IPython as your reply?

**Comment by rgrinberg** [comment]
Reply? But yeah, I do use ipython in emacs

**Comment by proofit404** [comment]
Stupid Android auto correction :facepalm:

Of course I mean repl.

**Comment by proofit404** [comment]
Fixed in master.
