### ISSUE TITLE
about logic operator

### ISSUE THREAD

**Issue by Vicriss** [proofit404/anaconda-mode#247]
Hi,
I just found a cool feature. When I type in  `a or b` , the operator `or` would be replaced to another
character as 
![image](https://cloud.githubusercontent.com/assets/9296808/25468692/2ce4d29a-2b4a-11e7-97ba-de126a2a38c2.png)
It's amazing! But I am not accustomed to it. How to disable it?
Thanks for any help!

**Comment by proofit404** [comment]
Hi, this functionality is not related to `anaconda-mode`.
