### ISSUE TITLE
anaconda complete with wrong-version python and packages

### ISSUE THREAD

**Issue by ashfinal** [proofit404/anaconda-mode#249]
I have two versions of python: 2.7.13 and 3.6.1, all installed with homebrew. They can be respectively accessed by typing `python` and `python3` in Terminal.
I noticed only the packages installed for python3 can be completed, and anaconda obviously launchs python3 to do this. Since my default interpreter is python2, I have no idea why python3 is launched.
<img width="559" alt="screen shot 2017-05-24 at 19 02 01" src="https://cloud.githubusercontent.com/assets/6827900/26400562/121910dc-40b4-11e7-9131-8193e691f715.png">

I'm wondering how can I use the default python, or specified python?
BTW, I didn't use any virtualenv.

**Comment by proofit404** [comment]
You can set it like this in your config:
```lisp
(setq python-shell-interpreter "/usr/bin/python")
```

**Comment by ashfinal** [comment]
It works, thanks a lot!
