### ISSUE TITLE
Connection failed when using with tramp

### ISSUE THREAD

**Issue by sivakov512** [proofit404/anaconda-mode#251]
When try to use remote python interpreter with tramp I get error like this 
```
# status: (:error (error connection-failed failed with code 111
 :host docker.local :service 35355))
# point: 1
```

My configuration
```(setq python-shell-interpreter "/ssh:root@docker.local#220:/usr/bin/python")```

How can I solve this?
Can I specify port manually for remote connections?

**Comment by mimischi** [comment]
Are you running your Python interpreter inside a Docker Container? Could you provide your Dockerfile? There is another issue #200 asking for Docker support.

For the `ssh` connection to work you would need to have a SSH server running inside your Docker Container and also forward the port to your host machine.

**Comment by cryptomaniac512** [comment]
Yes, the ssh server is started inside the container and the port is dropped.
According to the documentation in the README, the 9000 port is used for communication between client and the server, but as far as I can see, the port for communication is randomly selected in the range of 9000. For example, in this case 35355.

**Comment by thomasluquet** [comment]
@cryptomaniac512 so , what is your solution ?

**Comment by cryptomaniac512** [comment]
@thomasluquet, I have no solution.
Now I do not use Docker, so I do not have a problem yet.

**Comment by proofit404** [comment]
Probably fixed in master. If anyone is affected please submit the new issue.
