### ISSUE TITLE
How to autocomplete packages installed with pip

### ISSUE THREAD

**Issue by thisEric** [proofit404/anaconda-mode#256]
Recently I want to setup Python auto complete for emacs programming, and thanks to anaconda,it has plenty of packages included. After I enabled anaconda-mode and company-anaconda, I test with some system packages, the autocomplete works perfectly, but it cannot find the packages in anaconda subfolders, may I know how to use external installed packages for auto completion ? thanks

**Comment by proofit404** [comment]
Hi. Thanks for trying anaconda-mode.

I'm not familiar with anaconda python distribution. The package itself was named after sublime [anaconda](https://github.com/DamnWidget/anaconda).

If you install other packages into a different directory or into a different virtual environment, you can find instructions related to this topic on the [usage page](https://github.com/proofit404/anaconda-mode#usage) of the readme.

Probably you are looking for pythonpath or virtualenv settings.
