### ISSUE TITLE
everything no longer works after updating to 0.1.9

### ISSUE THREAD

**Issue by LeeiFrankJaw** [proofit404/anaconda-mode#262]
Anaconda-mode works perfectly in the past several months. I update it yesterday from 0.1.8 to 0.1.9 via melpa-stable.

Suddenly everything no longer works.

My host OS is ubuntu 16.04.

**Comment by proofit404** [comment]
Hi,

Any hints from `*anaconda-mode*` and `*anaconda-response*` buffers?

**Comment by LeeiFrankJaw** [comment]
\*anaconda-mode\* buffer says the following.

    Traceback (most recent call last):
      File "<string>", line 4, in <module>
      File "/home/leiz/.emacs.d/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg/anaconda_mode.py", line 22, in <module>
        from service_factory import service_factory
    ModuleNotFoundError: No module named 'service_factory'

**Comment by proofit404** [comment]
Try to remove `/home/leiz/.emacs.d/anaconda-mode/` directory and restart your emacs.

**Comment by LeeiFrankJaw** [comment]
After I remove `~/.emacs.d/anaconda-mode` and restart emacs. The `*anaconda-mode*` buffer now says the following.

    Searching for anaconda_mode==0.1.9
    Reading https://pypi.python.org/simple/anaconda_mode/
    Downloading https://pypi.python.org/packages/a6/f5/a8d433eb628e1584a5f5425a72770cc56d09d99dbc384e08178457cd5d23/anaconda_mode-0.1.9.tar.gz#md5=94c2cd0b72834bd1b1a5a6904dbc774a
    Best match: anaconda-mode 0.1.9
    Processing anaconda_mode-0.1.9.tar.gz
    Writing /tmp/easy_install-wuu2538y/anaconda_mode-0.1.9/setup.cfg
    Running anaconda_mode-0.1.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wuu2538y/anaconda_mode-0.1.9/egg-dist-tmp-g7t4i54u
    no previously-included directories found matching 'test'
    creating /home/leiz/.emacs.d/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg
    Extracting anaconda_mode-0.1.9-py3.6.egg to /home/leiz/.emacs.d/anaconda-mode/0.1.9
    Adding anaconda-mode 0.1.9 to easy-install.pth file
    
    Installed /home/leiz/.emacs.d/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg
    Processing dependencies for anaconda_mode==0.1.9
    Searching for service_factory>=0.1.5
    Reading https://pypi.python.org/simple/service_factory/
    Downloading https://pypi.python.org/packages/d1/32/bacd539bc748af613082f8cf80c82311373a05bb4af2d43bc2ff5bbdcdcc/service_factory-0.1.5.tar.gz#md5=a0dd7745280da2284e8bdc2c03b853e4
    Best match: service-factory 0.1.5
    Processing service_factory-0.1.5.tar.gz
    Writing /tmp/easy_install-59tbmcoj/service_factory-0.1.5/setup.cfg
    Running service_factory-0.1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-59tbmcoj/service_factory-0.1.5/egg-dist-tmp-tz_hj4p0
    creating /home/leiz/.emacs.d/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg
    Extracting service_factory-0.1.5-py3.6.egg to /home/leiz/.emacs.d/anaconda-mode/0.1.9
    Adding service-factory 0.1.5 to easy-install.pth file
    
    Installed /home/leiz/.emacs.d/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg
    Processing dependencies for service_factory>=0.1.5
    Finished processing dependencies for service_factory>=0.1.5
    Searching for jedi>=0.11
    Skipping development or system egg: jedi 0.10.2
    Reading https://pypi.python.org/simple/jedi/
    Downloading https://pypi.python.org/packages/08/8d/34b133dfa210b55e7efaa8b09c736a8f4383fcda0b6487fc43a1db3c7ee7/jedi-0.11.0.tar.gz#md5=a948c0903b03bf361c60742947f076a0
    Best match: jedi 0.11.0
    Processing jedi-0.11.0.tar.gz
    Writing /tmp/easy_install-orcw6_s8/jedi-0.11.0/setup.cfg
    Running jedi-0.11.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-orcw6_s8/jedi-0.11.0/egg-dist-tmp-xntsj6y_
    warning: no files found matching 'jedi/parser/python/grammar*.txt'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    zip_safe flag not set; analyzing archive contents...
    jedi.evaluate.compiled.__pycache__.mixed.cpython-36: module MAY be using inspect.getsourcefile
    jedi.evaluate.compiled.__pycache__.__init__.cpython-36: module references __file__
    jedi.evaluate.compiled.__pycache__.fake.cpython-36: module references __file__
    jedi.evaluate.__pycache__.pep0484.cpython-36: module references __file__
    jedi.evaluate.__pycache__.representation.cpython-36: module references __file__
    jedi.evaluate.__pycache__.sys_path.cpython-36: module references __file__
    jedi.__pycache__.__main__.cpython-36: module references __file__
    creating /home/leiz/.emacs.d/anaconda-mode/0.1.9/jedi-0.11.0-py3.6.egg
    Extracting jedi-0.11.0-py3.6.egg to /home/leiz/.emacs.d/anaconda-mode/0.1.9
    Adding jedi 0.11.0 to easy-install.pth file
    
    Installed /home/leiz/.emacs.d/anaconda-mode/0.1.9/jedi-0.11.0-py3.6.egg
    Processing dependencies for jedi>=0.11
    Searching for parso==0.1.0
    Reading https://pypi.python.org/simple/parso/

It seems the process halted at reading parso.  I remember the 0.1.8 used the jedi installed on my `anaconda3` directory but now it downloads its own jedi from pypi. The following was the old `0.1.8` directory before removed./home/leiz/.emacs.d/anaconda-mode/
├── 0.1.8
│   ├── anaconda_mode-0.1.8-py3.6.egg
│   │   ├── anaconda_mode.py
│   │   ├── EGG-INFO
│   │   │   ├── dependency_links.txt
│   │   │   ├── not-zip-safe
│   │   │   ├── PKG-INFO
│   │   │   ├── requires.txt
│   │   │   ├── SOURCES.txt
│   │   │   └── top_level.txt
│   │   └── __pycache__
│   │       ├── anaconda_mode.cpython-35.pyc
│   │       └── anaconda_mode.cpython-36.pyc
│   ├── easy-install.pth
│   └── service_factory-0.1.5-py3.6.egg
│       ├── EGG-INFO
│       │   ├── dependency_links.txt
│       │   ├── not-zip-safe
│       │   ├── PKG-INFO
│       │   ├── SOURCES.txt
│       │   └── top_level.txt
│       └── service_factory
│           ├── compat.py
│           ├── errors.py
│           ├── exceptions.py
│           ├── factory.py
│           ├── __init__.py
│           ├── providers
│           │   ├── basehttp.py
│           │   ├── __init__.py
│           │   └── __pycache__
│           │       ├── basehttp.cpython-35.pyc
│           │       ├── basehttp.cpython-36.pyc
│           │       ├── __init__.cpython-35.pyc
│           │       └── __init__.cpython-36.pyc
│           ├── __pycache__
│           │   ├── compat.cpython-35.pyc
│           │   ├── compat.cpython-36.pyc
│           │   ├── errors.cpython-35.pyc
│           │   ├── errors.cpython-36.pyc
│           │   ├── exceptions.cpython-35.pyc
│           │   ├── exceptions.cpython-36.pyc
│           │   ├── factory.cpython-35.pyc
│           │   ├── factory.cpython-36.pyc
│           │   ├── __init__.cpython-35.pyc
│           │   ├── __init__.cpython-36.pyc
│           │   ├── service.cpython-35.pyc
│           │   ├── service.cpython-36.pyc
│           │   ├── validation.cpython-35.pyc
│           │   └── validation.cpython-36.pyc
│           ├── service.py
│           └── validation.py

    /home/leiz/.emacs.d/anaconda-mode/
    ├── 0.1.8
    │   ├── anaconda_mode-0.1.8-py3.6.egg
    │   │   ├── anaconda_mode.py
    │   │   ├── EGG-INFO
    │   │   │   ├── dependency_links.txt
    │   │   │   ├── not-zip-safe
    │   │   │   ├── PKG-INFO
    │   │   │   ├── requires.txt
    │   │   │   ├── SOURCES.txt
    │   │   │   └── top_level.txt
    │   │   └── __pycache__
    │   │       ├── anaconda_mode.cpython-35.pyc
    │   │       └── anaconda_mode.cpython-36.pyc
    │   ├── easy-install.pth
    │   └── service_factory-0.1.5-py3.6.egg
    │       ├── EGG-INFO
    │       │   ├── dependency_links.txt
    │       │   ├── not-zip-safe
    │       │   ├── PKG-INFO
    │       │   ├── SOURCES.txt
    │       │   └── top_level.txt
    │       └── service_factory
    │           ├── compat.py
    │           ├── errors.py
    │           ├── exceptions.py
    │           ├── factory.py
    │           ├── __init__.py
    │           ├── providers
    │           │   ├── basehttp.py
    │           │   ├── __init__.py
    │           │   └── __pycache__
    │           │       ├── basehttp.cpython-35.pyc
    │           │       ├── basehttp.cpython-36.pyc
    │           │       ├── __init__.cpython-35.pyc
    │           │       └── __init__.cpython-36.pyc
    │           ├── __pycache__
    │           │   ├── compat.cpython-35.pyc
    │           │   ├── compat.cpython-36.pyc
    │           │   ├── errors.cpython-35.pyc
    │           │   ├── errors.cpython-36.pyc
    │           │   ├── exceptions.cpython-35.pyc
    │           │   ├── exceptions.cpython-36.pyc
    │           │   ├── factory.cpython-35.pyc
    │           │   ├── factory.cpython-36.pyc
    │           │   ├── __init__.cpython-35.pyc
    │           │   ├── __init__.cpython-36.pyc
    │           │   ├── service.cpython-35.pyc
    │           │   ├── service.cpython-36.pyc
    │           │   ├── validation.cpython-35.pyc
    │           │   └── validation.cpython-36.pyc
    │           ├── service.py
    │           └── validation.py

Now it seems to me the 0.1.9 tries to download everything it needs into its own `~/.emacs.d/anaconda-mode/` directory

**Comment by proofit404** [comment]
> Now it seems to me the 0.1.9 tries to download everything it needs into its own `~/.emacs.d/anaconda-mode/` directory.

This is right behavior defined by anaconda-mode package design.

**Comment by proofit404** [comment]
This is my `easy_install.pth` content
```
./anaconda_mode-0.1.9-py3.6.egg
./service_factory-0.1.5-py3.6.egg
./jedi-0.11.0-py3.6.egg
./parso-0.1.0-py3.6.egg
```
This is tree output
```
.
├── anaconda_mode-0.1.9-py3.6.egg
│   ├── EGG-INFO
│   │   ├── PKG-INFO
│   │   ├── SOURCES.txt
│   │   ├── dependency_links.txt
│   │   ├── not-zip-safe
│   │   ├── requires.txt
│   │   └── top_level.txt
│   ├── __pycache__
│   │   └── anaconda_mode.cpython-36.pyc
│   └── anaconda_mode.py
├── easy-install.pth
├── jedi-0.11.0-py3.6.egg
│   ├── EGG-INFO
│   │   ├── PKG-INFO
│   │   ├── SOURCES.txt
│   │   ├── dependency_links.txt
│   │   ├── not-zip-safe
│   │   ├── requires.txt
│   │   └── top_level.txt
│   └── jedi
│       ├── __init__.py
│       ├── __main__.py
│       ├── __pycache__
│       │   ├── __init__.cpython-36.pyc
│       │   ├── __main__.cpython-36.pyc
│       │   ├── _compatibility.cpython-36.pyc
│       │   ├── cache.cpython-36.pyc
│       │   ├── common.cpython-36.pyc
│       │   ├── debug.cpython-36.pyc
│       │   ├── parser_utils.cpython-36.pyc
│       │   ├── refactoring.cpython-36.pyc
│       │   ├── settings.cpython-36.pyc
│       │   └── utils.cpython-36.pyc
│       ├── _compatibility.py
│       ├── api
│       │   ├── __init__.py
│       │   ├── __pycache__
│       │   │   ├── __init__.cpython-36.pyc
│       │   │   ├── classes.cpython-36.pyc
│       │   │   ├── completion.cpython-36.pyc
│       │   │   ├── helpers.cpython-36.pyc
│       │   │   ├── interpreter.cpython-36.pyc
│       │   │   ├── keywords.cpython-36.pyc
│       │   │   ├── replstartup.cpython-36.pyc
│       │   │   └── usages.cpython-36.pyc
│       │   ├── classes.py
│       │   ├── completion.py
│       │   ├── helpers.py
│       │   ├── interpreter.py
│       │   ├── keywords.py
│       │   ├── replstartup.py
│       │   └── usages.py
│       ├── cache.py
│       ├── common.py
│       ├── debug.py
│       ├── evaluate
│       │   ├── __init__.py
│       │   ├── __pycache__
│       │   │   ├── __init__.cpython-36.pyc
│       │   │   ├── analysis.cpython-36.pyc
│       │   │   ├── cache.cpython-36.pyc
│       │   │   ├── context.cpython-36.pyc
│       │   │   ├── docstrings.cpython-36.pyc
│       │   │   ├── dynamic.cpython-36.pyc
│       │   │   ├── filters.cpython-36.pyc
│       │   │   ├── finder.cpython-36.pyc
│       │   │   ├── flow_analysis.cpython-36.pyc
│       │   │   ├── helpers.cpython-36.pyc
│       │   │   ├── imports.cpython-36.pyc
│       │   │   ├── instance.cpython-36.pyc
│       │   │   ├── iterable.cpython-36.pyc
│       │   │   ├── jedi_typing.cpython-36.pyc
│       │   │   ├── param.cpython-36.pyc
│       │   │   ├── parser_cache.cpython-36.pyc
│       │   │   ├── pep0484.cpython-36.pyc
│       │   │   ├── precedence.cpython-36.pyc
│       │   │   ├── recursion.cpython-36.pyc
│       │   │   ├── representation.cpython-36.pyc
│       │   │   ├── site.cpython-36.pyc
│       │   │   ├── stdlib.cpython-36.pyc
│       │   │   └── sys_path.cpython-36.pyc
│       │   ├── analysis.py
│       │   ├── cache.py
│       │   ├── compiled
│       │   │   ├── __init__.py
│       │   │   ├── __pycache__
│       │   │   │   ├── __init__.cpython-36.pyc
│       │   │   │   ├── fake.cpython-36.pyc
│       │   │   │   ├── getattr_static.cpython-36.pyc
│       │   │   │   └── mixed.cpython-36.pyc
│       │   │   ├── fake
│       │   │   │   ├── _functools.pym
│       │   │   │   ├── _sqlite3.pym
│       │   │   │   ├── _sre.pym
│       │   │   │   ├── _weakref.pym
│       │   │   │   ├── builtins.pym
│       │   │   │   ├── datetime.pym
│       │   │   │   ├── io.pym
│       │   │   │   ├── operator.pym
│       │   │   │   └── posix.pym
│       │   │   ├── fake.py
│       │   │   ├── getattr_static.py
│       │   │   └── mixed.py
│       │   ├── context.py
│       │   ├── docstrings.py
│       │   ├── dynamic.py
│       │   ├── filters.py
│       │   ├── finder.py
│       │   ├── flow_analysis.py
│       │   ├── helpers.py
│       │   ├── imports.py
│       │   ├── instance.py
│       │   ├── iterable.py
│       │   ├── jedi_typing.py
│       │   ├── param.py
│       │   ├── parser_cache.py
│       │   ├── pep0484.py
│       │   ├── precedence.py
│       │   ├── recursion.py
│       │   ├── representation.py
│       │   ├── site.py
│       │   ├── stdlib.py
│       │   └── sys_path.py
│       ├── parser_utils.py
│       ├── refactoring.py
│       ├── settings.py
│       └── utils.py
├── parso-0.1.0-py3.6.egg
│   ├── EGG-INFO
│   │   ├── PKG-INFO
│   │   ├── SOURCES.txt
│   │   ├── dependency_links.txt
│   │   ├── not-zip-safe
│   │   └── top_level.txt
│   └── parso
│       ├── __init__.py
│       ├── __pycache__
│       │   ├── __init__.cpython-36.pyc
│       │   ├── _compatibility.cpython-36.pyc
│       │   ├── cache.cpython-36.pyc
│       │   ├── grammar.cpython-36.pyc
│       │   ├── normalizer.cpython-36.pyc
│       │   ├── parser.cpython-36.pyc
│       │   ├── tree.cpython-36.pyc
│       │   └── utils.cpython-36.pyc
│       ├── _compatibility.py
│       ├── cache.py
│       ├── grammar.py
│       ├── normalizer.py
│       ├── parser.py
│       ├── pgen2
│       │   ├── __init__.py
│       │   ├── __pycache__
│       │   │   ├── __init__.cpython-36.pyc
│       │   │   ├── grammar.cpython-36.pyc
│       │   │   ├── parse.cpython-36.pyc
│       │   │   └── pgen.cpython-36.pyc
│       │   ├── grammar.py
│       │   ├── parse.py
│       │   └── pgen.py
│       ├── python
│       │   ├── __init__.py
│       │   ├── __pycache__
│       │   │   ├── __init__.cpython-36.pyc
│       │   │   ├── diff.cpython-36.pyc
│       │   │   ├── errors.cpython-36.pyc
│       │   │   ├── fstring.cpython-36.pyc
│       │   │   ├── parser.cpython-36.pyc
│       │   │   ├── pep8.cpython-36.pyc
│       │   │   ├── prefix.cpython-36.pyc
│       │   │   ├── token.cpython-36.pyc
│       │   │   ├── tokenize.cpython-36.pyc
│       │   │   └── tree.cpython-36.pyc
│       │   ├── diff.py
│       │   ├── errors.py
│       │   ├── fstring.py
│       │   ├── grammar26.txt
│       │   ├── grammar27.txt
│       │   ├── grammar33.txt
│       │   ├── grammar34.txt
│       │   ├── grammar35.txt
│       │   ├── grammar36.txt
│       │   ├── parser.py
│       │   ├── pep8.py
│       │   ├── prefix.py
│       │   ├── token.py
│       │   ├── tokenize.py
│       │   └── tree.py
│       ├── tree.py
│       └── utils.py
└── service_factory-0.1.5-py3.6.egg
    ├── EGG-INFO
    │   ├── PKG-INFO
    │   ├── SOURCES.txt
    │   ├── dependency_links.txt
    │   ├── not-zip-safe
    │   └── top_level.txt
    └── service_factory
        ├── __init__.py
        ├── __pycache__
        │   ├── __init__.cpython-36.pyc
        │   ├── compat.cpython-36.pyc
        │   ├── errors.cpython-36.pyc
        │   ├── exceptions.cpython-36.pyc
        │   ├── factory.cpython-36.pyc
        │   ├── service.cpython-36.pyc
        │   └── validation.cpython-36.pyc
        ├── compat.py
        ├── errors.py
        ├── exceptions.py
        ├── factory.py
        ├── providers
        │   ├── __init__.py
        │   ├── __pycache__
        │   │   ├── __init__.cpython-36.pyc
        │   │   └── basehttp.cpython-36.pyc
        │   └── basehttp.py
        ├── service.py
        └── validation.py

28 directories, 192 files
```
You should have the same.

**Comment by LeeiFrankJaw** [comment]
Thanks for you prompt reply!

I solved my problem by removing the `~/.emacs.d/anaconda-mode/` directory and regenerate it.

**Comment by proofit404** [comment]
Glad you solve it.
