### ISSUE TITLE
Anaconda-mode stopped working after recent update

### ISSUE THREAD

**Issue by wizmer** [proofit404/anaconda-mode#263]
Sneakingly, anaconda-stopped working a few days ago (I don't know which in fact).

I solved the problem by redownloading the whole melpa package so I'm not sure what the problem was.

But I had:
the package NotFoundError not being found from anaconda_mode.py:
`from jedi import Script, NotFoundError`

because my Jedi version was still 0.10 instead of 0.11.

So I suspect an upgrade of the anaconda package that had not checked the version requirement of Jedi and forgot to update Jedi.

**Comment by proofit404** [comment]
Jedi version pinned by anaconda-mode requirements.

https://github.com/proofit404/anaconda-mode/commit/89fc16d50b889a17521084347b28f3011b84e113#diff-2eeaed663bd0d25b7e608891384b7298R21
