### ISSUE TITLE
Anaconda-mode shows constantly errors about virtualenvs

### ISSUE THREAD

**Issue by aizquier** [proofit404/anaconda-mode#264]
Using spacemacs, after opening any python file, a new buffer *anaconda-mode* appears repeating the message:

    /usr/bin/emacs24: /home/aizquier/.virtualenvs/source /usr/local/bin/virtualenvwrapper.sh/bin/python: No such file or directory

besides, the minibuffer shows constantly:

    Can not create ~/.emacs.d/.cache/anaconda-mode/0.1.9 directory

What could be the source of these problems? Thanks!

**Comment by proofit404** [comment]
Hi, can you please show me a result of the following command:
```
M-: python-shell-interpreter RET
```

**Comment by aizquier** [comment]
Hi, yes, of course!.

It says :   [No Match] 
helm shows me many matches of `python-shell-*` but `python-shell-interpreter` is not listed. Notice also that the directory  /home/aizquier/.virtualenvs/ does not exist in my system, and besides the in string "/usr/local/bin/virtualenvwrapper.sh/bin/python" there is *not* a whitespace separating "virtualenvwrapper.sh" and "/bin/python".

Hope this could help!

**Comment by proofit404** [comment]
You should create virtual env before you can use it with anaconda-mode. Fill free to continue this discussion if you need further assessment. Closing since the is no actual issue.

**Comment by proofit404** [comment]
Maybe I close wrong issue.

**Comment by aizquier** [comment]
HI!
I have indeed many virtual envs. However I don't use a ~/.virtualenvs directory, I use a ~/VirtualEnvs directory instead. How can this be configured on anaconda-mode? What if I don't want to use virtualenvs at all?   
Thanks!

**Comment by proofit404** [comment]
You should point anaconda-mode to exactly one virtual environment. For example with interactive command `pythonic-activate`. If you don't want to use virtual env at all, anaconda-mode will complete from packages installed into global python with apt-get or sudo pip.

Hope this helps, closing now.

**Comment by suyashbire1** [comment]
I have this same issue if I try to use a remote virtualenv. I followed the steps in the readme to activate the virtualenv.

I get the following error in the `*anaconda-mode*` buffer (even though the virtualenv exists): 
```
/Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_9: /home/sbire/.bin/miniconda3/envs/myenv/bin/python: No such file or directory
```

And the minibuffer shows:
```
Can not create ~/.emacs.d/anaconda-mode/0.1.9 directory
```

**Comment by avli** [comment]
I got the same error when trying to switch on an environment created with pipenv. Everything is fine with virtualens created manually though.

**Comment by proofit404** [comment]
I think this happens when environment settings changed. Anaconda mode has problems with restart.

**Comment by avli** [comment]
@proofit404 Not sure I understand. Could you elaborate which settings do you mean?

**Comment by proofit404** [comment]
Do set one virtual environment with pythonic-activate, work some time, and then use another virtual environment with pythonic-activate. Right after that directory access error can happen.

**Comment by avli** [comment]
Got it! Thanks!
