### ISSUE TITLE
Virtual environments on Windows

### ISSUE THREAD

**Issue by ssefick** [proofit404/anaconda-mode#265]
I am using anaconda3 (version 4.3.8). I need to work on a project that is written in python 2.7. I am working on windows 7.

I am having problems setting up virtual environments:

I have set 
(setq python-shell-virtualenv-path "C:/ProgramData/Anaconda3/envs")

When I start the interpreter it does not start 2.7. I have tried using pyenv and pyenv-mode. Neither of these work.

relevant .emacs snippett:

;;python setup
;;anaconda mode set up
(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)

;;virtual environments
(setq python-shell-virtualenv-path "C:/ProgramData/Anaconda3/envs")

;;dosn't work
;;pyenv-mode
;;(pyenv-mode)

;;doesn't work...
;;pyenv
;;(setenv "WORKON_HOME" "C:/ProgramData/Anaconda3/envs")
;;(pyvenv-mode 1)

**Comment by proofit404** [comment]
Hi, I don't think that "C:/ProgramData/Anaconda3/envs" is your actual virtual env path. How about "C:/ProgramData/Anaconda3/envs/<your_project_env>"?

**Comment by ssefick** [comment]
I included your edit in my .emacs. This does not seem to work, and I am receiving a 'Can not install 'anaconda-mode' server.

And if I start python from the menu, I get a python 3 shell. 

Any help would be greatly appreciated.

**Comment by ssefick** [comment]
Update; a kludge I have found is to add the python that I want to the PATH with:

;;python
(add-to-list 'exec-path "C:/ProgramData/Anaconda3/envs/what_ever_the_path_is")

**Comment by proofit404** [comment]
Can you post `*anaconda-mode*` buffer log here?

**Comment by ssefick** [comment]
Sure; how do I do that, and under what settings (with pyenv and with my kludge or something else )? I am newish to emacs, and want to make sure that I post the most helpful text.

**Comment by proofit404** [comment]
`pyenv-mode` is a helper mode for using [pyenv](https://github.com/pyenv/pyenv). It's written in bash, so you don't use it actually.

Try to activate your virtual environment with `M-x pythonic-activate RET`

**Comment by ssefick** [comment]
Please let me know if you need anything else.

Setting interpreter explicilty
#################################################
Warning (python): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with ‘keyboard-quit’ and then try fixing the
interactive flag for your interpreter by adjusting the
‘python-shell-interpreter-interactive-arg’ or add regexps
matching shell prompts in the directory-local friendly vars:
  + ‘python-shell-prompt-regexp’
  + ‘python-shell-prompt-block-regexp’
  + ‘python-shell-prompt-output-regexp’
Or alternatively in:
  + ‘python-shell-prompt-input-regexps’
  + ‘python-shell-prompt-output-regexps’
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native-enable’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 

;;python setup
;;anaconda mode set up
(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)

;;virtual environments
;;(setq python-shell-virtualenv-path "C:/ProgramData/Anaconda3/envs/")

(setq python-shell-interpreter "C:/ProgramData/Anaconda3/envs/sped/python")

;;python
(require 'python)
(require 'eval-in-repl-python)
(add-hook 'python-mode-hook
         '(lambda ()
            (local-set-key (kbd "<C-return>") 'eir-eval-in-python)))
################################################################

without kludge
################################################################
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native-enable’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 

and

Loading c:/Users/sas0339/.emacs.d/elisp/cobalt.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
test.py has auto save data; consider M-x recover-this-file
Can’t guess python-indent-offset, using defaults: 4
Shell native completion is disabled, using fallback
previous-line: Beginning of buffer
Mark set
next-line: End of buffer
eldoc error: (file-error Spawning child process Invalid argument)
Mark set

;;python setup
;;anaconda mode set up
(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)

;;virtual environments
;;(setq python-shell-virtualenv-path "C:/ProgramData/Anaconda3/envs/")

;;(setq python-shell-interpreter "C:/ProgramData/Anaconda3/envs/sped/python")

;;python
(require 'python)
(require 'eval-in-repl-python)
(add-hook 'python-mode-hook
         '(lambda ()
            (local-set-key (kbd "<C-return>") 'eir-eval-in-python)))

;;set virt env
;;(add-to-list 'exec-path "C:/ProgramData/Anaconda3/envs/sped")

################################################################

**Comment by ssefick** [comment]
This still is not working. I have found a work around using python-mode, but I am still interested if anyone has any other ideas?

**Comment by kouvas** [comment]
@ssefick How did you get it working with python mode? I have the same issue.
When i select my anaconda env and press enter i get 
>Searching for program: No such file or directory, python

**Comment by ssefick** [comment]
I use a workaround by setting the path explicitly to the python executable
in the virtual environment bin directory. I can supply the relevant
snippets tomorrow if you like.

kindest regards,

Stephen Sefick, PhD

Let's not spend our time and resources thinking about things that are so
little or so large that all they really do for us is puff us up and make us
feel like gods.  We are mammals, and have not exhausted the annoying little
problems of being mammals.

                                -K. Mullis

"A big computer, a complex algorithm and a long time does not equal
science."

                              -Robert Gentleman

**Comment by fleimgruber** [comment]
I am seeing
```
eldoc error: (file-error Spawning child process Invalid argument)
```
as well.  @proofit404 What would be the best place to edebug into the machinery in anaconda-mode?  I would really like to see the place this breaks to find a fix.

**Comment by proofit404** [comment]
First of all, remove all elc files from your elpa directory to see clean trace back.

**Comment by fleimgruber** [comment]
I removed all elc files but still don't get a traceback?

**Comment by proofit404** [comment]
Please, try to evaluate this form before reproducing the error:

```lisp
(setq debug-on-error t)
```

**Comment by fleimgruber** [comment]
I have this enabled by default, but still no traceback.  I can generate tracebacks fine otherwise, e.g. evaluating `(asdf)`.  This is why I wanted to use the edebug approach.

**Comment by fleimgruber** [comment]
I did an experiment on a non-Windows machine where this is working.  I found that when I deliberately mess up the `python-shell-interpreter` in a .dir-locals.el then completion still works, but `run-python` fails as expected.  I take this as an indication that the anaconda-mode completion machinery is working with the pyvenv context and does not bother with `python-shell-interpreter`.  If that is correct, the next step would be to look into the pyvenv integration code.

```
((python-mode
  (eval . (pyvenv-activate "/Users/user/opt/miniconda3/envs/env"))
  (eval . (setq python-shell-interpreter "/Users/user/opt/miniconda3/envs/env/bin/pythonn"))))
```

**Comment by proofit404** [comment]
`python-shell-interpreter` is taken into consideration, but only if `python-shell-virtualenv-root` is `nil`. On windows python executable must have `env\\Scripts\\pythonw.exe` and `env/bin/python` on unix-like systems.

**Comment by fleimgruber** [comment]
Ah, good to know.  Now I think there is the root of the issue.  The type of virtual environment I and @ssefick use (inferred from paths in OP) are Conda environments (see also [here](https://conda.io/docs/)).  Their folder structure does not follow the usual virtual environment convention, i.e. they do not use `env\\Scripts\\python.exe` but use `env\\python.exe` and `env/python.exe` on unix-like systems instead.  Before switching to anaconda-mode, I used `pyvenv-activate` successfully with Conda environments.  As the switch to anaconda-mode was due to using Spacemacs, I looked for solutions there but only found tips on doing this on Linux, see e.g. [here](https://emacs.stackexchange.com/questions/32103/spacemacs-use-anaconda-environment).  After a fresh investigation with your input, I actually just found https://github.com/necaris/conda.el which might take care of this.

**Comment by proofit404** [comment]
Why not just specify the full path to the python executable?

You can look into `pythonic` package used by anaconda-mode.

**Comment by fleimgruber** [comment]
Hm, as I said in https://github.com/proofit404/anaconda-mode/issues/265#issuecomment-355833661, `run-python` works, so I do specify the full path to the python executable (via `python-shell-interpreter`) in the .dir-locals.el file and it is found.  Completion still fails with the mentioned
```
eldoc error: (file-error Spawning child process Invalid argument)
```
and
```
Spawning child process Invalid argument
```

I will look into the pythonic package.  But I would really like to pin down the point where the external command for completion is called by anaconda-mode and see whether there is some weird Windows-related stuff happening there.

**Comment by fleimgruber** [comment]
I found the place where things go awry for my setup in https://github.com/proofit404/pythonic/blob/master/pythonic.el#L69 where the `pythonic-executable` gets set incorrectly because `pythonic-environment` is set - as you described in https://github.com/proofit404/anaconda-mode/issues/265#issuecomment-355851891.

**Comment by fleimgruber** [comment]
I tried to remove virtual environment related config from my .dir-locals.el and now I get this in `*anaconda-mode*`
```
anaconda_mode port 53403
```
and this in `*anaconda-response*`
```
# status: (:error (error connection-failed deleted
 :host 127.0.0.1 :service 53403) :error (error connection-failed failed with code 10061
 :host 127.0.0.1 :service 53403))
# point: 1
```
I found #164 and followed the advice to set
```
(setq url-proxy-services '(("no_proxy" . "\\(localhost\\)")))
```
and it works now although it is a bit flaky, meaning I often get
```
Server error: ValueError('not enough values to unpack (expected 1, got 0)',)
Can not read anaconda-mode server response [2 times]
```

**Comment by fleimgruber** [comment]
Offtopic: I would really like to star this project, but something holds me back because the star counter is at 404 stars ;-)

**Comment by proofit404** [comment]
Looks like a jedi bug.

**Comment by fleimgruber** [comment]
Correct.  Turned out that the jedi 0.10 code was still being used, my bad.  Seems to work now.  Thanks @proofit404 for the patience and support!  @ssefick I think in the end we used the same fix, i.e. setting `python-shell-interpreter` directly and without any other env related config?  Do you agree that this issue can be closed then?

**Comment by prismv** [comment]
Based on hint by @proofit404 I found a solution. Still a workaround, but working (for me) with current standard Anaconda environments: Create symbolic links of %env%\python.exe and %env%\pythonw.exe in %env%\Scripts.
This is possible with mklink or e.g. 'Link Shell Extension'.

**Comment by fleimgruber** [comment]
@prismv nice one, thanks.  Works over here as well.

**Comment by proofit404** [comment]
Recent anaconda-mode depends completely on python.el to handle interpreter path.
