### ISSUE TITLE
How to verify anaconda-mode installation?

### ISSUE THREAD

**Issue by biocyberman** [proofit404/anaconda-mode#266]
I reported an issue over here: https://github.com/syl20bnr/spacemacs/issues/9777
I also ran:
`sudo -H pip install  jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2`

However, code navigation still doesn't work. 

### content of \*anaconda_mode\*: ###
Empty, no text appears there.

### Content of anaconda_mode directory ### 
```
 anaconda-mode-20170924.704: 
anaconda-mode-autoloads.el
anaconda-mode.el
anaconda-mode.elc
anaconda-mode-pkg.el
```
It seems that some files are missing

**Comment by proofit404** [comment]
Hi, You shouldn't install anaconda-mode dependencies globally. Anaconda-mode will handle it for you.

You should have `~/.emacs.d/anaconda-mode/0.1.9` with all dependencies installed by anaconda-mode. Spacemacs can override this location as well.

Please describe your project setup, so I can suggest possible solution for autocompletion fix. Missed dependencies is not an issue here.
