### ISSUE TITLE
anaconda-mode binding are inconsistent with xref

### ISSUE THREAD

**Issue by darkfeline** [proofit404/anaconda-mode#267]
anaconda-mode uses these bindings:

Keybinding | Description
-- | --
C-M-i | anaconda-mode-complete
M-. | anaconda-mode-find-definitions
M-, | anaconda-mode-find-assignments
M-r | anaconda-mode-find-references
M-* | anaconda-mode-go-back
M-? | anaconda-mode-show-doc

Emacs's built-in xref uses these bindings:

Keybinding | Description
-- | --
C-M-i | completion-at-point
M-. | xref-find-definitions
M-, | xref-pop-marker-stack
M-? | xref-find-references

**Comment by proofit404** [comment]
Hi, thanks for the report.

Anaconda-mode was developed way earlier xref. Personally, I like `M-,` and `M-*` a lot.

If you're interested in it, you can contribute xref support as an option, so it will have consistent key bindings automatically.
