### ISSUE TITLE
Add an C-u option to be able to find-definitions with prompt  

### ISSUE THREAD

**Issue by vspinu** [proofit404/anaconda-mode#268]
I often want to navigate to a definition of an object which is not under the cursor, in fact it might not be anywhere in a file. Would it be possible to add an C-u modifier to `anaconda-mode-find-definitions` in order to allow explicitly typed var names? 

Same option would be useful for other commands like `anaconda-mode-show-doc`.

Thanks!

**Comment by proofit404** [comment]
Hi @vspinu

It's an interesting option to have. Can you verbosity describe user interface for this feature? Especially for definitions not mentioned in current buffer.

Regards, Artem.

**Comment by vspinu** [comment]
I would like to see a C-u argument to anaconda-mode-find-definitions. So, when I do `C-u M-.` a minibuffer prompt would ask for symbol to navigate to (ideally with anaconda completion). 

This is roughly how `xref-find-definitions` behaves btw:

> "Find the definition of the identifier at point. With prefix argument or when there's no identifier at point, prompt for it.

Currently anaconda would not prompt for symbol when where is no suitable symbol at point.

Would be also great to see a global variable which would toggle the C-u behavior. Say `anaconda-mode-auto-jump`, which when set to `t` makes `anaconda-mode-find-definitions` and other function behave as they do right now, jump to the definitions with no query, when set to `nil` it would ask for symbol in the minibuffer with the symbol at point as the default. This variable should also reverse the meaning of C-u switch.  

Thank you for considering this!

**Comment by proofit404** [comment]
I don't think we can do this with jedi library.

**Comment by proofit404** [comment]
Maybe ggtags + gnu global + pygments parser.
