### ISSUE TITLE
M-? show wrong doc

### ISSUE THREAD

**Issue by cnglen** [proofit404/anaconda-mode#270]
import tensorflow as tf
tf.strided_slice   <---------------- M-? here

It shows doc of strided_slice defined in **tensorflow/python/ops/gen_array_ops.py,** 
NOT **tensorflow/python/ops/array_ops.py**

Any ideas?

**Comment by proofit404** [comment]
Please, report this bug to the `jedi` library. Source code analysis is performed in it.
