### ISSUE TITLE
ipython in virtual environment doesn't work

### ISSUE THREAD

**Issue by agreselin** [proofit404/anaconda-mode#271]
Hello. I've set up a virtual environment with `venv` and installed Ipython there via `pip`. On the terminal it works.
Now, in my `init.el`, I have
```
(setq python-shell-interpreter "ipython")

(defun my-python-mode-setup ()
  (anaconda-mode)
  (anaconda-eldoc-mode)
  (setq-local company-backends
              (append '((company-anaconda)) company-backends)))

(add-hook 'python-mode-hook 'my-python-mode-setup)
```
When I run Python after having `pythonic-activate`d my virtual environment I get the following messages
```
Making python-shell-interpreter local to *Python* while let-bound!
Making python-shell-interpreter-args local to *Python* while let-bound!
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
```
And the console looks like this (with escape characters instead of the question mark symbols that appear here on github):
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

[79C=
[79Ce
[79CF
   ...: 2''', 'exec'));[23D
[J[?7h[?12l[?25h[?2004l
[79C=
[79Ce
[79CP
   ...: F''', 'exec'));[23D
[79C=
[79Ce
[79CP
   ...: F''', 'exec'));[23D
[J[?7h[?12l[?25h[?2004l
[?1l[6n[?2004h[?25l[?7l[JIn [3]: [8D[8C[?7h[?12l[?25h
```
If I run python from outside the virtual environment, Ipython launches and works flawlessly, but in that case it uses python2.7.

Emacs is v24.5.1, on Ubuntu 16.04. All packages are at the latest version from the Gnu repository, or from Melpa if only available there (anaconda-mode is 20171223.1118).
I'm not an expert, please forgive me if I've made a trivial mistake.

---
I've tried without the hook, so without launching `anaconda-mode`, and I still have this problem. It looks it's not `anaconda-mode` causing it then, maybe `python-mode` or `pythonic`. I thought I was `anaconda-mode`'s fault because I couldn't use virtual environments before, then by installing `anaconda-mode` I got virtual environments and the strange behaviour.

If you know how to fix it, please tell me before closing this issue.

**Comment by toku-jin** [comment]
Solved [here](https://emacs.stackexchange.com/questions/37867/ipython-doesnt-work-in-a-virtual-environment). The problem was not caused by`anaconda-mode`. From IPython's [documentation](https://ipython.readthedocs.io/en/stable/whatsnew/version5.html#id1)
===
The new [v5] interface is not compatible with Emacs ‘inferior-shell’ feature. To continue using this, add the --simple-prompt flag to the command Emacs runs. This flag disables most IPython features, relying on Emacs to provide things like tab completion.
===
With these set-up IPython runs correctly:
```
(setq python-shell-interpreter "ipython")
(setq python-shell-interpreter-args "--simple-prompt --pprint -i")
```

**Comment by proofit404** [comment]
Thanks for feed back with your solution.

**Comment by proofit404** [comment]
Recent anaconda-mode depends completely on python.el to handle interpreter path and args.
