### ISSUE TITLE
Do I need to install anaconda_mode globally?

### ISSUE THREAD

**Issue by ReimuXMX** [proofit404/anaconda-mode#272]
Hello:

Do I need to globally install some python packages like this?
```
sudo pip3 install anaconda_mode anaconda-client jedi
```
I am a python rookie. If the problem is stupid, I'm sorry.

Thank you.

**Comment by proofit404** [comment]
Hi, you don't need to install it at all. Emacs mode will take care of python installation itself automatically.

**Comment by ReimuXMX** [comment]
Thanks.

In other words, I just make sure there are `pypi `and `setuptools` on the line?

**Comment by proofit404** [comment]
Yes, that's all you need.
