### ISSUE TITLE
Cannot install anaconda server using ipython

### ISSUE THREAD

**Issue by tigersoldier** [proofit404/anaconda-mode#273]
Spacemacs sets `python-shell-interpreter` to ipython by default. Invoking `anaconda-mode-install` results in the following error in `*anaconda-mode*` buffer:

```
  File "<ipython-input-1-451c6f6f942e>", line 1
    import
          ^
SyntaxError: invalid syntax
```

My ipython version is 5.1.0

**Comment by proofit404** [comment]
Please, Retry with 0.1.12. Installation logic was reimplemented.
