### ISSUE TITLE
Finding references and assignments open new buffer instead of working on current buffer

### ISSUE THREAD

**Issue by piojanu** [proofit404/anaconda-mode#274]
Hi!

First of all, I switched from elpy to anaconda-mode and it's great. It works out of the box and feels really smoothly, great job!

Buy of course nothing is ideal :D I noticed that when I use find-assignments/find-references and there is more then one candidate, it opens new buffer. Great, I can choose which one I want! But the problem is, candidates it shows doesn't say much. E.g. it look like this:
```
main
    l_obs = self._obs_preprocessor(l_obs)
    l_obs
    l_obs
```
When I hover above any option it doesn't change current buffer (it could show location of this candidate). What's more when I hit enter, it opens candidate location in this new buffer instead of showing it in buffer I came from and closing new one. Is it supposed to work like this? It's not really convenient.

I use [ivy](https://github.com/abo-abo/swiper), is there some way to integrate them? It would be amazing!

`*anaconda-mode*` buffer show only "anaconda_mode port 61733".

I look forward for your response!

**Comment by proofit404** [comment]
Hi,

Thanks for giving `anaconda-mode` a try!

I agree that `*Anaconda*` buffer isn't convenient in some cases. It was written a long time ago. I have some plans to replace it with modern `xref` integration, but I can't commit to any deadlines. Currently, I'm focused on another [Emacs package to work with Django](https://github.com/proofit404/djangonaut). Maybe after that, I'll return to the `anaconda-mode`.

I use `ivy` myself and I can say there is a huge room to improve this integration. Someday I'll get to it. But not now.

Seeing port message in the anaconda-mode buffer means anaconda-mode is fully functional and operates correctly.

Regards, Artem.

**Comment by piojanu** [comment]
Ok :) I humbly think of working on that integration myself. It would be my first contribution to open source project and first code written in elisp other then emacs config. But sadly, I will have some time only in summer :( We will see.
For now, is there a way to make this buffer open below current buffer like on screenshot in README (in my emacs it opens side-by-side) and make it close after I hit RET? It would be good enough for now :D

Pozdrawiam,
Piotr Januszewski

**Comment by proofit404** [comment]
This screenshot was a result of small emacs frame size.

Windows configuration in emacs is really configurable. There is also nice projects like [popwin](https://github.com/m2ym/popwin-el).

**Comment by piojanu** [comment]
Thank you! That will do fine :)

Pozdrawiam,
Piotr Januszewski
