### ISSUE TITLE
Send Statement

### ISSUE THREAD

**Issue by kevinjfoley** [proofit404/anaconda-mode#276]
Is there a function similar to `elpy`'s [`elpy-shell-send-statement-and-step`](https://github.com/jorgenschaefer/elpy/blob/d89cbca0c06079e0128b8cd7b74b03c94b6a6cb2/elpy-shell.el#L763)?

If not is there any reason something similar couldn't/wouldn't be implemented in `anaconda-mode`?  It's something I'd be willing to at least try my hand at as long as there's not some limitation that I should be aware of.

**Comment by proofit404** [comment]
Hi,

Anaconda mode does not provide any python shell interaction commands.

Regards, Artem.
