### ISSUE TITLE
how to get plots executed remotely show on your local client?

### ISSUE THREAD

**Issue by kirk86** [proofit404/anaconda-mode#277]
Hi and thank your for this amazing package. I was wondering if it's possible to get code executed on a remote host that produces some plots to be shown in the local client, eventually think of it something like persistent X11 session.

Minimal working exaple:
```
import numpy as np
import matplotlib.pyplot as plt

x = np.zeros((100, 100, 3))
plt.imshow(x)
plt.show()
```

For instance if I ssh in to remote host with `-X` flag and execute the code the plot will be shown in my local client/pc. 

How can I achieve the same results using `tramp` and `anaconda-mode`?
Any suggestions or hints?

Thank you in advance!

**Comment by kirk86** [comment]
I've tried using the following from the tramp wiki:

First attempt:

```
(add-to-list 'tramp-remote-process-environment
             (format "DISPLAY=%s" (getenv "DISPLAY")))
```

The error that I get is:

```
QXcbConnection: Could not connect to display /private/tmp/com.apple.launchd.SC2ebcf21k/org.macosforge.xquartz:0
```

Second attempt setting X11 forward in ssh config:
```
QXcbConnection: Could not connect to display /private/tmp/com.apple.launchd.SC2ebcf21k/org.macosforge.xquartz:0
```

Again the error persists. Is there another way to pass a flag similar to `-X` in tramp when you do `C-x C-f`?

**Comment by proofit404** [comment]
Hi,

`anaconda-mode` does not offer code execution at all. Neither on a local or remote host. It's all about auto-completion and reference search.

I suggest you try other packages like [ein](https://melpa.org/#/ein) or [ob-ipython](https://melpa.org/#/ob-ipython). 

Regards, Artem.
