### ISSUE TITLE
*anaconda-mode* completion give wrong candidates about python class "multiprocessing"

### ISSUE THREAD

**Issue by RtrauqOn** [proofit404/anaconda-mode#278]
hi! anaconda-mode is good and works really smoothly

but a problem is, candidates have wrong option when use class multiprocessing. it look like:
```python
foo = multiprocessing. 
                    queues <module queues>
                    process <module process>
                    ...

```
it should be module Queue, Process and so on.
and some module not in candidates like: Lock()  Connection().
only find in class multiprocessing, other class like threading works well.

If you know how to fix it, please tell me.

**Comment by proofit404** [comment]
Hi, unfortunately, there is nothing I can do about it.

The problem lays in the way multiprocessing is written. As you can see it patch itself in the import time and random context methods into module namespace...

```python
from . import context

globals().update((name, getattr(context._default_context, name)) for name in context._default_context.__all__)

__all__ = context._default_context.__all__
```

**Comment by RtrauqOn** [comment]
sad news
Anyway thank you for telling me that!
