### ISSUE TITLE
socat mode does not work on MacOSX

### ISSUE THREAD

**Issue by mahmoudimus** [proofit404/anaconda-mode#280]
Like the title says, the `socat` approach does not work for me on MacOSX. 

In particular, [this piece of code](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L386-L391) will execute a command:  `/usr/local/bin/socat TCP4-LISTEN:42077 TCP4:172.20.0.3:42077`. This does not work for me. I get these error messages in:

- `*anaconda-socat*`:
   > `Process anaconda-socat exited abnormally with code 1`

- `*anaconda-response*`:

   > ```
   > # status: (:error (error connection-failed deleted
   > :host 127.0.0.1 :service 42077) :error (error connection-failed failed with code 22
   >:host 127.0.0.1 :service 42077))
   ># point: 1
   >```

I had to use:

```
socat TCP-LISTEN:42077,reuseaddr,fork \
          'EXEC:docker-compose exec -T app "socat STDIO TCP-CONNECT:localhost:42077"'
```

This will spin up another `socat` on the docker host and redirect the i/o to the python script running on the docker instance.

Fwiw, I added this nice little hook in my `.dir-locals.el`, maybe it could be helpful.

```lisp
(defun should-run-docker-compose ()
  "Determines if docker-compose should be used."
  (and (file-exists-p  "docker-compose.yml")
       (executable-find "docker")
       (executable-find "docker-compose")))

((nil . ((cond (should-run-docker-compose)
           (setq python-shell-interpreter
                 (format "/docker:root@auto-bot:%s"
                         (s-trim
                          (docker-compose "exec" "-T" "app" "which" "python"))))))))

```

**Comment by mahmoudimus** [comment]
I did a little bit more digging today and I think the issue is with using this on Mac OSX. Basically, the networking bridge mode via Docker for Mac does not work. We might have to do a little bit of checking on the bit of code there.

I'm going to try it with VMWare Workstation to see if it works.

**Comment by mahmoudimus** [comment]
Ok, I figured out the issue. It has nothing to do with `anaconda-mode` - if it helps others, I did the following:

1) Install either:
  - https://github.com/mal/docker-for-mac-host-bridge (my preferred one)
  - https://github.com/AlmirKadric-Published/docker-tuntap-osx
  - https://github.com/zanaca/docker-dns
2) If you're using `docker-compose`, then put this in your `docker-compose`:

```yml
networks:
  default:
    external:
      name: tap  # or whatever you name your network
```

Should work fine :)

**Comment by jjinking** [comment]
I was wrestling with this for a few hrs, but I finally figured out that for some reason, the python version that anaconda-mode was using doesn't correspond to what was set as my global python version, even though my `pyenv global` output was showing the same version.

Running `pyenv global 3.6.1` (which is the 3.6 version on my machine), and then running
`pip2 install --upgrade "jedi>=0.9.0" "json-rpc>=1.8.1" "service_factory>=0.1.5"` and restarting spacemacs solved the problem for me.

**Comment by cjauvin** [comment]
I'm trying to run inside docker using version `melpa-20190111.1524` on OSX and I'm getting this socat error:

```
2019/04/30 11:45:58 socat[82529] E connect(5, LEN=16 AF=2 172.19.0.4:38181, 16): Operation timed out

Process anaconda-socat exited abnormally with code 1
```

Is there something I can do, or the conclusion is that it simply doesn't work on OSX?

**Comment by proofit404** [comment]
Hi @cjauvin

Tell me more about the way you activate virtual environment. 

Preferably in the fresh new issue.

Thanks, have a good day.
