### ISSUE TITLE
Set python-shell-interpret to /usr/bin/python2 still finds python3

### ISSUE THREAD

**Issue by introom** [proofit404/anaconda-mode#289]
Suspect it's an regression as I haven't met this before.

**Comment by proofit404** [comment]
Hi, do you have a fully reproducible example? I mean something `emacs -Q -l reproducible_config.el`.

**Comment by proofit404** [comment]
Please, Retry with 0.1.12. Installation logic was reimplemented.

**Comment by millennium-falcon42** [comment]
updated to the lastest, maple stable. 

now with /usr/bin/python2, "import os" finds nothing.

with /usr/bin/python3, "import os" correctly finds the python3's os module.

**Comment by proofit404** [comment]
Recent anaconda-mode depends completely on python.el in this part now.
