### ISSUE TITLE
anaconda-mode-host: Symbol’s function definition is void: pythonic-remote-docker-p

### ISSUE THREAD

**Issue by etam** [proofit404/anaconda-mode#290]
Packages installed from melpa stable:
- anaconda-mode: 0.1.11
- pythonic: 0.1.0

anaconda-mode uses pythonic-remote-docker-p function, but it was introduced in pythonic after 0.1.0 release.

**Comment by proofit404** [comment]
Yeh, it was...

**Comment by proofit404** [comment]
I've pushed pythonic 0.1.1.
