### ISSUE TITLE
No more ac-anaconda

### ISSUE THREAD

**Issue by p3r7** [proofit404/anaconda-mode#302]
I used to use this mode with autocomplete, using package ac-anaconda.

The repo for ac-anaconda is missing: https://github.com/proofit404/ac-anaconda

Did you drop support for autocomplete or did it get merged in the main anaconda-mode source?

**Comment by proofit404** [comment]
Hi, ac-anaconda was broken for last two years.

I decide to abandon this package.

I have no plans to support auto-complete-mode any more.

Sorry if you're affected by this change. Please, give company-mode a try.
