### ISSUE TITLE
Automatically forward ssh port not just for Vagrant

### ISSUE THREAD

**Issue by valignatev** [proofit404/anaconda-mode#305]
Hi! I've started to experiment with anaconda-mode and remote development server. Looks really promising!
What am I missing is automatic port forwarding when I start anaconda-mode on a remote server via ssh. Not in vagrant or docker, but just on remote ssh host. Now I have to manually run ssh with `-L` flag. By looking at the code, I've noticed that you already do this automatically for vagrant boxes: 
https://github.com/proofit404/anaconda-mode/blob/a4b9b8f97fe39cce076c2192b84a1b14de1c5c40/anaconda-mode.el#L361-L369

What do you think about the same automatization for plain ssh connection? If you think it's a valuable improvement, I might try to create a PR.

**Comment by proofit404** [comment]
Hi, I think we should do it.

I think this way we can make `anaconda-mode-host` a constant.

Please, submit PR!

**Comment by valignatev** [comment]
This can be closed now, works after merging #319
