### ISSUE TITLE
Incompatibility between anaconda-mode and pythonic

### ISSUE THREAD

**Issue by mrroman** [proofit404/anaconda-mode#312]
There is incompatibility between latest version of anaconda-mode (either stable or unstable) and latest version of pythonic (either stable or unstable). Anaconda-mode uses pythonic-environment variable and it was removed in the latest stable pythonic version. It breaks anaconda.

**Comment by proofit404** [comment]
Hi,

There is no `pythonic-environment` in master branch.

Please, check your build.

Regards, Artem.
