### ISSUE TITLE
getaddrinfo error 11001 on remote files via tramp

### ISSUE THREAD

**Issue by gongliyu** [proofit404/anaconda-mode#313]
Hi, I just get anaconda-mode updated from melpa, but it fails on remote file via tramp. Before I update, everything works fine for remote files.  

I tried to update all python packages on remote machine, but the problem still exists.

Any hints?

Thanks,
Liyu

Local system: Windows 10
emacs version: 26.1
Remote system: CentOS Linux release 7.4.1708 (Core)

Error msg:
Debugger entered--Lisp error: (error "holly/40848 getaddrinfo error 11001")
  make-network-process(:name "holly" :buffer #<buffer  *url-http-temp*> :host "holly" :service 40848 :nowait (:nowait t) :tls-parameters nil)
  open-network-stream("holly" #<buffer  *url-http-temp*> "holly" 40848 :type plain :nowait (:nowait t))
  url-open-stream("holly" #<buffer  *url-http-temp*> "holly" 40848 nil)
  url-http-find-free-connection("holly" 40848 nil)
  url-http(#s(url :type "http" :user nil :password nil :host "holly" :portspec 40848 :filename "" :target nil :attributes nil :fullness t :silent t :use-cookies t :asynchronous t) #f(compiled-function (status) #<bytecode 0x299b879>) (nil))
  url-retrieve-internal("http://holly:40848" #f(compiled-function (status) #<bytecode 0x299b879>) (nil) t nil)
  url-retrieve("http://holly:40848" #f(compiled-function (status) #<bytecode 0x299b879>) nil t)
  anaconda-mode-jsonrpc("eldoc" anaconda-mode-eldoc-callback)
  #f(compiled-function () #<bytecode 0x2b6274d>)()
  anaconda-mode-bootstrap-filter(#<process anaconda-mode> "anaconda_mode port 40848\n" #f(compiled-function () #<bytecode 0x2b6274d>))
  #f(compiled-function (process output) #<bytecode 0x2b62765>)(#<process anaconda-mode> "anaconda_mode port 40848\n")

*anaconde-mode*
anaconda_mode port 40848

**Comment by valignatev** [comment]
Hey @gongliyu, 11001 error means "host not found", e.g. TRAMP can't connect to "holly" on port 40848. It might be unrelated to anaconda-mode. Do you still have this issue? What's your anaconda-mode version and what's your emacs version?

**Comment by gongliyu** [comment]
Since anaconda-mode on tramp is not a good choice because of the network traffic. Currently, I disabled anaconda-mode after entering tramp mode. I'd like to close this issue.
