### ISSUE TITLE
Anaconda-Eldoc not displaying anything.

### ISSUE THREAD

**Issue by JulienPalard** [proofit404/anaconda-mode#314]
I'm trying anaconda-mode and eldoc, but I see nothing poping in my minibuffer when my point is on a function call of me (same file) or in a native function (tried on logging.basicConfig). My .emacs contains:
```
;;; package -- julien

;;; Commentary:

;; .emacs for conf in /home/mdk
;;
;; Made by Palard Julien
;; Login   <julien@palard.fr>
;;
;; Started on  Sun Nov 16 12:00:18 2008 Julien Palard
;;

;;; Code:

;; Enable backup files.

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(setq make-backup-files t)

;; Enable versioning of backup files.
(setq version-control t)

;; Save all backup file in this directory.
(setq backup-directory-alist (quote ((".*" . "~/.emacs_backups/"))))
(setq-default delete-old-versions t)

(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)

(provide `.emacs)
;;; .emacs ends here

```

I'm using anaconda-mode      20180707.1010.

**Comment by JulienPalard** [comment]
Whoops, sorry:

`*anaconda-mode*`:
```
anaconda_mode port 38525
```

No `*anaconda-response*` and no `*anaconda-socat*` buffers.

**Comment by proofit404** [comment]
Ok, please provide content of the problematic buffer and not put of the `tree` command in the `~/.emacs.d/anaconda-mode/`.

**Comment by JulienPalard** [comment]
I think I understand the "issue", my point is "on a function call", it as to be "inside the parenthesis".

In one hand it make sense, but it was not clear to me and I *only* tried with my point on the *name* of the called function, no inside the parenthesis pair.

Maybe we could enhance the README on that point, english is not my main language but something like:

> anaconda-eldoc-mode provide document function to eldoc-mode so when your point is between the parenthesis of a function call, its parameters are shown in the echo area. All you need is to enable anaconda-eldoc-mode in addition to the previous setup.

?

**Comment by proofit404** [comment]
Yes, great idea. Could you submit PR?

**Comment by JulienPalard** [comment]
https://github.com/proofit404/anaconda-mode/pull/315

**Comment by proofit404** [comment]
Thanks!
