### ISSUE TITLE
Flycheck compatible?

### ISSUE THREAD

**Issue by silgon** [proofit404/anaconda-mode#323]
As far as I understand. By using `pythonic-activate` and the choosing my environment, I'm able activate the autocompletion. Is there a way that affter `pythonic-active` also activate flycheck or something else to validate and highlight syntax?

Thanks in advance!

**Comment by proofit404** [comment]
Hi, 

Flycheck works without additional setup. I use default flycheck config mention in their docs. When I change a current virtual environment with pythonic or pyenv-mode, linters like flake8 and mypy start using python interpreter from the virtual environment.

Regards, Artem.

**Comment by silgon** [comment]
I'm sorry but even after a while I seem to have the same problem.
Is there any way to check the flycheck checker? I did `M-: flycheck-checker` and the response is `nil`. 
As an example, I'm trying to use function annotators and it's always throwing an error (which is just, invalid syntax)
![example](https://user-images.githubusercontent.com/901061/55065760-b424fb00-507c-11e9-96a0-602189ff3625.png)

**Comment by digikar99** [comment]
@silgon I got flycheck working after I installed pylint and pyflakes in the venv. 

Through `ivy`, I also found `flycheck-verify-setup` to be an interesting command!
