### ISSUE TITLE
search pip installed directory

### ISSUE THREAD

**Issue by seventhking** [proofit404/anaconda-mode#325]
Hi, 

OS:ubuntu18
emacs:GNU Emacs 25.3.2

I use pip2.7 install pika module(/usr/lib/python2.7), but emacs with anaconda-mode just complete modules located in python3.6(/usr/lib/python3.6) directory.

In my termial, 
`python --version`    ------->   Python 2.7.15rc1

If i specified (add-to-list 'python-shell-extra-pythonpaths "/usr/lib/python2.7"), got error message:

Company: An error occurred in auto-begin
Company: backend (company-anaconda company-etags company-dabbrev-code) async timeout with args (candidates pi)
Saving file /home/seventh/test/rabbitmq/python/main.py...
Wrote /home/seventh/test/rabbitmq/python/main.py
Server error: InternalError('The subprocess /usr/bin/python3.6 has crashed.',)

Should Configure some variable?

**Comment by proofit404** [comment]
Hi,

This is strange for sure.

Did you try to setup anaconda mode according to the readme?

What python version is taking place when you do `M-x run-python` with plain Emacs config?

Regards, Artem.

**Comment by seventhking** [comment]
Hi,

I installed anaconda-mode from melpa and my emacs configuration :

(require 'anaconda-mode)

(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)
(after-load 'company
  (add-hook 'python-mode-hook
            (lambda () (sanityinc/local-push-company-backend #'(company-anaconda
                                                           company-etags
                                                           company-dabbrev-code)))))


M-x run-python :

Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>>

**Comment by proofit404** [comment]
Please, try to evaluate this code with `M-:`

```lisp
(with-temp-buffer (pythonic-call-process :args '("-V") :buffer standard-output) (message "%s" (buffer-string)))
```

**Comment by seventhking** [comment]
I just can find some log in *anaconda_mode* if i configured 
~~~
(add-to-list 'python-shell-extra-pythonpaths "/usr/lib/python2.7")
~~~
it looks like:
~~~
anaconda_mode port 35027
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/usr/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

Current thread 0x00007ffb7512b740 (most recent call first):
127.0.0.1 - - [26/Sep/2018 16:03:30] ================================================================================
Traceback (most recent call last):
  File "/home/seventh/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/seventh/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/seventh/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/seventh/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "InternalError(\'The subprocess /usr/bin/python3.6 has crashed.\',)"}}')
~~~

if not configure the python2.7 path,  *anaconda_mode* just has one line:
~~~
anaconda_mode port 35027
~~~

company-diag looks like:
~~~
Emacs 25.3.2 (x86_64-pc-linux-gnu) of 2018-04-19 on lgw01-amd64-039
Company 0.9.6

company-backends: (company-anaconda company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
                  (company-dabbrev-code company-gtags company-etags company-keywords)
                  company-oddmuse company-dabbrev)

Used backend: company-anaconda
Major mode: python-mode
Prefix: "pik"
Completions: none(error fetching)
~~~

**Comment by proofit404** [comment]
```
(add-to-list 'python-shell-extra-pythonpaths "/usr/lib/python2.7")
```

By this line you add python 2 libraries to the python 3 interpreter. And it can't read it because of backward incompatible syntax.

Try to set `python-shell-interpreter` instead.

Regards, Artem.

**Comment by seventhking** [comment]
Same error message after doing it
~~~
(add-to-list 'python-shell-extra-pythonpaths "/usr/lib/python2.7")
(setq python-shell-interpreter "/usr/bin/python2.7")
~~~

**Comment by proofit404** [comment]
Do not touch extra python paths.

**Comment by seventhking** [comment]
Just configured
~~~
(setq python-shell-interpreter "/usr/bin/python2.7")
~~~

`*anaconda-mode*` buffer shows:
~~~
anaconda_mode port 45067
~~~

`*Message*` buffer shows:
~~~
Can’t guess python-indent-offset, using defaults: 4
error in process filter: anaconda-mode-bootstrap-filter: Symbol’s function definition is void: pythonic-remote-ssh-p
error in process filter: Symbol’s function definition is void: pythonic-remote-ssh-p
Company: An error occurred in auto-begin
Company: backend company-anaconda async timeout with args (candidates pik)
No completion found
~~~

**Comment by proofit404** [comment]
Should be fixed in master.
