### ISSUE TITLE
 (void-function pythonic-start-process)

### ISSUE THREAD

**Issue by Knusper** [proofit404/anaconda-mode#328]
Installed anaconda-mode via elpa, but it is simply not working for me.  

Every anaconda-mode function I try (also documentation) fails with above error-message.  Unfortunately, the documentation is too sparse to help me figuring out where the problem could be on my side.

**Comment by proofit404** [comment]
Why put anaconda-mode on elpa?! :open_mouth:

**Comment by Knusper** [comment]
Sorry, I installed it via melpa.  For an unknown reason the dependency to pythonic-mode was not resolved.

**Comment by proofit404** [comment]
Did you update pythonic package?

**Comment by Knusper** [comment]
pythonic was not installed on the system, package.el did, for an unnknown reason, not resolve the dependency automatically.  I now deleted anaconda-mode, refreshed the package list, installed it again, and this time the dependency got resolved.  Why do things like this always happen to me :dizzy_face:

**Comment by proofit404** [comment]
So, I guess this ticket is resolved?

**Comment by Knusper** [comment]
OK - now I get an assertion error that the jedi version is too old :-1:

**Comment by Knusper** [comment]
OK - this is a bit weird, I installed anaconda - which comes with jedi (since I use anaconda I want to use also anaconda-mode in emacs) - however, anaconda has only jedi 0.12.1.  Removing jedi (conda remove jedi) in anaconda seems not to be a good idea.

**Comment by proofit404** [comment]
Actually anaconda and anaconda-mode are not related... Sorry for confusion.

**Comment by proofit404** [comment]
You can install Jedi manually into cache directories to, your global conda installation won't be affected.

**Comment by Knusper** [comment]
> Actually anaconda and anaconda-mode are not related... Sorry for confusion.

That is indeed very confusing that it would recommend it to be added to the documentation!

**Comment by proofit404** [comment]
Can you please send me the PR?

**Comment by valignatev** [comment]
> 'Jedi version should be >= 0.13.0, current version: %s'
Related to a https://github.com/proofit404/anaconda-mode/pull/327 which I'm working on
