### ISSUE TITLE
Anaconda mode spawning excessive processes

### ISSUE THREAD

**Issue by mrmagooey** [proofit404/anaconda-mode#337]
I'm finding that anaconda mode (possibly jedi) is spawning hundreds of processes over the course of a work session, and eventually both starving my computer of memory and python reporting constant messages to emacs of too many files being open. The process is the same in each case:  

    /usr/bin/python /root/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.13.1-py2.7.egg/jedi/evaluate/compiled/subprocess/__main__.py /root/.emacs.d/.cache/anaconda-mode/0.1.13/parso-0.3.1-py2.7.egg 2.7.15

Every time there is a autocompletion lookup, it seems to spawn about three of these processes, of which one will die after some time. Restarting emacs periodically is the current workaround.

**Comment by subhacom** [comment]
This is a jedi bug: [https://github.com/jorgenschaefer/elpy/issues/1481](url)
