### ISSUE TITLE
Add "python-shell-extra-pythonpaths" in spacemacs config file does not work

### ISSUE THREAD

**Issue by zarzen** [proofit404/anaconda-mode#338]
Hi,
I am using `sys.path.insert(...)` method to maintain python `import` from sibling folders. 
```
import sys
sys.path.insert(0, os.path.abspath('../common'))

from <a file at ../common dir> import xxx-function as yyy

if __name__ == "__main__":
    yyy()
```

Thus `jump to definition` function of `anaconda-mode` seems broken. I cannot jump from yyy to it's origin file located at `../common` directory. I guess it is the problem of the `PYTHONPATH`. 
So, I try to add following to `.spacemacs` config:
``` lisp
(defun dotspacemacs/user-config ()
    (add-to-list 'python-shell-extra-pythonpaths "/path/to/the/dir/contains/xxx-function")
)
```

After restart `emacs` got following error:
```log
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: python-shell-extra-pythonpaths
```

**Comment by zarzen** [comment]
> Hi, try to `(require 'python)`.
Great! It works.

Is there anyway to set this `python-shell-extra-pythonpaths` to be project specific? Write something into `.dir_locals.el`?

**Comment by proofit404** [comment]
I think it should work just fine with `.dir-local.el`

Regards, Artem.

**Comment by zarzen** [comment]
Hi, 
write the following content doesn't work:
```
(require 'python)
(add-to-list 'python-shell-extra-pythonpaths "/Users/zarzen/Dev/desc2perm/src/common")
```

I also tried 
```
((nil . ((require 'python)
         (add-to-list 'python-shell-extra-pythonpaths "~/Dev/desc2perm/src/common/"))))
```

Does this mean I can only set a variable at `.dir-locals.el` file, then write a function in `.spacemacs` config file to catch the value to add it to `pythonpaths` ?

**Comment by proofit404** [comment]
I guess you need something like
```lisp
((python-mode . ((python-extra-...))))
```

**Comment by dakra** [comment]
@zarzen Just to give you a complete example, your version of `.dir-locals.el`
would look like:

``` emacs-lisp
((python-mode . ((python-shell-extra-pythonpaths . ("/Users/zarzen/Dev/desc2perm/src/common")))))
```
