### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'padding_mode'

### ISSUE THREAD

**Issue by raphtoubi** [proofit404/anaconda-mode#350]
When I run my webapp locally, the program won't analyze the picture and I have this error message. Does someone already tackled this problem ?
<img width="508" alt="Capture d’écran 2019-03-26 à 17 47 46" src="https://user-images.githubusercontent.com/43609010/55227505-f33b8380-5217-11e9-8c58-e4359f69b72e.png">

**Comment by proofit404** [comment]
You report to the wrong repo.
