### ISSUE TITLE
Function Annotations with flycheck

### ISSUE THREAD

**Issue by silgon** [proofit404/anaconda-mode#352]
I'm having some problems with flycheck while using anaconda mode.
I activate my environment with `pythonic-activate` which some version of `python 3`, however, I don't seem to be able to use function annotations with flycheck. A simple example:

![function_annotations](https://user-images.githubusercontent.com/901061/56720442-2142b380-6743-11e9-9ef6-567f72a782b8.png)
The message in the minibuffer is just `invalid syntax`.

I'm not sure if it's me who has misconfigured something, but I cannot seem to solve this issue.

**Comment by proofit404** [comment]
Hi, thanks for the report.

`anaconda-mode` has no functionality related to flycheck.

I think you should report it in the flycheck repo.

**Comment by silgon** [comment]
Thanks for the reply @proofit404 , what do you use to validate your syntax when you're using `anaconda-mode`?

**Comment by proofit404** [comment]
Flycheck flake8 works for me out of the box. I usually install it inside the virtual environment I activate with pythonic.

**Comment by silgon** [comment]
Sorry for the late response. I use `pythonic-activate` with my virtual environment and yet flycheck doesn't work. I'm using anaconda to generate my virtual environment though. It should be it I think....

**Comment by silgon** [comment]
Ok. I generated a virtual environment `virtualenv -p python3.6 .penv` inside the project and at least it accepts `Function Annotations`. I'll try to figure why the behavior is that way and why flycheck doesn't accept `pythonic-activate`, at least for the anaconda environments.

**Comment by silgon** [comment]
Well... In the end what seems to solve the issue (at least for me) is the following workaround:
```elisp
(defun my-pythonic-activate (virtualenv)
  "Activate python VIRTUALENV."
  (interactive "DEnv: ")
    (progn
        (setq flycheck-python-pycompile-executable (concat virtualenv "bin/python"))
        (setq flycheck-python-flake8-executable (concat virtualenv "bin/flake8"))
        (setq flycheck-python-pylint-executable (concat virtualenv "bin/pylint"))
        (setq python-shell-virtualenv-root (pythonic-python-readable-file-name virtualenv))
        (flycheck-mode -1)
        (flycheck-mode t)
        ))
```
I just leave that part of code here to document the problem.
