### ISSUE TITLE
Make clear that either python-json-rpc or pip should be installed

### ISSUE THREAD

**Issue by Hylen** [proofit404/anaconda-mode#53]
When i decided to try this package out today, I ran into a little bit of trouble. Wasn't until I removed the filter on the server in the elisp file I understood that the problem was I didn't have pip or python-json-rpc installed.

Perhaps python-json-rpc could be pointed out as a dependency on the front page (and also the pip-behavior)?

**Comment by proofit404** [comment]
Done.
