### ISSUE TITLE
Blocking call to accept-process-output with quit inhibited

### ISSUE THREAD

**Issue by danielwuz** [proofit404/anaconda-mode#54]
I've had this issue recently after updating `anaconda-mode` from melpa. My emacs hung when company-mode tries to auto complete with `anaconda`, and I see message as following in minibar.
```
Blocking call to accept-process-output with quit inhibited.
```

 I guess this is a regression as I saw previous discussion on this issue before. Below is backtrace log on `toggle-debug-on-quit`.
```
Debugger entered--Lisp error: (quit)
  anaconda-mode-bootstrap()
  anaconda-mode-start()
  anaconda-mode-call("complete")
  anaconda-mode-complete()
  company-anaconda-candidates()
  company-anaconda(candidates #("fo" 0 2 (fontified nil)))
  apply(company-anaconda (candidates #("fo" 0 2 (fontified nil))))
  #[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(candidates #("fo" 0 2 (fontified nil))) company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"]()
  funcall(#[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(candidates #("fo" 0 2 (fontified nil))) company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"])
  company-call-backend-raw(candidates #("fo" 0 2 (fontified nil)))
  company--fetch-candidates(#("fo" 0 2 (fontified nil)))
  company-calculate-candidates(#("fo" 0 2 (fontified nil)))
  #[0 "\n\203	\nC\202\n\211\205\245\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\236\314\300\242!\203\230\315\300\242!\211\301\316\f!\240\210\301\242:\204l
\203\230\317\320!\210\202\230
\203t\300\242\2119\203\203\321\322!P\202\211\323\301\242@!\210\324\301\242!\210\325\326\327 \"\210\330\331!\210\332\333\301\242\"\210A\266\202\202\n\207" [(#("fo" 0 2 (fontified nil))) (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" " " symbol-name company--update-group-lighter company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix company-lighter] 6 "\n\n(fn)"]()
  funcall(#[0 "\n\203	\nC\202\n\211\205\245\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\236\314\300\242!\203\230\315\300\242!\211\301\316\f!\240\210\301\242:\204l
\203\230\317\320!\210\202\230
\203t\300\242\2119\203\203\321\322!P\202\211\323\301\242@!\210\324\301\242!\210\325\326\327 \"\210\330\331!\210\332\333\301\242\"\210A\266\202\202\n\207" [(#("fo" 0 2 (fontified nil))) (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" " " symbol-name company--update-group-lighter company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix company-lighter] 6 "\n\n(fn)"])
  company--begin-new()
  company--perform()
  #[0 "\300 \207" [company--perform] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [company--perform] 1 "\n\n(fn)"])
  company-auto-begin()
  company-idle-begin(#<buffer *scratch*> #<window 3 on *scratch*> 5 3)
  apply(company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 5 3))
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 21662 39799 656946 nil company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 5 3) nil 0])
```

**Comment by proofit404** [comment]
Maybe I need to use `subprocess.Popen([sys.executable, '-m', 'pip'])` instead of `pip` binary.

**Comment by syl20bnr** [comment]
@proofit404 do you plan to try this fix ? I had the same exact same issue as @danielwuz.

**Comment by angrybakon** [comment]
@proofit404 Yes, a fix would be more than welcome : )

**Comment by mheider** [comment]
@danielwuz your suggestion was correct. I installed pip from easy_install and everything worked fine!

**Comment by sableloki** [comment]
another thankyou to @danielwuz

**Comment by sableloki** [comment]
to my knowledge it would seem that we have to break compatibilty with python 2.6 to close this issue

**Comment by ryankask** [comment]
I'm unable to use anaconda-mode since it starting using `pip` to install its dependencies.

The issue for me is that I'm using a Homebrew installed Python on a Mac and this is what I have by default in my `distutils.cfg` (`/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/distutils.cfg`):

```ini
[global]
verbose=1
[install]
force=1
prefix=/usr/local
```

When anaconda-mode tries to install the required packages using `pip`, it fails with the following: `DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both`

This is because the `-t` option anaconda-mode uses to installs the packages conflicts with the ``prefix` line in the config above.

I'd rather install the dependencies myself instead of anaconda-mode trying to manage them for me. I understand, however, that this would be a usability issue.

anaconda-mode could first try to import the packages and if necessary, inspect the installed packages' versions using `jedi.__version__` and `jsonrpc.__version__`.

If an `ImportError` is raised, it could fall back to current behavior and install the Python packages alongside the emacs list file.

Also, I use MELPA to manage my emacs packages and it seems a bit strange that every time I update anaconda-mode and the previous version is deleted, `pip` will have to install the jedi and json-rpc packages again, even if the required versions haven't changed.

**Comment by proofit404** [comment]
Hello everybody. I'm sorry for my late responses. Since new year holidays in Russia I unable to fix this issue until Jan 12.

С Новым годом и Рождеством!

**Comment by proofit404** [comment]
I fix deadlock discussed here.  But I still doesn't understand what is the difference between pip from pypi and pip from homebrew?

**Comment by ryankask** [comment]
Hi proofit404,

When I try to install something with pip using the `-t` flag, the following results:

```
$ PIP_REQUIRE_VIRTUALENV=0 pip install -t ./ json-rpc
Collecting json-rpc
  Using cached json_rpc-1.8.1-py2-none-any.whl
Installing collected packages: json-rpc
  Exception:
  Traceback (most recent call last):
[snipped]
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
      "must supply either home or prefix/exec-prefix -- not both"
  DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

This is because of this code in the Homebrew Python formula: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/python.rb#L191

The Homebrew Python sets some default distutils config options, including the `--prefix` option. The end result is that pip will not run with the `-t` option as it exists now in `anaconda_mode.py`. pip appears to transform the [`-t` option into the `--home` option](https://github.com/pypa/pip/blob/develop/pip/commands/install.py#L236) causing the error.

I think it ultimately is a [Python bug](http://bugs.python.org/issue22269) but there is also a [Homebrew issue](https://github.com/Homebrew/homebrew/pull/31811) tracking it.

The result (it seems) is that Homebrew Python users will need to install the dependencies manually with pip. Your latest changes allow that so I am able to use anaconda again.

**Comment by proofit404** [comment]
@ryankask If we move to the `subprocess.Popen([sys.executable, '-m', 'pip', 'install', '-t', ...])` then `anaconda-mode` will use pip installed from easy_install.  Can this solve this issue?

**Comment by endrebak** [comment]
I'm having the same problem on OS X, however I'm not using a brew version of Python, I'm using the Scientific Python Distribution called Anaconda: https://store.continuum.io/cshop/anaconda/

Is the fix to install the dependencies for anaconda-mode manually for the system version of Python?, i.e.:

```
sudo /usr/bin/python -m easy_install jedi==0.8.1
sudo /usr/bin/python -m easy_install json-rpc==1.8.1
```

(Haven't tried it yet because it seems scary)

**Comment by proofit404** [comment]
@endrebak can you post `*anaconda-mode*` buffer content first?

**Comment by endrebak** [comment]
```
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/.emacs.d/elpa/anaconda-mode-20150111.1101/anaconda_mode.py", line 37, in <module>
    assert jedi.__version__ == '0.8.1', 'Jedi version does not match 0.8.1'
AssertionError: Jedi version does not match 0.8.1

Process anaconda_mode exited abnormally with code 1
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/.emacs.d/elpa/anaconda-mode-20150111.1101/anaconda_mode.py", line 37, in <module>
    assert jedi.__version__ == '0.8.1', 'Jedi version does not match 0.8.1'
AssertionError: Jedi version does not match 0.8.1

Process anaconda_mode exited abnormally with code 1
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/.emacs.d/elpa/anaconda-mode-20150111.1101/anaconda_mode.py", line 37, in <module>
    assert jedi.__version__ == '0.8.1', 'Jedi version does not match 0.8.1'
AssertionError: Jedi version does not match 0.8.1

Process anaconda_mode exited abnormally with code 1
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/.emacs.d/elpa/anaconda-mode-20150111.1101/anaconda_mode.py", line 37, in <module>
    assert jedi.__version__ == '0.8.1', 'Jedi version does not match 0.8.1'
AssertionError: Jedi version does not match 0.8.1

Process anaconda_mode exited abnormally with code 1
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/.emacs.d/elpa/anaconda-mode-20150111.1101/anaconda_mode.py", line 37, in <module>
    assert jedi.__version__ == '0.8.1', 'Jedi version does not match 0.8.1'
AssertionError: Jedi version does not match 0.8.1

Process anaconda_mode exited abnormally with code 1
```

**Comment by proofit404** [comment]
```
cd /Users/endrebakkenstovner/.emacs.d/elpa/anaconda-mode-20150111.1101/
python -i
>>> import jedi
>>> jedi.__version__
```

**Comment by endrebak** [comment]
`'0.8.1-final0'`

Could the `-final` string be the issue?

**Comment by proofit404** [comment]
Yes. It's exactly. Remove `/Users/endrebakkenstovner/.emacs.d/elpa/anaconda-mode-20150111.1101/jedi*`, kill `*anaconda-mode*` buffer or simply restart emacs.

**Comment by endrebak** [comment]
Thanks for the help so far.

I have no folder or files called `jedi*`:

```
endrebakkenstovner@dhcp-032209 ~/.e/e/anaconda-mode-20150111.1101> ls
anaconda-mode-autoloads.el anaconda-mode.el           anaconda_mode.py           jsonrpc
anaconda-mode-pkg.el       anaconda-mode.elc          json_rpc-1.8.1.dist-info 
```
perhaps that is the problem?

**Comment by ryankask** [comment]
@proofit404 That wouldn't make a difference. It appears to be a lower level [distutils bug](http://bugs.python.org/issue22269). I'm not really sure what the right option is at this point (besides vendoring the packages which you recently stopped doing) but I will continue to think about it.

In the meantime, if any Homebrew users come across this issue, simply install the dependencies yourself.

**Comment by endrebak** [comment]
`python -m easy_install jedi==0.8.1` ftw. Now it works. Thanks!

**Comment by proofit404** [comment]
@ryankask Maybe we can install dependencies without pip? Something like `curl http://pypi.python.org | unzip -C /path/to/anaconda-mode`. Or homebrew users can manually remove prefix from distutils config.

**Comment by pwalsh** [comment]
I still have this problem with Homebrew Python.

In my *anaconda-mode* buffer I see both:

```
error: must supply either home or prefix/exec-prefix -- not both
```

and 

```
Warning: The version specified ('0.8.1-final0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

Amongst the usual logging of the download process.

**Comment by proofit404** [comment]
@pwalsh I can't workaround `distutils` bug in anaconda mode.  First error occurs because of `prefix` option in your `distutils.cfg`.  I add few possible solutions in the README.  Manual dependencies installation is one of the specified ways to solve it.

Second error message occurs because you have relatively new `pip`.  '0.8.1-final0' doesn't valid version identifier any more.  This message will go away after new `jedi` release.

**Comment by dsdshcym** [comment]
@proofit404 I have this problem again today. Maybe there are some new problems in the new version? Or it is only my own problem?

Here is the anaconda-mode buffer output:
https://gist.github.com/dsdshcym/4013b4f59b4177ba405c

**Comment by proofit404** [comment]
@dsdshcym actually it's different problem. Update your anaconda-mode installation and create new issue. I need whole buffer content together with python, jedi and jsonrpc status info.

**Comment by naseer** [comment]
I have the same problem on OSX - manually installing jedi and json-rpc didn't help


```
Process anaconda_mode exited abnormally with code 1
Downloading/unpacking service-factory
  Downloading service_factory-0.1.2.tar.gz
  Running setup.py (path:/private/var/folders/c9/8m5qvh796696ds3kmcqgz_9h002_2z/T/pip_build_naseer/service-factory/setup.py) egg_info for package service-factory

Downloading/unpacking six (from service-factory)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: service-factory, six
  Running setup.py install for service-factory
    error: must supply either home or prefix/exec-prefix -- not both
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/c9/8m5qvh796696ds3kmcqgz_9h002_2z/T/pip_build_naseer/service-factory/setup.py';exec(compile(getattr(tokeniz\
e, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/c9/8m5qvh796696ds3kmcqgz_9h002_2z/T/pip-qpPAfp-record/install-record.txt --single-version-externally-managed --compile --home=/var/f\
olders/c9/8m5qvh796696ds3kmcqgz_9h002_2z/T/tmp9SBCrv:
    running install

error: must supply either home or prefix/exec-prefix -- not both
```

**Comment by proofit404** [comment]
@naseer Install `service_factory==0.1.2` manually.

**Comment by naseer** [comment]
doh - missed that, thanks :+1:

**Comment by yangj1e** [comment]
I have the same problem and I have manually installed jedi, json-rpc, service_factory.
```
Process anaconda_mode exited abnormally with code 1
Collecting service-factory
  Using cached service_factory-0.1.2.tar.gz
Collecting six (from service-factory)
  Using cached six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six, service-factory
[31m  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
      status = self.run(options, args)
    File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 352, in run
      root=options.root_path,
    File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 693, in install
      **kwargs
    File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 817, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1018, in move_wheel_files
      isolated=self.isolated,
    File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 138, in move_wheel_files
      name, user=user, home=home, root=root, isolated=isolated
    File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 236, in distutils_scheme
      i.finalize_options()
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 38, in finalize_options
      orig.install.finalize_options(self)
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
      "must supply either home or prefix/exec-prefix -- not both"
  DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
[0m
Traceback (most recent call last):
  File "/Users/yangjie/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 40, in <module>
    assert pip.returncode is 0, 'PyPi installation fails.'
AssertionError: PyPi installation fails.

**Comment by yangj1e** [comment]
Well, I think it is because I set the `python-shell-virtualenv-path` to be `~/anaconda`.

**Comment by proofit404** [comment]
@yangj1e if you install anaconda-mode dependencies manually in some virtualenv than they don't magically appears in the another one. Install they into each virtualenv you use, or install they ones into anaconda-mode directory with pip -t option.

**Comment by yangj1e** [comment]
Yes I know. Thank you.

**Comment by skwuent** [comment]
I hit this problem with Spacemacs and Ubuntu 15.04. It was fixed by removing the pip that I had installed with apt and then installing pip 6.1.1 using easy_install.

**Comment by proofit404** [comment]
@skwuent I can't actually say is this the same issue or not without actual stacktrace.
