### ISSUE TITLE
Regression in anaconda_mode.py

### ISSUE THREAD

**Issue by tdavis** [proofit404/anaconda-mode#56]
Please see #49 for an explanation; restoring the line `sys.path.insert(0, '')` resolves the issue.

**Comment by proofit404** [comment]
```python
project_path = dirname(abspath(__file__))
sys.path.insert(0, project_path)
```
Doesn't meet this case?

**Comment by proofit404** [comment]
Also note that anaconda-mode doesn't bind `default-directory` to the package location. So `cwd` will equal `default-directory` from buffer where you call `anaconda-mode` commands first time.

**Comment by tdavis** [comment]
Hmmm, odd; I didn't seen the line in master, but it is there. I will look into this more; currently, all I know is that using an old anaconda_mode.py works for me. I'll try to figure out why.

**Comment by proofit404** [comment]
Any progress?

**Comment by proofit404** [comment]
Fill free to reopen this issue if you still have this problem.
