### ISSUE TITLE
anaconda-mode-bootstrap: Unable to run anaconda-mode server

### ISSUE THREAD

**Issue by CestDiego** [proofit404/anaconda-mode#57]
I get this when I try to use anaconda-go-to-definition :( Can you guide me on what information should I give to solve this? Running Emacs 24.4 Ubuntu 14.04

**Comment by proofit404** [comment]
I need `*anaconda-mode*` buffer content.

**Comment by CestDiego** [comment]
It says emacs: /home/io/.virtualenvs/bin/python: No such file or directory

**Comment by CestDiego** [comment]
I have this  
``` elisp
 (setq python-shell-virtualenv-path "~/.virtualenvs")
```

So.... I have there my virtualenvs I've created. And when I needed for anaconda-mode to go to an specific definition I would first go to a project, use "pyvenv-workon" and select a virtual env in that directory. Now it seems anaconda is looking at the whole directory though

**Comment by proofit404** [comment]
You need to specify concrete virtualenv with `(setq python-shell-virtualenv-path "~/.virtualenvs/current_venv")`. When you switch it to the another one all things will restart its server transparently.

**Comment by CestDiego** [comment]
gr8 thx. But ain't there a way to do it with an emacs command or sth I'm missing out?

**Comment by proofit404** [comment]
For good reason `pyvenv-activate` should setup it. You can file issue to https://github.com/jorgenschaefer/pyvenv.  Or you can try `pyenv` tool with my `pyenv-mode`.
