### ISSUE TITLE
Assertion of jedi version fails

### ISSUE THREAD

**Issue by noinil** [proofit404/anaconda-mode#58]
Since now anaconda use pip to install jedi, using **assert** to check version of jedi and jsonrpc may fail on some systems.  In my case, I use mac os x, and pip1.5.6, my jedi version is "0.8.1-final10".  This causes error in *anaconda_mode.py*.
I fixed it on my computer by modify line 37 of *anaconda_mode.py*:
```python
assert jedi.__version__ == '0.8.1-final0', 'Jedi version does not match 0.8.1'
```
But obviously this is not a good solution. 
Please fix this. Thanks.

**Comment by proofit404** [comment]
Why you don't install `jedi==0.8.1` exactly?

**Comment by noinil** [comment]
I think this is automatically searched and installed by pip, which is coded in *anaconda_mode.py*, isn't it?

**Comment by proofit404** [comment]
Only if it placed together with `anaconda-mode.py`

**Comment by noinil** [comment]
I see. :+1: 
Thanks for your answer, problem solved now.

**Comment by proofit404** [comment]
You're welcome.
