### ISSUE TITLE
use python-shell-interpreter as python executable.

### ISSUE THREAD

**Issue by zbelial** [proofit404/anaconda-mode#62]
In anaconda-mode-python, python executable is hardcoded as "python" . This is not convinient, especially when you have python3 and python2 installed at the same time. I think it will be better if you change it to use python-shell-interpreter. 
Anyway, thank you for this great mode. I like it.

**Comment by proofit404** [comment]
This behavior is discussable. For windows it use `pythonw` for example. Also `python-shell-virtualenv-path` checked and used according to platform. You can write advanced version of this [function][https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L61-L67] or describe this usage more verbosely.

**Comment by zbelial** [comment]
I just use Linux, so this is my own use case.
The default python on my computer is python2.7, and python is a symbol link to it. But I want to learn python3, so if hardcoded as 'python', then sometimes anaconda will fail to complete and jump to defination. 
As you have given me a hint, advicing anaconda-mode-python makes sense for me. So to change or to keep the situation are all good for me. 
You can close this issue if you wish. Thanks again.

**Comment by proofit404** [comment]
I can check value of interpreter variable, validate it through set of other python variables and use it correctly according to your recommendation. I'll do it in my pythonic library and then use it in anaconda mode. Please, wait for a while.

**Comment by zbelial** [comment]
Sure, thank you very much.

**Comment by gozes** [comment]
@proofit404 would it be simpler, and faster, to set a variable with the return value of anaconda-mode-python and then use that inside anaconda? That way it can be overwritten by users.

**Comment by proofit404** [comment]
@gozes Actually `anaconda-mode-python` makes the opposite - it builds anaconda-mode starting command depending on values in this variable. In this way we mimic `run-python` command behavior.

**Comment by proofit404** [comment]
Done with `pythonic` package.
