### ISSUE TITLE
Is there a way to reverse jump-to-definition?

### ISSUE THREAD

**Issue by CestDiego** [proofit404/anaconda-mode#63]
I see that sometimes I would like to get back to the part of the file that I was before jumping to definition (when the definition is in the same file)

**Comment by proofit404** [comment]
`M-*`?

**Comment by CestDiego** [comment]
gr8 thx :)

**Comment by proofit404** [comment]
You're welcome.

**Comment by danielwuz** [comment]
FYI if you're using spacemacs, you can use C-o to jump back and C-i to jump forward again. Anaconda goto-definition has been integrated with evil-jumper in spacemacs

**Comment by proofit404** [comment]
@danielwuz Nice advice!
