### ISSUE TITLE
complete at point key binding conflict

### ISSUE THREAD

**Issue by QiangF** [proofit404/anaconda-mode#65]
Hello,
The complete keybinding C-M i conflicts with the outline cycle buffer keybinding, I tried to rebind it, but I can't find the complete-at-point function. I am using outshine mode, which is not easy to customise.
Is there a quick way to rebind the anaconda complete function?
Also when I enable anaconda backend for company mode, I lost the in buffer words completion. So I can't use that as a substitute, I have to find another way to do the anaconda completion.
Thank you!

**Comment by proofit404** [comment]
You can rebind `complete-at-point` command with following snippet:
```lisp
(eval-after-load "python"
 '(progn
   (define-key python-mode-map (kbd "M-i") 'complete-at-point)))
```
Also note that company allow you to use multiple backends at ones:
```lisp
(eval-after-load "company"
 '(progn
   (add-to-list 'company-backends '(company-anaconda :with company-dabbrev)))
```
Consult company documentation for more info.

**Comment by QiangF** [comment]
Thank you very much Sir!
The command is completion-at-point though.

**Comment by proofit404** [comment]
You're welcome!
