### ISSUE TITLE
documetation lookup not working

### ISSUE THREAD

**Issue by QiangF** [proofit404/anaconda-mode#66]
Hello,
I can't find out why M-? always shows me an empty buffer. I am using emacs 24.4 on debian jessie and the ananconda mode is the newest from melpa.
Eldoc keybinding C-c C-f works if I M-x run-python first. I have the exec-path-from-shell in my init.el.  The python distribution is the sientific anancoda python 2.7, in which I installed pip, virtualenv and jedi. Also python-shell-exec-path's value is nil, but it makes no difference with (setq python-shell-exec-path "/home/q/anaconda/bin"). Is this a bug?
Sorry about this perhaps naive question. I hope I can help make this nice package easier to use for all beginners.
Thank you!

**Comment by proofit404** [comment]
Try to set your anaconda installation as virtual environment:
```lisp
(setq python-shell-virtualenv-path "/home/q/anaconda/")
```
Also wait for the new melpa build and post here `*anaconda-mode*` buffer content.

**Comment by QiangF** [comment]
Thank you sir. Here is the *anaconda-mode* buffer, looks like it had found the pathon path, but the problem persists: *anaconda-doc* still empty.

Collecting json-rpc
  Using cached json_rpc-1.8.1-py2-none-any.whl
Installing collected packages: json-rpc

Successfully installed json-rpc
Python executable: /home/q/anaconda/bin/python
Jedi version: (0, 7, 0)
JSON RPC version: 1.8.1
anaconda_mode port 24970

**Comment by proofit404** [comment]
Can you post python buffer to reproduce this problem? (mark point possition with `|` char)

**Comment by QiangF** [comment]
Sure, here is  a test buffer in python mode.
import numpy as np
a = num|py.arr|ay([10])
b = ran|ge(0,10)
def test():
    """this is a test"""
    pass
te|st()
when the cursor is on numpy and array, there is no meassage in the echo area, 
when the cursor is on the built in range and user defined test function, I got this error message.
JSON-RPC error condition: :data, (:type "AttributeError" :args ("'Definition' object has no attribute 'docstring'") :message "'Definition' object has no attribute 'docstring'"), :code, -32000, :message, "Server error"

**Comment by proofit404** [comment]
Uninstall jedi from anaconda setup. Anaconda-mode will install newer jedi automatically for you.

**Comment by QiangF** [comment]
Unintalling jedi solves the problem.
Thank you so much!

**Comment by proofit404** [comment]
I'm happy to help my users to solve their problems.
