### ISSUE TITLE
Unable to run anaconda-mode server

### ISSUE THREAD

**Issue by rongyi** [proofit404/anaconda-mode#69]
in Mac OS, When editing py file, anaconda mode give me this error message, and I find out I didn't install json-rpc,  after I install json-rpc, all goes ok. So can we give a little hint when install anaconda-mode?

**Comment by proofit404** [comment]
Please post `*anaconda-mode*` buffer content. Did you read [this](https://github.com/proofit404/anaconda-mode#issues) README section?

**Comment by ladevan** [comment]
First, thanks to @proofit404 for this wonderful package. I got the same issue of "unable to run anaconda-mode server" as @rongyi, after "pip install json-rpc", all goes fine. Maybe it's better to state the requirements in the README section?
