### ISSUE TITLE
useing system pyhon(s) insted of Virtualenv?

### ISSUE THREAD

**Issue by gozes** [proofit404/anaconda-mode#72]
is there  a way to tell anaconda to use my system python(s) rather then using virtualenv?

**Comment by proofit404** [comment]
Set `python-shell-virtualenv-path` to `nil`?

**Comment by gozes** [comment]
I was thinking that plus use the function anaconda-mode-python, if it took any parameters, to give the name of the bin I want to use or set anaconda-mode-process-pythonpath. Or would setting python-shell-virtualenv-path to nil make it so that anaconda  looks for python executable in usr/bin?

**Comment by proofit404** [comment]
`anaconda-mode-python` will use "python" executable resolved from `exec-path` variable if `python-shell-virtualenv-path` is `nil`.

**Comment by gozes** [comment]
thank that is what I wanted to know

**Comment by proofit404** [comment]
You're welcome.
