### ISSUE TITLE
blocking call to accept-process-output

### ISSUE THREAD

**Issue by holocronweaver** [proofit404/anaconda-mode#73]
About every 15 seconds I receive the following error when using a Python buffer while anaconda-mode is active:

```Blocking call to accept-process-output with quit inhibited!!```

When this occurs, I have to press ```C-g``` repeatedly to regain keyboard input into the buffer.

I am using the latest Emacs trunk (as of 2015-03-10) on Linux with anaconda-mode version ```20150310.46```. This may be related to #54, but maybe not.

**Comment by proofit404** [comment]
Please, post `*anaconda-mode*` buffer content.

**Comment by holocronweaver** [comment]
Here you go!
```
Traceback (most recent call last):                                                                                                                                                                                   
  File "/home/jesse/.emacs.d/elpa/anaconda-mode-20150310.46/anaconda_mode.py", line 38, in <module>                                                                                                                  
    pip = Popen(command)                                                                                                                                                                                             
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__                                                                                                                                                     
    errread, errwrite)                                                                                                                                                                                               
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child                                                                                                                                              
    raise child_exception                                                                                                                                                                                            
OSError: [Errno 2] No such file or directory                                                                                                                                                                         
                                                                                                                                                                                                                     
Process anaconda_mode exited abnormally with code 1   
```
Looks like I did not have pip installed, and that was the problem. Is it possible to have an error message printed in this case to alert the user that pip is required? I guess the check should be done within elisp, rather than Python. This could avoid trying to call a non-existent program and causing the keyboard lock to occur.

**Comment by proofit404** [comment]
Actually I'm on the way to solve it. Just don't have much time to implement.

**Comment by holocronweaver** [comment]
Thanks for making this great module! Looks like it will really speed up my Python dev.

**Comment by proofit404** [comment]
You're welcome.

**Comment by endrebak** [comment]
Okay so the fix for this is to install `pip`? (Having the same problem)

**Comment by proofit404** [comment]
Yep. Also check [issues](https://github.com/proofit404/anaconda-mode#issues) README section.

**Comment by pank** [comment]
Maybe an error should be thrown if `(executable-find "pip")` is nil?  It at least took me a while to figure why anacanda was "so slow"...

**Comment by proofit404** [comment]
How it can be "so slow" if it doesn't work at all without pip? Actually I'm work on user friendly errors as I mention above.

**Comment by pank** [comment]
Malyshev Artem <notifications@github.com> writes:

> How it can be "so slow" if it doesn't work at all without pip?

It blocks the input (at least with company) and when you don't know about
`*anaconda-mode*` it seems slow.  The quotes were meant to signify that
slow was a misconception.

> Actually I'm work on user friendly errors as I mention above.

I understand.  I meant as a temporary workaround.

**Comment by proofit404** [comment]
`*anaconda-mode*` buffer with exactly traceback will be shown in the case of any error. Also `*anaconda-response*` buffer will be shown in the case of unreadable server response. I'm think this is enough.
