### ISSUE TITLE
`anaconda-mode-goto` prefers custom decorator definition.

### ISSUE THREAD

**Issue by jcpetkovich** [proofit404/anaconda-mode#74]
In the following minimal example:

```python
import time

def timed_method(method):

    def time_wrapped(self, *args, **kwargs):
        start = time.time()
        result = method(self, *args, **kwargs)
        stop = time.time()
        self.total_time = stop - start
        return result

    return time_wrapped


class ObjectToBeTimed(object):

    @timed_method
    def dostuff(self):
        print("I did things")


x = ObjectToBeTimed()

x.dostuff()
```
With the point on `x.dostuff()`, `anaconda-mode-goto` prefers navigating to the custom decorator rather than the function definition, whereas `anaconda-mode-goto-assignments` goes to the correct definition.

It this seems like a bug to me. When the point is on a method with a decorator, I would generally want the method definition not the decorator's definition.

**Comment by proofit404** [comment]
Actually this is behaviour of the `jedi` library. You can rebind defaults hotkeys. Or you can suggest better solution for this problem?

**Comment by jcpetkovich** [comment]
Hmm, I don't have a better suggestion just yet. But I did notice that this is an issue in elpy as well: https://github.com/jorgenschaefer/elpy/issues/433

Sounds like deciding between the two functions is difficult. Strangely enough, [jedi.el](https://github.com/tkf/emacs-jedi) always seems to do the right thing, but I don't really understand it's code just yet.

**Comment by proofit404** [comment]
`jedi.el` uses definition or assignment depending on given prefix arg and goto definition config.

**Comment by CestDiego** [comment]
So is there a way to have anaconda to go by default to the assignment or definition in a smart way? or are we tied to the `jedy` library?

**Comment by proofit404** [comment]
@CestDiego It's your own choice which command to use.
