### ISSUE TITLE
anaconda-doc window interferes with window layout/golden ratio mode

### ISSUE THREAD

**Issue by cpaulik** [proofit404/anaconda-mode#75]
I am using [golden ration mode](https://github.com/roman/golden-ratio.el) which means my windows are resized when i switch between them.

Accessing the help e.g. in a lisp buffer shows the help window and when I return my window is the size I left it in. Doing the same in anaconda mode shows the documentation in the second buffer and does not resize it back when i close the documentation. This gif might explain it better:

![recorded](https://cloud.githubusercontent.com/assets/380927/6873634/ff67e8d4-d4b1-11e4-9507-4e2cf821038d.gif)

I'm using [Spacemacs](https://github.com/syl20bnr/spacemacs) but I guess that this is not related to that.

**Comment by proofit404** [comment]
I'll look at this as far as I got free time. You can fix it yourself an make a poll request.

**Comment by proofit404** [comment]
Does this applies to new implementation?

**Comment by cpaulik** [comment]
Yes still the same behaviour.

**Comment by proofit404** [comment]
:disappointed: I thought it occurs during window configuration workaround in the previous anaconda-mode version.

**Comment by proofit404** [comment]
Maybe @roman can help?

**Comment by proofit404** [comment]
Since `anaconda-mode` use plain `pop-to-buffer` function without any magic I think there is nothing to do from my side.
