### ISSUE TITLE
package-install RET anaconda-mode RET gives json-rpcs error

### ISSUE THREAD

**Issue by bikemule** [proofit404/anaconda-mode#76]
This was after I followed the directions to add MELPA here: http://melpa.org/#/getting-started
I'm using Emacs 24.4 on OS X, which I installed with Homebrew.
I can't find the error now. I should have written it down, but it was saying it couldn't find json-rpc-2014something

I realize that's not the most helpful and maybe not even totally your fault, but I thought I'd note it.

**Comment by proofit404** [comment]
I doesn't has macbook so I can't reproduce exactly situation. Can you post content of the `*anaconda-mode*` buffer? If you publish your configuration somewhere can you give me a link to it? I'll give it a try.
