### ISSUE TITLE
Once More: Blocking call to accept-process-output with quit inhibited!!

### ISSUE THREAD

**Issue by capdevc** [proofit404/anaconda-mode#80]
I'm on Ubuntu 14.10, emacs 24.4

contents of my *anaconda-mode* buffer:

    Python executable: /home/cc/anaconda/bin/python
    jedi version: 0.8.1
    service_factory version: 0.1.2
    anaconda_mode port 9000

Everything looks ok there, but I get the "Blocking call to accept-process-output with quit inhibited!!" message repeatedly when opening a python buffer.

In case it matters I'm using the anaconda python distribution

**Comment by pronobis** [comment]
Same here:
`Blocking call to accept-process-output with quit inhibited!! [3 times]`
and
```
Python executable: /home/czikus/.virtualenv/python3/bin/python
jedi version: 0.8.1-final0
service_factory version: 0.1.2
anaconda_mode port 9000
```
Emacs 24.5

**Comment by proofit404** [comment]
As far as I understand everything works fine, except you are getting this message?

**Comment by pronobis** [comment]
I guess so, I did not observe any issue related to this message.

**Comment by proofit404** [comment]
This message is side effect of [json-rpc](https://github.com/skeeto/elisp-json-rpc) library.
