### ISSUE TITLE
how to use ipython as default interpreter

### ISSUE THREAD

**Issue by dzhwinter** [proofit404/anaconda-mode#81]
I'm a new bier to emacs.  if i miss understood the ananconda-mode feature, please figure me out.
I wanna to use the ananconda-mode python completation. but it default is python, how to change my default active interperter as ipython.

**Comment by proofit404** [comment]
anaconda-mode doesn't need ipython installed at all. Awesome `jedi` library used in background. All you need is to install anaconda-mode from melpa. All possible settings described in the readme. Feel free to ask any questions below.
