### ISSUE TITLE
Another: Blocking call to accept-process-output with quit inhibited!!

### ISSUE THREAD

**Issue by shaief** [proofit404/anaconda-mode#82]
I face some issues with `anaconda-mode` on a spacemacs distribution.
At the buttom of a buffer with python file opened i get this message:
```Blocking call to accept-process-output with quit inhibited!!```
My anaconda-mode buffer is full with this message:
```
emacs: /usr/local/bin/python: Exec format error 

Process anaconda_mode exited abnormally with code 126
```
i installed everything as described in lang Python (spacemacs). My OS is Arch Linux so my main Python is python3.4

Do you know how to solve it, and make it possible to work on Python in spacemacs?

Thanks!

**Comment by proofit404** [comment]
Maybe following command will clarify situation a bit.

    M-: (anaconda-mode-complete-at-point) RET

Do it from the python buffer.

**Comment by shaief** [comment]
Thanks! i don't have this command...

**Comment by proofit404** [comment]
You need to eval this code with `M-:` not `M-x`.

**Comment by shaief** [comment]
i'm sorry - it might sound stupid question but do you mean Meta and column?
i can't use it for some weird reason.
i can use `SPC :` (M-X) though...

**Comment by proofit404** [comment]
Read `evil` package documentation how to turn on Emacs state.

**Comment by shaief** [comment]
Well - apparently i needed to run M-x and then eval-expression
When running:
`(anaconda-mode-complete-at-point) RET`
I got the following:
```
Debugger entered--Lisp error: (void-variable anaconda-mode-complete-at-point)
  eval(anaconda-mode-complete-at-point nil)
  eval-expression(anaconda-mode-complete-at-point nil)
  call-interactively(eval-expression record nil)
  command-execute(eval-expression record)
  helm-M-x()
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

Any idea?

**Comment by shaief** [comment]
OK. It seems like it works, but only after i manually:
```M-ESC : (anaconda-mode-complete-at-point) RET```
Thanks!

Do you know how should i make it start with spacemacs?

**Comment by proofit404** [comment]
I'm not familiar with evil and spacemacs. Maybe you should ask in any of this projects issues. Standard way to get completions in emacs is `C-M-i`. If you activate anaconda-mode you should see proper completions.
