### ISSUE TITLE
parsing sklearn error

### ISSUE THREAD

**Issue by dzhwinter** [proofit404/anaconda-mode#84]
i use company as front-end 
anaconda-mode as backend
the error message is
Company: An error occurred in auto-begin                           |~                                                                      
259Company: Back-end company-anaconda error "JSON-RPC error condition\|~                                                                      
   : :data, (:type "ImportError" :args ("No module named joblib") :me\|~                                                                      
   ssage "No module named joblib"), :code, -32000, :message, "Server \|~                                                                      
   error"" with args (candidates )

emacs: 24.3
python 2.7.6
scikit-learn 0.16.1

**Comment by proofit404** [comment]
`*anaconda-mode*` buffer content?
