### ISSUE TITLE
Anaconda mode with anaconda

### ISSUE THREAD

**Issue by silgon** [proofit404/anaconda-mode#87]
Sorry for this post but this is more a question than an issue.
In the read me file of anaconda-mode it says that you can load a virtual environment with

```python
(setq python-shell-virtualenv-path "/path/to/virtualenv")
```
I'm using [Anaconda](https://store.continuum.io/cshop/anaconda/) to work as my virtual environment, is there any approach for this kind of virtual environment?

P.S. My first thought was that the name anaconda-mode probably came from this [Anaconda](https://store.continuum.io/cshop/anaconda/), and therefore it should be implemented. But I'm not sure so I needed to ask. =)

**Comment by proofit404** [comment]
Hello. No problem. Suppose your anaconda executable is `/home/u/anaconda/bin/python`. You can try to set `python-shell-virtualenv-path` to `/home/u/anaconda`.

By the way anaconda-mode name was inspired by excellent sublime text [anaconda](https://github.com/DamnWidget/anaconda) plug-in. Both use [jedi](https://github.com/davidhalter/jedi) library under the hood.

**Comment by silgon** [comment]
nice, it works, thanks ;)

**Comment by proofit404** [comment]
You're welcome.
