### ISSUE TITLE
Update to new version of undercover.el

### ISSUE THREAD

**Issue by sviridov** [proofit404/anaconda-mode#90]
@proofit404 Hi! I just released a new version of `undercover.el` which has backward incompatible API change related to `:report-file` option.

Old version of API:

- Set `report-file` option if you want to save coverage report locally.

New version of API:

- Set `report-file` option if you want to change report location. `undercover.el` will try to merge new report with existing one.
- Set `send-report` option to `nil` if you want to save coverage report locally.

So, you need to add `(:send-report nil)` to your `undercover.el` configuration. I'm sorry for the inconvenience and for not opening a PR for that.

**Comment by proofit404** [comment]
Thanks for report! Done.

**Comment by proofit404** [comment]
Thanks one more time.
