### ISSUE TITLE
six package fails to install via pip

### ISSUE THREAD

**Issue by holocronweaver** [proofit404/anaconda-mode#91]
anaconda-mode is trying to download a Python package called `six` which fails to install. Here is the error message from my anaconda-mode message buffer:

```
Downloading/unpacking six (from service-factory)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: jedi, service-factory, six
Cleaning up...
[31mException:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 309, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 140, in move_wheel_files
    scheme = distutils_scheme(name, user=user, home=home, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 155, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```
Not clear to me from the traceback message why the failure is occurring.

Maybe [this](http://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install) is related?

**Comment by proofit404** [comment]
Looks like old known pip bug covered in [issues](https://github.com/proofit404/anaconda-mode#issues) section.

**Comment by holocronweaver** [comment]
Yep, that seems to do the trick. Could an error message pointing to the issues section be printed when pip fails like that?

**Comment by proofit404** [comment]
Seems like good idea to me.  To implement it I need additional information. Distutil config file content with problem persist. Similar info with problem solved.  Also can you try first configuration with last version of pip (>=7.0.1)?

**Comment by holocronweaver** [comment]
I actually fixed the problem by installing the anaconda-mode dependencies manually, so I am not sure how to test it again via modifying the distutils file.

**Comment by proofit404** [comment]
`pip uinistall jedi`

**Comment by holocronweaver** [comment]
Sorry, I misunderstood. Where is the `distutils.cfg` I am supposed to be modifying located? Assuming it is a system file, I did `locate distutils.cfg` and got nothing. Searching in the anaconda-mode folder for a *.cfg file also turned up empty handed.

**Comment by proofit404** [comment]
I thought it was caused by [pip bug](http://bugs.python.org/issue22269). `prefix` option specified in the `distutils.cfg` will block `pip -t .` option work.

**Comment by proofit404** [comment]
Close due to #113

**Comment by x-ji** [comment]
I recently upgraded to Ubuntu 16.04 LTS and had this error. I ran pip in the command line manually via `sudo pip install  jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2` but it didn't solve the error. I looked into the folder /usr/lib/python2.7/distutils/ but there is no `distutils.cfg` file present there. What should I do now?

**Comment by proofit404** [comment]
What is your pip version? What files stored in the `~/.emacs.d/anaconda-mode/0.1.1/` folder?

**Comment by x-ji** [comment]
pip version: pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

I'm installing anaconda-mode via Spacemacs' Python layer. There doesn't seem to be a `~/.emacs.d/anaconda-mode` folder. There is a `anaconda-mode-20160411.650` folder in ~/.emacs.d/elpa` which has

- `anaconda-mode.el`
- `anaconda-mode-autoloads.el`
- anaconda-mode-pkg.el`

I'm not sure if they are relevant

**Comment by proofit404** [comment]
Look at the value of `anaconda-mode-installation-directory`.

**Comment by x-ji** [comment]
I see. It's in `~/.emacs.d/.cache.anaconda-mode/0.1.1`. There is nothing in the folder.

**Comment by proofit404** [comment]
That's the problem. There must be installed anaconda-mode python package. Try following workaround:

    cd ~/.emacs.d/.cache.anaconda-mode/0.1.1
    pip install -t . anaconda_mode

**Comment by x-ji** [comment]
That seems to solve it. Thanks. Is this situation actually different from the one in the original issue? Maybe a new section in issues part of README file can be added to help confused users with this error. Or is it more likely an issue on the part of Spacemacs and I should report it there?

**Comment by proofit404** [comment]
This is definitely another issue. But I don't understand why your installation directory is empty.

**Comment by x-ji** [comment]
Hmm. Maybe there's something wrong with my directory permissions? Maybe treat it as a ubiquitous occurrence now until more people report the same bug. Let's see. Thanks for the help.

**Comment by bb4242** [comment]
I just encountered this issue with the same setup (installing anaconda-mode via spacemacs on ubuntu 16.04).  However, the workaround (`cd ~/.emacs.d/.cache/anaconda-mode/0.1.1; pip install -t . anaconda_mode`) didn't work for me:

```
╭─bbethke@roland  ~/.emacs.d/.cache/anaconda-mode/0.1.1  ‹master› 
╰─$ pip install -t . anaconda_mode
^FCollecting anaconda_mode
Collecting jedi>=0.9.0 (from anaconda_mode)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda_mode)
Collecting six (from service-factory>=0.1.2->anaconda_mode)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: jedi, six, service-factory, anaconda-mode
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

**Comment by x-ji** [comment]
@bb4242 Just a guess. Did you run pip with sudo? I think it could be a permission error.

**Comment by bb4242** [comment]
Hmm, my understanding was that `pip install -t . <packages>` was supposed to install the packages into the current directory, which is owned by my user and thus shouldn't require root privileges to write into.  The directory I'm trying to install into is definitely writable by my user.

Will spacemacs attempt to use a system-wide install of `anaconda-mode` if it's present, or does it always require it to be installed to `~/.emacs.d/.cache/anaconda-mode/0.1.1`?  If it'll try using a system package, I could probably work around it by doing a system-wide `sudo pip install anaconda-mode`.  If it won't, I could install it system-wide and then copy the package into `~/.emacs.d/.cache/anaconda-mode/0.1.1`.  But either way, it does seem like there is a more fundamental bug with distutils in ubuntu 16.04, because none of those workarounds were necessary in 15.10.

Thanks for your help with this! :)

**Comment by proofit404** [comment]
Anaconda mode will use locally installed package if any and ignore system wide installation at all.
