### ISSUE TITLE
How to config virtualenv on Windows

### ISSUE THREAD

**Issue by xuehao** [proofit404/anaconda-mode#92]
I use prelude emacs on Windows. The system Python is 3.4.3.
Follow the Usage, I add `(setq python-shell-virtualenv-path "C:\venv") ` in my personal configuration.
But it doesn't work.

**Comment by proofit404** [comment]
Please post `*anaconda-mode*` buffer content.

**Comment by xuehao** [comment]
I add the following into my config init.el

` (setq python-shell-virtualenv-path "C:\\Users\\Mike\\flaskenv\\Scripts")`

`*anaconda-mode*` buffer is empty. 
![1](https://cloud.githubusercontent.com/assets/2335731/8197891/54c652ca-14d1-11e5-964a-8e6328ea81f0.PNG)

I tried to use `pyenv-mode`, the following is like this.
![2](https://cloud.githubusercontent.com/assets/2335731/8197893/5a50f1b4-14d1-11e5-9e9d-f992092f8bf9.PNG)

**Comment by xuehao** [comment]
Oh, my god. I just switch the config into `prelude-python.el`.
It was fixed right now. I close this issue.

**Comment by proofit404** [comment]
Glade you solve it :D 

Actually I think pyenv tool will not work on Windows.

**Comment by xuehao** [comment]
Yes. `pyenv` is annoying to use both under win and ubuntu. I don't even understand the tutorial of the mode.

But I find a new mode `pyvenv-mode`. It works fine under win and ubuntu.

I suggest `anaconda-mode` ships with a good virtualenv tool.

**Comment by proofit404** [comment]
To understand `pyenv-mode` tutorial you need to understand `pyenv` tool completely. Personally I think `pyenv` is the best tool for python installation available under unix-like operation systems.

Anaconda-mode has nothing to deal with virtualenv management so it just follows your choice.
