### ISSUE TITLE
Is it possible to auto complete in python-shell?

### ISSUE THREAD

**Issue by xin-jin** [proofit404/anaconda-mode#93]
As the title asks. I enable the same modes as in the python-mode:
```
(add-hook 'py-python-shell-mode-hook 'ac-anaconda-setup)
(add-hook 'py-python-shell-mode-hook 'anaconda-mode)
(add-hook 'py-python-shell-mode-hook 'eldoc-mode)
```

However, it only does some basic completion. For example, "im" can be completed to "import". But "os.getc" will not complete to "os.getcwd" (while it is working well in the python-mode buffer).

**Comment by xin-jin** [comment]
wait. This is strange. The other packages like "glob" and "sys" auto-complete in python-shell without problems, but "os" does not.

**Comment by proofit404** [comment]
I'm sorry I'm not familiar with `python-mode`. I think this is because of comint pointer behavior. You can fix it your self and perform pull request. Don't forget to write test case to prove your fix.
