### ISSUE TITLE
Some questions about install instructions

### ISSUE THREAD

**Issue by john2x** [proofit404/anaconda-mode#95]
I installed anaconda-mode via `package-install`, and I think it's working since `C-M-i` brings up the completion buffer. But I have some questions/problems regarding my setup:

1. One problem is that it doesn't respect the `python-shell-virtualenv-path`. The completion options are only the built-in Python libraries.
2. I see there is a `requirements.txt` file. Is `package-install` supposed to install that automatically? Or do I need to install it with pip manually afterwards? (it's not mentioned in the docs)
3. Do I need to copy `anaconda_mode.py` anywhere?
4. (slightly off-topic) I also installed `company-anaconda` and have added it to `company-backends`. But when I do `C-M-i`, it still uses the non-company completion buffer (and if I'm not mistaken company offers completion automatically with no keys needed?)

**Comment by proofit404** [comment]
To solve virtualenv issue I need `*anaconda-mode*` buffer content.

`anaconda-mode` will install its python side automatically for you. You doesn't need to do anything.

`company-mode` doesn't overwrite `C-M-i` by default. You can bind `company-complete` manually to you favorite key binding.

**Comment by john2x** [comment]
Thanks for clearing those up.

But I can't seem to find the `*anaconda-mode*` buffer. But I do have `anaconda-mode` enabled already.

**Comment by proofit404** [comment]
`*anaconda-mode*` buffer appears after first command related to this mode. Start completions process, initiate documentation lookup or enable `eldoc-mode` and move point around.

**Comment by john2x** [comment]
Strange, still don't see the `*anaconda-mode*` buffer after trying `C-M-i` (which brought up the completion buffer) and `eldoc-mode`.

Let me get back to this later. I'll uninstall all things related to anaconda and start over.

**Comment by proofit404** [comment]
I can look at your configuration if you publish it on some code sharing hosting.

**Comment by john2x** [comment]
Oh cool. (I've actually just finished moving my config to an Org file :-)

My packages are installed at http://www.john2x.com/init.html#sec-1-6

Python stuff happens at http://www.john2x.com/init.html#sec-1-7-8-1

And company is configured at http://www.john2x.com/init.html#sec-1-7-7-1

Thanks for taking the time!

**Comment by proofit404** [comment]
Looks like you setup `anaconda-mode` properly. Try to restart emacs, set `python-shell-virtualenv-path` variable, open new python file `test.py`, write `import <two first letters of the package name installed in your env`. `*anaconda-mode*` buffer must appears in you buffer list.

**Comment by john2x** [comment]
`*anaconda-mode*` finally showed up. Here's its contents:

```
Python executable: /Users/john/.virtualenvs/prospecthive/bin/python
jedi version: 0.9.0
service_factory version: 0.1.2
anaconda_mode port 9000
```

And a screenshot, if it helps
![test_py](https://cloud.githubusercontent.com/assets/332885/8445550/561ee762-1fd1-11e5-9e50-d7258409a47c.png)

**Comment by john2x** [comment]
Ah crap. I am so sorry, I just remembered that I was working in a VM all this time. It hit me like a wall when I typed `vagrant up` to start my day. *sigh*

Problem was between keyboard and chair.

**Comment by proofit404** [comment]
Glad you solve it.
