### ISSUE TITLE
anaconda-mode fails when I try to complete - looks like it's incorrectly pulling OSX Python rather than anaconda?

### ISSUE THREAD

**Issue by feoh** [proofit404/anaconda-mode#96]
Hi there;

All of a sudden today when I hit C-M-i to get a completion, I keep getting the dread "Unable to run anaconda-mode server".

Checking the anaconda mode buffer, I see:
```

Process anaconda_mode exited abnormally with code 1
Traceback (most recent call last):
  File "/Users/cpatti/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 38, in <module>
    pip = Popen(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

And see that repeated a few times over.

Any idea how I can get anaconda-mode.py to use the anaconda python which is correctly in my PATH?

I'm using the latest emacs 25.0.50.1 with the Cocoa GUI.

**Comment by proofit404** [comment]
Can you provide `exec-path` and `python-shell-virtualenv-path` variables values here? Do you use `exec-path-from-shell` package?

**Comment by feoh** [comment]
here's my exec-path:
```
exec-path
("/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs/HEAD/libexec/emacs/25.0.50/x86_64-apple-darwin14.3.0" "/Users/cpatti/anaconda/bin" "/usr/local/bin")
```

python-shell-virtualenv-path isn't defined.

I'd initially had trouble because anaconda mode couldn't find pip, ag mode couldn't find ag, etc. So I added the following to my init.el:

```
;; Add all the groovy locally installed packages to emacs exec path
(setenv "PATH" (concat (getenv "PATH") "/Users/cpatti/anaconda/bin:/usr/local/bin"))
(setq exec-path (append exec-path '("/Users/cpatti/anaconda/bin") '("/usr/local/bin")))
```

Should I in fact be using exec-path-from-shell instead? I just found that on the web yesterday and had been considering it.

**Comment by feoh** [comment]
@proofit404 Thanks so much for your response,  it contained the clue I needed :) Using exec-package-from-shell worked, and now completion and everything else work perfectly.  Thank you!

**Comment by proofit404** [comment]
Glad you solve it. You're welcome.
