### ISSUE TITLE
can't change default python version

### ISSUE THREAD

**Issue by xuehao** [proofit404/anaconda-mode#97]
I want  to change default python2 to 3 on my ubuntu. Could you give some tips?

I tried to add 
> (setenv "PYTHONPATH" "/usr/bin/python3.4")

but it doesn't work

Then I tried to use
> M-x setenv [RET] PYTHONPATH [RET] /usr/bin/python3.4

still not work.

```
Python executable: /usr/bin/python
jedi version: 0.9.0
service_factory version: 0.1.2
anaconda_mode port 9000
Python executable: /usr/bin/python
jedi version: 0.9.0
service_factory version: 0.1.2
anaconda_mode port 9000

Process anaconda_mode<1> killed

Process anaconda_mode killed
Python executable: /usr/bin/python
jedi version: 0.9.0
service_factory version: 0.1.2
anaconda_mode port 9000
```

**Comment by proofit404** [comment]
It's doesn't straightforward in current state. You need to set `/usr/bin/python` link to point to the necessary python.

Currently I'm working on `pythonic` package to solve this problem. Wait for a while.
