### ISSUE TITLE
Don't remap find-tag or pop-tag-mark; bind the actual keys

### ISSUE THREAD

**Issue by dgutov** [proofit404/anaconda-mode#99]
In Emacs 25, these commands have no bindings.

**Comment by novakboskov** [comment]
It seems to me that it is not just binding problem. I'm relatively new to Emacs but I tried some debug.
System is Emacs 25.0.50.1, Ubutnu 14.04 and it is Python 2.7.6.
The example is:
```python
example_hello_model = hello_meta.model_from_file("example.hello")
from textx.export import model_export
model_export(e-|-xample_hello_model, "example.dot")
```
and for that one it produces an anaconda-mode-call in anaconda-mode.el like this:
```elisp
(defun anaconda-mode-call (command)
  "Make remote procedure call for COMMAND."
   ...
  ;; use list since not all dash functions operate on vectors
  (let ((json-array-type 'list))
    (json-rpc
     anaconda-mode-connection
     command => goto_definitions
     (buffer-substring-no-properties (point-min) (point-max)) =>  whole text
     (line-number-at-pos (point)) => 9 [OK]
     (- (point) (line-beginning-position)) => 14 [OK]
     (anaconda-mode-file-name) => appropriate absolute path)))
```
and than:
```elsip
(defun anaconda-mode-goto-definitions ()
  "Goto definition for thing at point."
  (interactive)
  (anaconda-nav-navigate
   (or (anaconda-mode-call "goto_definitions") => nil
       (error "No definition found"))
   t))
```
when it call goto_definitions function returns empty list:
```python
def goto_definitions(script): => script = <Script: u'[appropriate absolute path]'>
    return script.goto_definitions() => []
```

**Comment by dgutov** [comment]
It's a different issue, but yes, I've also seen stability issues in Emacs 25. First it works, then it doesn't (doesn't find the definitions, say). I haven't investigated this further.

**Comment by novakboskov** [comment]
Should I open new issue for this one above?

**Comment by proofit404** [comment]
Will fix exactly this issue at the end of `feature/pypi` branch. Actual Emacs 25 support with `xref` integration will become a bit later.

**Comment by dgutov** [comment]
Note that I'm not asking for `xref` support now. It's API is has not stabilized yet.

**Comment by proofit404** [comment]
I understand. This is exactly what I mean.

**Comment by novakboskov** [comment]
Now I see few things...
I forgot to mention that function which I have tested was 'anaconda-mode-goto-definitions', and 'anaconda-mode-goto' actually works in this case.
This with 'anaconda-mode-goto-definitions' is totally different issue.
Sorry for confusion.

**Comment by proofit404** [comment]
Done.
